### ISSUE TITLE
Issue when send first message 

### ISSUE THREAD

**Issue by bhavesh53** [tulir/whatsmeow#10]
hello ,
          i am getting weird problem . when ever i send message to any number first time its shows error to receiver's mobile . from 2nd message onwords its working fine . shows waiting for this message.This may takes a while.

![139803571-fea86aab-5f6e-4756-a9c2-01ef308c8c1b](https://user-images.githubusercontent.com/1794741/139913007-dc89686c-5251-446d-b5cb-4a4762dfc754.jpeg)

**Comment by Romerito007** [comment]
> hello , i am getting weird problem . when ever i send message to any number first time its shows error to receiver's mobile . from 2nd message onwords its working fine . shows waiting for this message.This may takes a while. ![WhatsApp Image 2021-11-02 at 12 55 53 PM](https://user-images.githubusercontent.com/1794741/139803571-fea86aab-5f6e-4756-a9c2-01ef308c8c1b.jpeg)

Same, second message sends.

**Comment by Romerito007** [comment]
> > hello , i am getting weird problem . when ever i send message to any number first time its shows error to receiver's mobile . from 2nd message onwords its working fine . shows waiting for this message.This may takes a while. ![WhatsApp Image 2021-11-02 at 12 55 53 PM](https://user-images.githubusercontent.com/1794741/139803571-fea86aab-5f6e-4756-a9c2-01ef308c8c1b.jpeg)
> 
> **Same, second message sends.**

**When I send the first message** [Client WARN] Failed to fetch prekey for 552220400210.0:1@s.whatsapp.net: invalid prekey in prekey response: prekey node doesn't contain ID tag

**Comment by gabrielphilipes** [comment]
Hi!

I'm having this problem, the first message I send is always waiting to be received.

Arrived is there any solution?

**Comment by Romerito007** [comment]
> Hi!
> 
> I'm having this problem, the first message I send is always waiting to be received.
> 
> Arrived is there any solution?

I resolved by saving message data, when I get retry I send messages again.

**Comment by Valdenirmezadri** [comment]
> > Hi!
> > I'm having this problem, the first message I send is always waiting to be received.
> > Arrived is there any solution?
> 
> I resolved by saving message data, when I get retry I send messages again.
> 
> [Maybe this commit could handle it somehow](https://github.com/tulir/whatsmeow/blob/main/receipt.go#L23)

Hello Romero, 

in this case, do you send the revoke message and resend message as a new message?

**Comment by beshoo** [comment]
Even if it works, It will affect your number since it is not a normal
pattern to send messages in WhatsApp

**Comment by Romerito007** [comment]
> > > > Hi!
> > > > I'm having this problem, the first message I send is always waiting to be received.
> > > > Arrived is there any solution?
> > > 
> > > 
> > > I resolved by saving message data, when I get retry I send messages again.
> > > [Maybe this commit could handle it somehow](https://github.com/tulir/whatsmeow/blob/main/receipt.go#L23)
> > 
> > 
> > Hello Romero,
> > in this case, do you send the revoke message and resend message as a new message?
> 
> I send the same data with the same id

You can resend here https://github.com/tulir/whatsmeow/blob/main/retry.go#L167, you already have the message data

**Comment by Valdenirmezadri** [comment]
> > > > > Hi!
> > > > > I'm having this problem, the first message I send is always waiting to be received.
> > > > > Arrived is there any solution?
> > > > 
> > > > 
> > > > I resolved by saving message data, when I get retry I send messages again.
> > > > [Maybe this commit could handle it somehow](https://github.com/tulir/whatsmeow/blob/main/receipt.go#L23)
> > > 
> > > 
> > > Hello Romero,
> > > in this case, do you send the revoke message and resend message as a new message?
> > 
> > 
> > I send the same data with the same id
> 
> You can resend here https://github.com/tulir/whatsmeow/blob/main/retry.go#L167, you already have the message data

but being a private function, how do you call it? because it's not automatic

**Comment by Romerito007** [comment]
> > > > > > Hi!
> > > > > > I'm having this problem, the first message I send is always waiting to be received.
> > > > > > Arrived is there any solution?
> > > > > 
> > > > > 
> > > > > I resolved by saving message data, when I get retry I send messages again.
> > > > > [Maybe this commit could handle it somehow](https://github.com/tulir/whatsmeow/blob/main/receipt.go#L23)
> > > > 
> > > > 
> > > > Hello Romero,
> > > > in this case, do you send the revoke message and resend message as a new message?
> > > 
> > > 
> > > I send the same data with the same id
> > 
> > 
> > You can resend here https://github.com/tulir/whatsmeow/blob/main/retry.go#L167, you already have the message data
> 
> but being a private function, how do you call it? because it's not automatic

I I edited, maybe someone has a better approach

**Comment by ramacatur** [comment]
> but being a private function, how do you call it? because it's not automatic

I think this is automatically send retry message. 

[https://github.com/tulir/whatsmeow/blob/main/receipt.go#L25](https://github.com/tulir/whatsmeow/blob/main/receipt.go#L25)

But, my message still waiting.

**Comment by Romerito007** [comment]
> > but being a private function, how do you call it? because it's not automatic
> 
> I think this is automatically send retry message.
> 
> https://github.com/tulir/whatsmeow/blob/main/receipt.go#L25
> 
> But, my message still waiting.

I believe so.

**Comment by ramacatur** [comment]
> > > but being a private function, how do you call it? because it's not automatic
> > 
> > 
> > I think this is automatically send retry message.
> > https://github.com/tulir/whatsmeow/blob/main/receipt.go#L25
> > But, my message still waiting.
> 
> I believe so.

i just tried to send to a number that is not in contacts. Message is still waiting and my number is blocked.

**Comment by Romerito007** [comment]
> > > > but being a private function, how do you call it? because it's not automatic
> > > 
> > > 
> > > I think this is automatically send retry message.
> > > https://github.com/tulir/whatsmeow/blob/main/receipt.go#L25
> > > But, my message still waiting.
> > 
> > 
> > I believe so.
> 
> i just tried to send to a number that is not in contacts. Message is still waiting and my number is blocked.

add  cli.SendMessage(receipt.Chat, messageID, msg) [below the line, take the tests](https://github.com/tulir/whatsmeow/blob/main/retry.go#L167)

**Comment by Valdenirmezadri** [comment]
> > > > > but being a private function, how do you call it? because it's not automatic
> > > > 
> > > > 
> > > > I think this is automatically send retry message.
> > > > https://github.com/tulir/whatsmeow/blob/main/receipt.go#L25
> > > > But, my message still waiting.
> > > 
> > > 
> > > I believe so.
> > 
> > 
> > i just tried to send to a number that is not in contacts. Message is still waiting and my number is blocked.
> 
> add cli.SendMessage(receipt.Chat, messageID, msg) [below the line, take the tests](https://github.com/tulir/whatsmeow/blob/main/retry.go#L167)

It worked, ty Romerito

**Comment by Romerito007** [comment]
@Valdenirmezadri  be careful when adding this function to cli.SendMessage(receibo.Chat, messageID, msg), when sending message to verified accounts, it will cause a loop. uses this number as an example of tests 551131361384

**Comment by Valdenirmezadri** [comment]
> be careful when adding this function to cli.SendMessage(receibo.Chat, messageID, msg), when sending message to verified accounts, it will cause a loop. uses this number as an example of tests 551131361384

if I've already verified that the account exists, you say?

**Comment by Valdenirmezadri** [comment]
i made this pull #25

**Comment by tulir** [comment]
Responding to retry receipts should work properly now
