### ISSUE TITLE
Aligning 'ButtonsMessage' in line horizontally

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#101]
In my code below, I was able to send `ButtonsMessage` with 3 buttons that are sorted in vertical way, is there a way that I can put couple of buttons in line, so I reduce the number of lines as shown in the image below?:
```go
	msg := &waProto.Message{ButtonsMessage: &waProto.ButtonsMessage{
		HeaderType:  waProto.ButtonsMessage_EMPTY.Enum(),
		ContentText: proto.String("Hi, who are you"),
		FooterText:  proto.String("من معي؟"),
		Buttons: []*waProto.Button{
			{
				ButtonId: proto.String("id1"),
				ButtonText: &waProto.ButtonText{
					DisplayText: proto.String("مورد"),
				},
				Type: waProto.Button_RESPONSE.Enum(),
			},
			{
				ButtonId: proto.String("id2"),
				ButtonText: &waProto.ButtonText{
					DisplayText: proto.String("مشرف فرع"),
				},
				Type: waProto.Button_RESPONSE.Enum(),
			},
			{
				ButtonId: proto.String("id3"),
				ButtonText: &waProto.ButtonText{
					DisplayText: proto.String("صاحب إمتياز"),
				},
				Type: waProto.Button_RESPONSE.Enum(),
			},
		},
	}}
	jid, ok := parseJID("966xxxxx")
	if !ok {
		return
	}
	_ = msg
	send, err := cli.SendMessage(jid, "", msg) // jid = recipient

	if err != nil {
		log.Errorf("Error sending message: %v", err)
	} else {
		log.Infof("Message sent (server timestamp: %s)", send)
	}
```

![image](https://user-images.githubusercontent.com/98168280/165309217-91607900-fb9e-4997-a0ad-c2575341f1c4.png)

**Comment by tulir** [comment]
In general, the easiest way to find out how to do something is to receive a message and print the contents.

`nativeFlowInfo` sounds like it might be relevant, but it has a generic json field so I don't know what it should contain.

**Comment by Duckduckgot** [comment]
I think it automatically changes the width, if the text in the two buttons is short enough, then it turns out like on the screenshot.
![photo_2022-05-06_11-32-03](https://user-images.githubusercontent.com/49223254/167057449-5ad1a10f-dffe-4954-ab4a-44ca6629ef8f.jpg)
