### ISSUE TITLE
Sending document

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#102]
I need to send a document file, it is saved as `./documents/ContractTerms.pdf` so I wrote the below code, but documents had not been sent, what am I missing here?

```go
package bots

import (
	"fmt"

	"github.io/hajsf/whatsapp/global"
	waProto "go.mau.fi/whatsmeow/binary/proto"
	"google.golang.org/protobuf/proto"
)

func SendContract(sender string) {
	fmt.Println("sending file")
	msg := &waProto.Message{
		DocumentMessage: &waProto.DocumentMessage{
			DirectPath: proto.String("./documents/ContractTerms.pdf"),
		},
	}

	jid, ok := global.ParseJID(sender)
	if !ok {
		return
	}
	send, err := global.Cli.SendMessage(jid, "", msg) // jid = recipient

	if err != nil {
		global.Log.Errorf("Error sending message: %v", err)
	} else {
		global.Log.Infof("Message sent (server timestamp: %s)", send)
	}
}
```

**Comment by tulir** [comment]
You need to upload files before sending them https://pkg.go.dev/go.mau.fi/whatsmeow#Client.Upload (replace `ImageMessage` with `DocumentMessage`)

**Comment by hajsf** [comment]
> You need to upload files before sending them https://pkg.go.dev/go.mau.fi/whatsmeow#Client.Upload (replace `ImageMessage` with `DocumentMessage`)

What is `DirectPath:    &uploaded.DirectPath`
