### ISSUE TITLE
Access client instance on eventHandler

### ISSUE THREAD

**Issue by rvp98** [tulir/whatsmeow#108]
I read in the docs that i can be done by wrap the handler in another struct, but im sorry i still little bit confused>
Can someone show me some snippet how to implementing this please 

type MyClient struct {
    WAClient *whatsmeow.Client
    eventHandlerID uint32
}

func (mycli *MyClient) register() {
    mycli.eventHandlerID = mycli.WAClient.AddEventHandler(mycli.myEventHandler)
}

func (mycli *MyClient) myEventHandler(evt interface{}) {
     // Handle event and access mycli.WAClient
}

**Comment by tulir** [comment]
That is the implementation. Then you just create a `MyClient` with a `whatsmeow.Client` instance and call `.register()`.

**Comment by rvp98** [comment]
Hello sir thanks for the response @tulir 
Can you give a little bit example for this implementation :(
Im sorry
