### ISSUE TITLE
Sync contact store

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#112]
Hi, I was able to iterate over my saved contacts as:
```go
contacts, err := cli.Store.Contacts.GetAllContacts()
```

I found plenty of contacts, that looks I deleted before but still there, and I want to delete them permanently, it caused embarrassing for me once I wanted to send to ALL my existing contacts.

I thoughts about the below:
1. from the [https://sqliteonline.com/](https://sqliteonline.com/) I can opened the sql database created by whatsMeow
2. Delete all the data in this database under table `SELECT * FROM whatsmeow_contacts`
3. Sync back to WhatsApp server, so empty contacts be there.

My question is about the last point, how to syync back, unless if someone else advice another way to delete all the saved contacts in the whatsAppp server.

**Comment by tulir** [comment]
`cli.FetchAppState` with `appstate.WAPatchCriticalUnblockLow` as the type

**Comment by tulir** [comment]
Oh wait, if you mean how to update the store on the server (rather than sync data on server back to client), that's not supported (#31)
