### ISSUE TITLE
Howto send link preview?

### ISSUE THREAD

**Issue by Diden05** [tulir/whatsmeow#117]
This not worked :(

		`content := &waproto.Message{
			ExtendedTextMessage: &waproto.ExtendedTextMessage{
				Text:          proto.String(text),
				Title:         proto.String(title),
				CanonicalUrl:  proto.String(url),
				MatchedText:   proto.String(url),
				JpegThumbnail: thumb,
				Description:   proto.String(description),
			},
		}`

**Comment by Romerito007** [comment]
> This not worked :(
> 
> ```
> 	`content := &waproto.Message{
> 		ExtendedTextMessage: &waproto.ExtendedTextMessage{
> 			Text:          proto.String(text),
> 			Title:         proto.String(title),
> 			CanonicalUrl:  proto.String(url),
> 			MatchedText:   proto.String(url),
> 			JpegThumbnail: thumb,
> 			Description:   proto.String(description),
> 		},
> 	}`
> ```

format text with link, see if it works.

```
Text:          proto.String(fmt.Sprintf("%s %s", caption, link)),
```

**Comment by tulir** [comment]
Yeah the message probably has to contain the url (the same one as in `MatchedText`)

**Comment by david-botelho-mariano** [comment]
This question was answered at:
#356
