### ISSUE TITLE
Direct to catalog

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#118]
In the 'ButtonsMessage' is there a way to get the 'catalog' dialog to be opened upon the user click of the 'ButtonsMessage', the same way the catalog dialog is opened by clicking the button provided by WhatsApp itself?

**Comment by hrizal** [comment]
i think. with call this function  it is work too
https://github.com/tulir/whatsmeow/issues/21#issuecomment-1117123883

**Comment by Diden05** [comment]
@hajsf Hi! Did you manage to send a ProductMessage? You can send a catalog like this

```
		content := &waproto.Message{
			ExtendedTextMessage: &waproto.ExtendedTextMessage{
				Text:        proto.String("https://wa.me/c/"+jid),
				MatchedText: proto.String("https://wa.me/c/"+jid),
				Description: proto.String(description),
				Title:       proto.String(title),
				JpegThumbnail: thumb,
			},
		}

```
