### ISSUE TITLE
Message with ActionLink and CanonicalUrl

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#120]
Trying to send the user a message where he is having a link that if clicked a web page will be opened in the browser.
I found there are `Url`s and tried both as below but failed.
```go
	msg := &waProto.Message{
		Conversation: proto.String("Check Google"),
		ContextInfo: &waProto.ContextInfo{
			ActionLink: &waProto.ActionLink{
				Url:         proto.String("Google"),
				ButtonTitle: proto.String("http://google.com"),
			},
		},
	}
```
I tried using `CanonicalUrl` but it did not work as well.
```go
	_ = &waProto.Message{
		ExtendedTextMessage: &waProto.ExtendedTextMessage{
			Text:         proto.String("Google"),
			CanonicalUrl: proto.String("http://google.com"),
		},
	}
```

How can I get it done?

**Comment by tulir** [comment]
`CanonicalUrl` is a part of the url preview stuff, which also requires `MatchedText` and the preview metadata fields like `Title` and `Description`. As usual, you should just receive a message like the one you want to send and print the contents to find out how to send them yourself.
