### ISSUE TITLE
Send audio with waveform

### ISSUE THREAD

**Issue by diegostefano** [tulir/whatsmeow#121]
Hi, people!

How do I send the audio waveform in an audio message?

I know there's the `Waveform` field in the `AudioMessage` struct, with type `[]byte`, but what should I put in this field?

Should I use a tool like `ffmpeg` to gather this waveform data? If so, what should I query for?

**Comment by tulir** [comment]
Just put the waveform data there, figuring out how to generate it is up to you. It looks like native apps send it as 64 numbers between 0 and 100.
