### ISSUE TITLE
Reaction support

### ISSUE THREAD

**Issue by DrDeee** [tulir/whatsmeow#125]
It would be cool if Whatsmeow would support reactions

**Comment by DrDeee** [comment]
Can you give me a quick example, please?

**Comment by batara666** [comment]
just listen for default:

**Comment by DrDeee** [comment]
No, I want to send reactions

**Comment by Ased2235** [comment]
> No, I want to send reactions

https://github.com/tulir/whatsmeow/blob/a0a87653cff059f05c849585cbd928c07beab765/mdtest/main.go#L429
