### ISSUE TITLE
Latest version is 2.2216.8 but I get an error when setting it in clientpayload.go

### ISSUE THREAD

**Issue by brunoaduarte** [tulir/whatsmeow#128]
Latest version of WA Web is 2.2216.8, but if I manually set it on clientpayload.go I get an error saying it's newer than lastest (2.2216.7)

![image](https://user-images.githubusercontent.com/5354345/168114036-2f26923d-00dc-4387-84bb-cd9b206c7969.png)

```
12:38:30.801 [Main DEBUG] Version data: whatsmeow.CheckUpdateResponse{IsBroken:false, IsBelowSoft:false, IsBelowHard:false, CurrentVersion:"2.2216.7", ParsedVersion:store.WAVersionContainer{0x2, 0x8a8, 0x7}}←[0m
12:38:30.801←[36m [Main INFO] Client is newer than latest←[0m
```

**Comment by tulir** [comment]
That's not an error, it's just an info log repeating what https://web.whatsapp.com/check-update?version=2.2216.7&platform=web says
