### ISSUE TITLE
 failed to get device list

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#132]
Hi, I got this error:
```bash
[Main ERROR] Error sending message: failed to get device list: failed to send usync query: websocket disconnected before info query returned response
```

Could it be some thing related to bad internet connection or something else? I used to run the app smoothly for full week, but got this today (I know the internet connection here is bad, sometimes got disconnected), just need to be sure about the reason. Thanks

**Comment by Romerito007** [comment]
> Hi, I got this error:
> 
> ```shell
> [Main ERROR] Error sending message: failed to get device list: failed to send usync query: websocket disconnected before info query returned response
> ```
> 
> Could it be some thing related to bad internet connection or something else? I used to run the app smoothly for full week, but got this today (I know the internet connection here is bad, sometimes got disconnected), just need to be sure about the reason. Thanks

instability in whatsapp servers

**Comment by hajsf** [comment]
Now I'm getting more errors, when I'm trying to send document message:
```bash
[Main ERROR] Error sending message: failed to get device list: failed to send usync query: info query returned status 503: service-unavailable
```

And:
```bash
[Main ERROR] Error uploading document to whatsapp server: failed to execute request: Post "https://media.fdmm2-4.fna.whatsapp.net/mms/document/m9dbLvJ6VBS2BRgp71uQSiTFJcJe-nbuSaRXuw0M2b4=?auth=AWT_jk6yPzPvdZD3upwSaq2o0ii7zd3FlTB94Oq3k_w7s06G9ZIGlZcHLYs&token=m9dbLvJ6VBS2BRgp71uQSiTFJcJe-nbuSaRXuw0M2b4%3D": unexpected EOF
```

**Comment by qfpeeeer** [comment]
Hello, were you able to resolve this issue?

**Comment by qfpeeeer** [comment]
I still get this same error when I try to call the IsOnWhatsApp function

`failed to send usync query: websocket disconnected before info query returned response`
