### ISSUE TITLE
Changing app name in "Linked Devices" list applies to Android but not iOS devices.

### ISSUE THREAD

**Issue by MohamedAE** [tulir/whatsmeow#133]
Hello all.

I would like to change the displayed OS/client name in the _Linked Devices_ screen from "whatsmeow". Assigning the new name to `CompanionProps.Os` in the file `clientpayload.go` changes the name for Android devices but doesn't seem to apply to iOS devices. Is this a quirk of WhatsApp on iOS? Any thoughts or advice?

`clientpayload.go Ln. 63`
```
var CompanionProps = &waProto.CompanionProps{
	Os: proto.String("foo"),
	Version: &waProto.AppVersion{
		Primary:   proto.Uint32(0),
		Secondary: proto.Uint32(1),
		Tertiary:  proto.Uint32(0),
	},
	PlatformType:    waProto.CompanionProps_UNKNOWN.Enum(),
	RequireFullSync: proto.Bool(false),
}
```

Also tried reassigning `CompanionProps.Os` in `SetOsInfo(...)` in `clientpayload.go` doesn't apply the change either:

`clientpayload.go Ln. 74`
```
func SetOSInfo(name string, version [3]uint32) {
	CompanionProps.Os = proto.String("foo")
	CompanionProps.Version.Primary = &version[0]
	CompanionProps.Version.Secondary = &version[1]
	CompanionProps.Version.Tertiary = &version[2]
	BaseClientPayload.UserAgent.OsVersion = proto.String(fmt.Sprintf("%d.%d.%d", version[0], version[1], version[2]))
	BaseClientPayload.UserAgent.OsBuildNumber = BaseClientPayload.UserAgent.OsVersion
}
```

**Comment by tulir** [comment]
The iOS app probably just doesn't want to render any unrecognized names
