### ISSUE TITLE
error on first message

### ISSUE THREAD

**Issue by llabbasmkhll** [tulir/whatsmeow#139]
thanks for your perfect package. it is very useful.

when I send messages to non-existing chats the package shows no error but the message does not get delivered as shown:
![image](https://user-images.githubusercontent.com/86796762/170366640-bf7012f4-f131-40bc-aa36-c772b9a9b590.png)
the very first message does not deliver appropriately but the other messages 

I copied the code in mdtest (the part for sending messages)

**Comment by Nikitian** [comment]
Looks like double https://github.com/tulir/whatsmeow/issues/69

**Comment by tulir** [comment]
#160
