### ISSUE TITLE
Is this library be used for production? | Why, what purpose, how many numbers?

### ISSUE THREAD

**Issue by 1337-sys** [tulir/whatsmeow#141]
Anyone using this library for production?

Does anyone in a company or otherwise use this library? Can anyone say why, for what purpose and how many numbers they use this library?

**Comment by llabbasmkhll** [comment]
I am using this library for the company that I'm working for. we use it for CRM and support purposes. 10 numbers have registered so far and around 100 messages getting sent every day.

**Comment by moxovil** [comment]
I also use this library as an integration for CRM. Now my application works with 6500 active numbers. Sends about 1000 messages per minute. The solution is very good, the developer constantly makes updates.

**Comment by sumnerevans** [comment]
This is being used in https://github.com/mautrix/whatsapp/ which is deployed by multiple companies including Beeper and Element.

Also, this question is not appropriate for GitHub, you should ask on https://matrix.to/#/#whatsmeow:maunium.net

**Comment by sumnerevans** [comment]
@1337-sys please engage in nontechnical discussions such as this on the Matrix chat that I linked in my previous comment.
