### ISSUE TITLE
Is it possibe to add metadata for stickers? 

### ISSUE THREAD

**Issue by deven96** [tulir/whatsmeow#144]
I can send webp images as stickers and it works perfectly but I want to be able to add metadata about the creator of the sticker as those fields show up blank unlike stickers made manually 

Manual sticker 
![20220527_204323](https://user-images.githubusercontent.com/23453888/170779707-da5f7ec9-343d-47fb-8221-25dbc98deb0c.jpg)

Whatsmeow sticker
![20220527_204350](https://user-images.githubusercontent.com/23453888/170779760-dfca5402-8a9c-4561-9d7a-f9c7d2db4621.jpg)

**Comment by Duckduckgot** [comment]
This does not apply to this package.
Use [Node](https://www.npmjs.com/package/wa-sticker-formatter)

**Comment by deven96** [comment]
Really... so I change an entire project to node for just that? @Duckduckgot

**Comment by Ased2235** [comment]
> Really... so I change an entire project to node for just that? @Duckduckgot

You can create an api running on background & send & receive stickers from there that should work

**Comment by deven96** [comment]
Not everything should be a service. Thanks to the library @Duckduckgot  posted I figured out all I needed to know to realize the metadata was just exif data. I was able to modify it in golang by wrapping around [webpmux](https://developers.google.com/speed/webp/docs/webpmux)
