### ISSUE TITLE
Group names?

### ISSUE THREAD

**Issue by burstfreeze** [tulir/whatsmeow#15]
First of all congrats! Group names are not supported yet, right?

**Comment by tulir** [comment]
Depends on what you mean by supporting group names, but they're probably supported

**Comment by burstfreeze** [comment]
Sorry I mean the titles of group chats. I can find the titles for every person contact in the database but not a group name. (Baileys has the same issue btw)

**Comment by tulir** [comment]
Getting group info from the servers includes the name. The database only contains things that can't be easily fetched from the server
