### ISSUE TITLE
Is it necessary to use an ORM framework?

### ISSUE THREAD

**Issue by Aoang** [tulir/whatsmeow#156]
[whatsmeow](https://github.com/tulir/whatsmeow) is a great project.

The project use raw sql seems to be a laborious thing if you want to be compatible with other databases. I'm using [GORM](https://github.com/go-gorm/gorm) handles the compatibility of the database and using PostgreSQL. I'm doing some work in my test project, and I don't understand how  some parameters works, which leads to some  storage problems.

Is it possible to integrate ORM framework into whatsmeow?

If sure, is it possible to adjust the interface in [store](https://github.com/tulir/whatsmeow/blob/main/store/store.go)? Let it only have a pure data storage function.

Also, it would be great if you could help me understand what the parameters mean, and if you don't have time, you can write unit tests for the interface.

**Comment by tulir** [comment]
The default store supports Postgres and it works fine, so I probably don't want any extra bloat by default. You can already implement custom stores by doing the same things as the `sqlstore` package.

**Comment by Aoang** [comment]
What is holding me back that the complex interface of no unit tests's [Device](https://github.com/tulir/whatsmeow/blob/main/store/store.go#L102-L129), I don't know where is the error
