### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by amirsheikh** [tulir/whatsmeow#163]
Failed to pair device: failed to save device store: pq: null value in column "adv_account_sig_key" of relation "whatsmeow_device" violates not-null constraint

**Comment by tulir** [comment]
Are you doing something silly like using a new database with an old whatsmeow version?

**Comment by amirsheikh** [comment]
I created a database about 4 months ago, and now I use the latest version of the library.
I log in several times two days ago, but today when I want to log in again I got this error.
I have three instants of my program, but others work fine.
The version that got this error is my test application and two other one is used in production.
 After I got this error, I dropped the database and made another one so it works fine but lose all my logged in account.
Is it possible that two other version of my program Got this error?
What should i do?

**Comment by Ased2235** [comment]
I just updated & facing the same issue, i already deleted .db file @tulir
