### ISSUE TITLE
new(uint32)

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#177]
What shall I use to define the above, I aware if I got `*string` as `new(string)` then I use `proto.String("my text"),` but in my case I've to use `Index: new(uint32),` I tried to use `proto.int(1)` but it failed, what shall I use?

**Comment by Duckduckgot** [comment]
> What shall I use to define the above, I aware if I got `*string` as `new(string)` then I use `proto.String("my text"),` but in my case I've to use `Index: new(uint32),` I tried to use `proto.int(1)` but it failed, what shall I use?

proto.Uint32(uint32(86400))
