### ISSUE TITLE
[BUG] Failed to parse receipt when node contains multiple participants

### ISSUE THREAD

**Issue by a5r0n** [tulir/whatsmeow#179]
in some cases, (usually in `status@broadcast`) receipt node contains couple of participants childrens instead of one in the attrs.
so we need some logic to handle many receipt events in one Node..

@tulir if u can guide me a bit, i like to work on this.
```
[Client WARN] Failed to parse receipt: [didn't find required JID attribute 'participant']
```

```xml
<receipt from="status@broadcast" id="230XXX" t="165XXX30794" type="read">
	<participants key="3EB07XXXXXX246">
		<user jid="XXXXXXXXXXXX@s.whatsapp.net" t="165XXX794"/>
		<user jid="XXXXXXXXXX@s.whatsapp.net" t="165XXXX796"/>
	</participants>
</receipt>
```

**Comment by tulir** [comment]
You were 7 hours late https://github.com/tulir/whatsmeow/commit/bfb10aff31b90ba5a379b0d3652c041a694b0a3d
