### ISSUE TITLE
events.Message 

### ISSUE THREAD

**Issue by zahrayt299** [tulir/whatsmeow#184]
> That only contains the key, not the message. You can ignore those, whatsmeow will handle them automatically (it stores the key to use when the actual message is decrypted).

I know it's been handled, but why isn't it inserted in *events.Message

type Message struct {
	Info    types.MessageInfo // Information about the message like the chat and sender IDs
	Message *waProto.Message  // The actual message struct
	SenderDecryptedMessage *waProto.Message  // Decrypted SenderKeyDistributionMessagestruct
	.....
}
@tulir

_Originally posted by @zahrayt299 in https://github.com/tulir/whatsmeow/issues/166#issuecomment-1159812661_

**Comment by tulir** [comment]
Sender key messages is not something you can decrypt, it's a key to decrypt other messages. In general, there will be another message event immediately afterwards with the actual content, and future messages from the same user won't have the sender key message at all.
