### ISSUE TITLE
How to Set Browser UserAgent Information

### ISSUE THREAD

**Issue by cuiyinglu2008** [tulir/whatsmeow#185]
I want to use different UA information for different numbers
For example: chrome under windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

thanks in advance

**Comment by tulir** [comment]
https://github.com/tulir/whatsmeow/blob/main/store/clientpayload.go#L103-L146

(you can assign them directly in your code, e.g. `store.DeviceProps.PlatformType = waProto.DeviceProps_CHROME.Enum()`)
