### ISSUE TITLE
 [Main ERROR] Error sending message: failed to get device list: failed to send usync query: info query timed out

### ISSUE THREAD

**Issue by nawi** [tulir/whatsmeow#188]
Suddenly, I got this error message today, then I check mdtest example for simple sending message like this

```./mdtest send '<620810000000@s.whatsapp.net>' 'test'```

nothing in reeceived response or log

**Comment by Diden05** [comment]
same problem

**Comment by AndhikaAdjie** [comment]
@tulir what is the solution of this issue ? i got same problem :(

**Comment by azickri** [comment]
@tulir any update on this issue? This happens when a user sends many messages at the same time.

**Comment by trickaugusto** [comment]
Good morning guys!
I had the same problem, but **I think** that I found the solution. 

The error message doesn't so clarity, but I saw a pattern:

In my app, I receive phones with different formats, like:
+5541987654321, 41987654321 or 5541987654321.

And all the times that I tried to send a message with + in the string, I would receive the error _**"failed to get device list: failed to send usync query: info query timed out"**_

And I just forgot to clean the + to the string:
`number = strings.ReplaceAll(number, "+", "")`

I don't know if this is the unique cause of the error, but maybe can help you =)

**Comment by zxkletters** [comment]
> Good morning guys! I had the same problem, but **I think** that I found the solution.
> 
> The error message doesn't so clarity, but I saw a pattern:
> 
> In my app, I receive phones with different formats, like: +5541987654321, 41987654321 or 5541987654321.
> 
> And all the times that I tried to send a message with + in the string, I would receive the error _**"failed to get device list: failed to send usync query: info query timed out"**_
> 
> And I just forgot to clean the + to the string: `number = strings.ReplaceAll(number, "+", "")`
> 
> I don't know if this is the unique cause of the error, but maybe can help you =)

Great! That work for me.
