### ISSUE TITLE
Can I capture stdout log in real time inside my code

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#200]
I aware we can display the log at the reminal as below:
```go
clientLog := waLog.Stdout("Client", "ERROR", true)
```

Is there a way that I can read these errors inside my code itself, something like:
```go
go func(){
     log = captureLog()
     fmt.Println("log:", log)
}
```
For example, in my system, upon removing the app from the connected devices list in my mobile WhatsApp application, I got the below:
```bash
12:58:04.229 [Client/AppState ERROR] Failed to update app state version in the database: FOREIGN KEY constraint failed
12:58:04.229 [Client/AppState ERROR] Failed to insert added mutation MACs to the database: FOREIGN KEY constraint failed
12:58:04.299 [Client/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF
```
Is there a way, that in my code, I get these errors in my code, so for example for the first error/log line, I get my code printing:
```bash
log: 12:58:04.229 [Client/AppState ERROR] Failed to update app state version in the database: FOREIGN KEY constraint failed
```

The objective is I need to analyze these logs (mainly the erros) inside my code, and take the proper action based on the error I got.

**Comment by tulir** [comment]
Just set a custom logger instead of the default stdout one

**Comment by hajsf** [comment]
> set a custom logge

Can you elaborate more, some code snippest if possible
