### ISSUE TITLE
How to get a user's pushname？

### ISSUE THREAD

**Issue by pfthink** [tulir/whatsmeow#202]
hi guys，How to get a user's pushname？ HistorySync_PUSH_NAME Only a few are incomplete？ How to query？

**Comment by tulir** [comment]
You only get them from history sync and when receiving a message. There's no way to query push names that you haven't received either via history sync or a new message, but all names you receive are cached and the cache can be queried via `cli.Store.Contacts` (`GetContact(jid)` and `GetAllContacts()`)

**Comment by pfthink** [comment]
Thank for you replay!  is there any api like this ,
![image](https://user-images.githubusercontent.com/31644641/178790706-e31c8cbf-a9c4-47d7-aa4d-422db47aaa46.png)
 or Can you handle it here
![image](https://user-images.githubusercontent.com/31644641/178790818-599b9e7e-dbc4-4325-9ba7-18ca7bf4d168.png)
