### ISSUE TITLE
Download Chat attacment error

### ISSUE THREAD

**Issue by angga30** [tulir/whatsmeow#206]
<img width="1127" alt="Screen Shot 2022-07-18 at 16 04 35" src="https://user-images.githubusercontent.com/33894482/179479134-2054ecd9-31e8-4692-8385-7c560b33c160.png">
<img width="837" alt="Screen Shot 2022-07-18 at 16 05 51" src="https://user-images.githubusercontent.com/33894482/179479220-c7e078ff-3e99-4524-b78a-f5f628f0d6eb.png">
 this is my code

**Comment by angga30** [comment]
i have check this is chat with image attachment

**Comment by mamur-rezeki** [comment]
Does it happen everytime or just in a case ?

**Comment by angga30** [comment]
Everytime

Pada tanggal Sen, 18 Jul 2022 18.57, mamur-rezeki ***@***.***>
menulis:

**Comment by tulir** [comment]
That happens if `w.client` is nil
