### ISSUE TITLE
Unable to get module

### ISSUE THREAD

**Issue by carepollo** [tulir/whatsmeow#207]
I literally did nothing but run the command `go get URL of repo` and then follows the next error.

![Screenshot from 2022-07-24 18-01-46](https://user-images.githubusercontent.com/67649525/180669333-bb2ac19a-459b-42a9-be35-b6c5b9fa98be.png)

**Comment by Duckduckgot** [comment]
> Я буквально ничего не делал, кроме как запускал команду, `go get URL of repo`а затем следовала следующая ошибка.
> 
> ![Скриншот от 24.07.2022 18.01.46](https://user-images.githubusercontent.com/67649525/180669333-bb2ac19a-459b-42a9-be35-b6c5b9fa98be.png)

go get -u go.mau.fi/whatsmeow
