### ISSUE TITLE
ContextInfo for ListResponseMessage or Row in Section 

### ISSUE THREAD

**Issue by mamur-rezeki** [tulir/whatsmeow#211]
When we select an option (*Row) on ListMessage, we're sending as "Non-contextual" for Current chat setting that's maybe has set as Disappearing on.

<summary>Show image</summary>
<details>

![Screenshot_20220728-035846_WhatsApp](https://user-images.githubusercontent.com/107448645/181361457-cf3e555a-bfdb-4030-84de-9cf42e4560b3.jpg)

</details>

**Comment by tulir** [comment]
That doesn't sound like a whatsmeow issue. Protocol questions belong in GitHub discussions, but the ContextInfo field is there in ListResponseMessage just like all other messages
