### ISSUE TITLE
[BUG] no signal session established when trying to send critical_unblock_low

### ISSUE THREAD

**Issue by a5r0n** [tulir/whatsmeow#214]
[Client WARN] Failed to send app state key request: failed to encrypt peer message for XXXXXXXXXXX@s.whatsapp.net: can't encrypt message for device: no signal session established

**Comment by Paguiar735** [comment]
We need more actionable information, such as the context of the problem and a minimal working example.

**Comment by a5r0n** [comment]
well, it's been a while, so i don't have any examples or more context...
we can close this for now.
