### ISSUE TITLE
Get Sender Alias Name in Groups

### ISSUE THREAD

**Issue by Progaros** [tulir/whatsmeow#22]
How can I get the Name of a person sending a message in a group chat?
(The one they defined when setting up WhatsApp eg: +012345678 `~UserName`)

**Comment by tulir** [comment]
It's called `PushName`. Available in incoming message info, the contact store and also `*events.PushName` when the contact store is changed.

**Comment by Y6b** [comment]
> It's called `PushName`. Available in incoming message info, the contact store and also `*events.PushName` when the contact store is changed.

Hello
How about `PushName` for persons who are mentioned in a message or the source of a quoted message?
