### ISSUE TITLE
Button message not working

### ISSUE THREAD

**Issue by bhavesh53** [tulir/whatsmeow#222]
Hello, 
         Today button message stopped working . may be Baileys patch work  
https://github.com/adiwajshing/Baileys/commit/9f3b00d58d4f6b1527db42069acafff01123cbf8

can you please implement it . 

/**
 * this is an experimental patch to make buttons work
 * Don't know how it works, but it does for now
 */
```
export const patchMessageForMdIfRequired = (message: proto.IMessage) => {
	const requiresPatch = !!(
		message.buttonsMessage
		// || message.templateMessage
		|| message.listMessage
	)
	if(requiresPatch) {
		message = {
			viewOnceMessage: {
				message: {
					messageContextInfo: generateContextInfo(),
					...message
				}
			}
		}
	}

	return message
}
```

**Comment by tulir** [comment]
You can put whatever you want in the message proto yourself. That looks like it just wraps button/list messages in a `ViewOnceMessage` and adds `MessageContextInfo`

**Comment by Diden05** [comment]
Not Working 

```
		content := &waproto.Message{
			ViewOnceMessage: &waproto.FutureProofMessage{
				Message: &waproto.Message{
					ButtonsMessage: &waproto.ButtonsMessage{
						HeaderType: waproto.ButtonsMessage_TEXT.Enum(),
						ContentText: proto.String(header),
						Buttons: Button,
						FooterText: proto.String(footer),
					},
					MessageContextInfo: &waproto.MessageContextInfo{
						DeviceListMetadataVersion: proto.Int32(2),
						DeviceListMetadata: &waproto.DeviceListMetadata{},
					},
				},
			},
		}

```

and ViewOnceMessageV2 not working :)

**Comment by mamur-rezeki** [comment]
> Not Working
> 
> ```
> 		content := &waproto.Message{
> 			ViewOnceMessage: &waproto.FutureProofMessage{
> 				Message: &waproto.Message{
> 					ButtonsMessage: &waproto.ButtonsMessage{
> 						HeaderType: waproto.ButtonsMessage_TEXT.Enum(),
> 						ContentText: proto.String(header),
> 						Buttons: Button,
> 						FooterText: proto.String(footer),
> 					},
> 					MessageContextInfo: &waproto.MessageContextInfo{
> 						DeviceListMetadataVersion: proto.Int32(2),
> 						DeviceListMetadata: &waproto.DeviceListMetadata{},
> 					},
> 				},
> 			},
> 		}
> ```
> 
> and ViewOnceMessageV2 not working :)
> 
> The button is visible on the web version, but not on the mobile device

Just don't let the Header empty.

**Comment by Diden05** [comment]
> Just don't let the Header empty.

You can hint what should be in the Header?

**Comment by mamur-rezeki** [comment]
> > Just don't let the Header empty.
> 
> You can hint what should be in the Header?

If we set ` HeaderType ` as ` proto.ButtonsMessage_TEXT `, we also need to fill the ` Header ` field as  a ` proto.ButtonsMessage_Text{ ... } `

```go

var msg = &waProto.Message{
  ViewOnceMessage: &waProto.FutureProofMessage{
     Message: &waProto.Message{
       ButtonsMessage: &waProto.ButtonsMessage{
         HeaderType: waProto.ButtonsMessage_TEXT.Enum(),
         Header: &waProto.ButtonsMessage_Text{
           Text: "Title",
         },
         ContentText: proto.String("Content"),
         FooterText:  proto.String("Footer"),
         Buttons: []*waProto.ButtonsMessage_Button{
           {
             ButtonId: proto.String("id1"),
             ButtonText: &waProto.ButtonsMessage_Button_ButtonText{
               DisplayText: proto.String("btn1"),
             },
             Type: waProto.ButtonsMessage_Button_RESPONSE.Enum(),
           },
         },
       },
     },
   },
}

```

**Comment by mamur-rezeki** [comment]
There's examples 
1. Button message with Text header
2. Button without set the Header field 

![Screenshot_20220805-133213_WhatsApp](https://user-images.githubusercontent.com/107448645/183009827-92854f5a-377a-4c70-978b-a57722a71276.jpg)

**Comment by Diden05** [comment]
> There's examples
thanks, so far so good :)

**Comment by bhavesh53** [comment]
working with **Android** but issue in **IPhone** . any one facing same .

**Comment by Valdenirmezadri** [comment]
> > > Just don't let the Header empty.
> > 
> > 
> > You can hint what should be in the Header?
> 
> If we set `HeaderType` as `proto.ButtonsMessage_TEXT`, we also need to fill the `Header` field as a `proto.ButtonsMessage_Text{ ... }`
> 
> ```go
> var msg = &waProto.Message{
>   ViewOnceMessage: &waProto.FutureProofMessage{
>      Message: &waProto.Message{
>        ButtonsMessage: &waProto.ButtonsMessage{
>          HeaderType: waProto.ButtonsMessage_TEXT.Enum(),
>          Header: &waProto.ButtonsMessage_Text{
>            Text: "Title",
>          },
>          ContentText: proto.String("Content"),
>          FooterText:  proto.String("Footer"),
>          Buttons: []*waProto.ButtonsMessage_Button{
>            {
>              ButtonId: proto.String("id1"),
>              ButtonText: &waProto.ButtonsMessage_Button_ButtonText{
>                DisplayText: proto.String("btn1"),
>              },
>              Type: waProto.ButtonsMessage_Button_RESPONSE.Enum(),
>            },
>          },
>        },
>      },
>    },
> }
> ```

for empty header use waProto.ButtonsMessage_EMPTY

**Comment by Valdenirmezadri** [comment]
TemplateMessage not work, receive only web and android, iphone not

![image](https://user-images.githubusercontent.com/4634624/183263296-706ef2f0-c487-409d-9fdb-f3e8e3d5767e.png)


msg := &waProto.FutureProofMessage{
			Message: &waProto.Message{
				TemplateMessage: buttonsMessage,
				MessageContextInfo: &waProto.MessageContextInfo{
					DeviceListMetadataVersion: proto.Int32(2),
					DeviceListMetadata:        nil,
				},
			},
		}

		m = &waProto.Message{ViewOnceMessage: msg}

**Comment by Diden05** [comment]
> TemplateMessage not work, receive only web and android, iphone not

Yes, for some reason it doesn’t work on the iphone, baileys also haven’t found a solution yet

**Comment by mamur-rezeki** [comment]
> > > > Just don't let the Header empty.
> > > 
> > > 
> > > You can hint what should be in the Header?
> > 
> > 
> > If we set `HeaderType` as `proto.ButtonsMessage_TEXT`, we also need to fill the `Header` field as a `proto.ButtonsMessage_Text{ ... }`
> > ```go
> > var msg = &waProto.Message{
> >   ViewOnceMessage: &waProto.FutureProofMessage{
> >      Message: &waProto.Message{
> >        ButtonsMessage: &waProto.ButtonsMessage{
> >          HeaderType: waProto.ButtonsMessage_TEXT.Enum(),
> >          Header: &waProto.ButtonsMessage_Text{
> >            Text: "Title",
> >          },
> >          ContentText: proto.String("Content"),
> >          FooterText:  proto.String("Footer"),
> >          Buttons: []*waProto.ButtonsMessage_Button{
> >            {
> >              ButtonId: proto.String("id1"),
> >              ButtonText: &waProto.ButtonsMessage_Button_ButtonText{
> >                DisplayText: proto.String("btn1"),
> >              },
> >              Type: waProto.ButtonsMessage_Button_RESPONSE.Enum(),
> >            },
> >          },
> >        },
> >      },
> >    },
> > }
> > ```
> 
> for empty header use waProto.ButtonsMessage_EMPTY

Yes we can left the `Header` as Nil 

![Screenshot_20220807-131506_WhatsApp](https://user-images.githubusercontent.com/107448645/183276411-ca7fa749-250b-42c6-ada6-d6f6687f95b7.jpg)

**Comment by andersling** [comment]
> > TemplateMessage not work, receive only web and android, iphone not
> 
> Yes, for some reason it doesn’t work on the iphone, baileys also haven’t found a solution yet

had you   found some solution yet?sir,thanks!

**Comment by ayrokid** [comment]
> > > TemplateMessage not work, receive only web and android, iphone not
> > 
> > 
> > Yes, for some reason it doesn’t work on the iphone, baileys also haven’t found a solution yet
> 
> had you found some solution yet?sir,thanks!

up
