### ISSUE TITLE
AudioMessage does not play on whatsapp web

### ISSUE THREAD

**Issue by adarosci** [tulir/whatsmeow#228]
WhatsApp made some changes in the last few days and they started to give some problems and audio and video happen the same thing, is anyone having these problems?

WhatsWeb
![image](https://user-images.githubusercontent.com/39490460/184364562-ddceb6a5-8dd4-4996-887a-e4f6c111b094.png)

Andriod
![image](https://user-images.githubusercontent.com/39490460/184364780-db86cc6f-b3c8-4ed9-81bb-85e727540098.png)

code
![image](https://user-images.githubusercontent.com/39490460/184364845-b0fcc67d-3596-4e34-a0fb-480d01d9888e.png)

I tested with this audio
https://tuningmania.com.br/autosom/mp3/20%20~%2024%20Hz.MP3

**Comment by tulir** [comment]
This is not related to whatsmeow, use [GitHub discussions](https://github.com/tulir/whatsmeow/discussions/new?category=whatsapp-protocol-q-a) for questions about the WhatsApp protocol and other clients.

**Comment by socialhub-lab** [comment]
Hi,

I have the same problems with audio. Any idea? Was resolved?
