### ISSUE TITLE
Program crash when client logout from linked devices. 

### ISSUE THREAD

**Issue by amirsheikh** [tulir/whatsmeow#23]
This is the error:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x82a465]
go.mau.fi/whatsmeow.(*Client).sendProtocolMessageReceipt(0xc000194000, {0xc00023a080, 0xc000740160}, {0xa159df, 0x8})
        /root/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20211109215855-2e8804d7e690/message.go:370 +0x145
go.mau.fi/whatsmeow.(*Client).handleProtocolMessage(0xe, 0xc0003ac340, 0xc0003ac340)
        /root/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20211109215855-2e8804d7e690/message.go:319 +0x106
created by go.mau.fi/whatsmeow.(*Client).handleDecryptedMessage
        /root/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20211109215855-2e8804d7e690/message.go:343 +0x487
exit status 2

**Comment by moxovil** [comment]
+1 I have the same thing. Arrived is there any solution for this problem?

**Comment by Stasich** [comment]
+1

**Comment by Stasich** [comment]
https://github.com/tulir/whatsmeow/pull/47 It's works for me, thx:)
