### ISSUE TITLE
panic when client logout

### ISSUE THREAD

**Issue by cowabungal** [tulir/whatsmeow#239]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99c10e]

goroutine 22749037 [running]:
[go.mau.fi/whatsmeow.(*Client](http://go.mau.fi/whatsmeow.(*Client)).handleOwnDevicesNotification(0xc012e17000, 0xc08dd8cf88)
 [go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/notification.go:138](http://go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/notification.go:138) +0xce
[go.mau.fi/whatsmeow.(*Client](http://go.mau.fi/whatsmeow.(*Client)).handleAccountSyncNotification(0xc012e17000, 0xc1076f1ef0)
 [go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/notification.go:169](http://go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/notification.go:169) +0xda
created by [go.mau.fi/whatsmeow.(*Client](http://go.mau.fi/whatsmeow.(*Client)).handleNotification
 [go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/notification.go:189](http://go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/notification.go:189) +0x5ef

**Comment by Paguiar735** [comment]
That looks a lot like [1]. Do you have a minimal working example?

[1] https://github.com/tulir/whatsmeow/issues/287#issue-1466410628

**Comment by tulir** [comment]
Moving to #295
