### ISSUE TITLE
Fail decrypt message

### ISSUE THREAD

**Issue by adarosci** [tulir/whatsmeow#242]
Often messages are not being decrypted, they come with the SenderKeyDistributionMessage object populated

![image](https://user-images.githubusercontent.com/39490460/188734397-ff5cb58b-eb6c-4665-838a-4bc9c18e8c0f.png)

![image](https://user-images.githubusercontent.com/39490460/188734973-1c6de50e-1f7e-48a8-b617-f54051fda053.png)

![image](https://user-images.githubusercontent.com/39490460/188734619-b5703425-a1d9-43b9-9963-3b71251f4764.png)

I've been digging through the other tasks here to see if anyone has already reported this issue, but what was said is that I should ignore the message because the SenderKeyDistributionMessage was the key to decrypt the message that would come later, but in this case the message didn't come.

Any idea?
Is there a problem with the prekeys?

**Comment by adarosci** [comment]
@tulir could help me in this case? tks

**Comment by ichabod-mo** [comment]
I have same trouble
How to solve it？
@tulir
