### ISSUE TITLE
Implement file logging in the waLog package

### ISSUE THREAD

**Issue by KarelKubat** [tulir/whatsmeow#244]
Proposed:

- Parallel to  the `Stdout` method, implement `File` that returns a logger to send to a file.
- Proposed arguments:
  - Filename: string
  - Append: bool (when true, the logfile gets appended)
  - Reopen: bool (when true, the file is opened before outputting to it and closed after. That way an external logrotator can ensure that the file doesn't grow too much and that old versions are gzipped or similar).

Let me know if you agree. If yes I'll get to work on a pull request.

Update: FWIW I implemented this in https://github.com/KarelKubat/whatsmeow, if you deem it worthy for a merge, then let me know.

**Comment by Paguiar735** [comment]
To me it sounds like a good idea

**Comment by KarelKubat** [comment]
I just put in https://github.com/tulir/whatsmeow/pull/299/commits, have a look.

**Comment by eferay93** [comment]
Thank you very much Sir

12 Ara 2022 Pzt, saat 16:45 tarihinde Karel Kubat ***@***.***>
şunu yazdı:
