### ISSUE TITLE
pdf title being "null.pdf"

### ISSUE THREAD

**Issue by batara666** [tulir/whatsmeow#246]
```go
&waProto.Message{DocumentMessage: &waProto.DocumentMessage{
    Title:         proto.String(Title), 
    Caption:       proto.String(Caption),
```

but what's shows on the app are "null.pdf"

**Comment by Manjit2003** [comment]
```go
&waProto.Message{DocumentMessage: &waProto.DocumentMessage{
    Title:         proto.String(Title), 
    Caption:       proto.String(Caption),
    FileName: proto.String("classified.pdf")
```

**Comment by tulir** [comment]
Note that document captions aren't supported by the official apps yet (https://wabetainfo.com/whatsapp-beta-for-android-2-22-21-2-whats-new/), and once they are, you'll probably have to wrap the message in a [`DocumentWithCaptionMessage`](https://github.com/tulir/whatsmeow/blob/5c8577b8ac6f718e809e4c06dcc1e9260cc7c73d/binary/proto/def.proto#L900) before sending
