### ISSUE TITLE
What is the usage purpose of GetMessageForRetry?

### ISSUE THREAD

**Issue by 1337-sys** [tulir/whatsmeow#252]
1 - What is the purpose of this exported callback ? For what purposes can we use it? 
2 - Can I get the first message using this callback if the first message is not received? - Related issue (https://github.com/tulir/whatsmeow/issues/251)

**Comment by Manjit2003** [comment]
In case if sending message fails then whatsmeow uses this function to get that message for retry.
You will have to write custom function to store and retrieve the message.

**Comment by tulir** [comment]
Yeah it's when the recipient sends a retry receipt and whatsmeow doesn't have the message in memory anymore (e.g. if you restarted between sending and getting a retry receipt). Sometimes even the retry receipts don't work though, that's #160
