### ISSUE TITLE
How can i support multiple session with a single go server

### ISSUE THREAD

**Issue by RakaiSeto** [tulir/whatsmeow#255]
I want to make an API that runs on a single GO server but can store multiple session

**Comment by hoehermann** [comment]
Then do it. As far as I know, there is no client-side limitation implemented in whatsmeow. I do something similar in my project [purple-whatsmeow](https://github.com/hoehermann/purple-gowhatsapp/blob/whatsmeow/src/go/login.go).

**Comment by aldinokemal** [comment]
With multiple sessions, it's hard to add an event handler. I suggest you create one session and then run a second app on another port
