### ISSUE TITLE
how to mention 

### ISSUE THREAD

**Issue by mentalisit** [tulir/whatsmeow#257]
how to mention in group message via @

**Comment by mamur-rezeki** [comment]
You should add jid into `...ContextInfo.MentionedJID` , tagging text like @name/@number is optional.

**Comment by mentalisit** [comment]
> You should add jid into `...ContextInfo.MentionedJID` , tagging text like @name/@Number is optional.

can i have a sample?

**Comment by mentalisit** [comment]
@mamur-rezeki  can you show an example

**Comment by mamur-rezeki** [comment]
> @mamur-rezeki  can you show an example 

Let's move to #259 .
