### ISSUE TITLE
Disable logs

### ISSUE THREAD

**Issue by Ased2235** [tulir/whatsmeow#26]
Is there anyway to disable debug logs? I can't seems to find it.

**Comment by tulir** [comment]
How do you not find it? :thinking:

Logs have to be explicitly enabled by passing a logger to `NewClient` (and `sqlstore.New`). Passing `nil` as the logger will disable logs entirely (as the [`NewClient` docs](https://godocs.io/go.mau.fi/whatsmeow#NewClient) say). The stdout logger implementation also requires you to explicitly pass the minimum log level when creating the logger.

Directly copied from [the example](https://godocs.io/go.mau.fi/whatsmeow#example-package):

```go
clientLog := waLog.Stdout("Client", "DEBUG", true)
client := whatsmeow.NewClient(deviceStore, clientLog)
```
