### ISSUE TITLE
Need Help of HistorySync json data processing

### ISSUE THREAD

**Issue by itzngga** [tulir/whatsmeow#261]
Hello how do I process such large data in HistorySync,
is it a good idea to inserting it into MongoDB?

or access data with the help of third parties such as

https://github.com/tidwall/gjson

**Comment by Paguiar735** [comment]
> Hello how do I process such large data in HistorySync,
> is it a good idea to inserting it into MongoDB?
> 
> or access data with the help of third parties such as
> 
> https://github.com/tidwall/gjson

If you already have the data you want, that means it's probably already stored in a SQLite database, which is the one suggested in the minimal working example provided in the repo's readme.

In other words, it seems to me that your question revolves around how to go about getting the data from the SQLite database into some other database of your choosing, which I'm afraid is something out of the scope of this repo.
