### ISSUE TITLE
No new message notification on phone if message received in whatsmeow

### ISSUE THREAD

**Issue by Diden05** [tulir/whatsmeow#262]
Hi!
For some reason, the notification of the received message does not appear on the phone if the message is also received in whatsmeow. How can I get notifications for new messages on my phone?

**Comment by Diden05** [comment]
May be related to SendPresence(types.PresenceAvailable)?

**Comment by hoehermann** [comment]
Yes, based on the user feed-back from https://github.com/hoehermann/purple-gowhatsapp/tree/whatsmeow, it seems you need to use `types.PresenceUnavailable` for notifications to appear on other devices.

**Comment by Diden05** [comment]
> Yes, based on the user feed-back from https://github.com/hoehermann/purple-gowhatsapp/tree/whatsmeow, it seems you need to use `types.PresenceUnavailable` for notifications to appear on other devices.

Thanks!

**Comment by salmaricc** [comment]
Hi!

Please can you guide me how I can set types.PresenceUnavailable? And if I do that, will I be able to see other users online status still in Pidgin?

**Comment by wxl2578** [comment]
Do you mean that the main device cannot receive the message, only the clone device that scans the code can receive the message? I need this function

**Comment by hoehermann** [comment]
@wxl2578 Regardless of the presence setting, all devices receive the message.
