### ISSUE TITLE
ERROR: Can't send message to unknown server WA web

### ISSUE THREAD

**Issue by slackale** [tulir/whatsmeow#276]
Hello everyone.

I've been using this code and it's really good, awesome job!

However I have this error everytime it receives a message from someone using whatsapp web:
[Main ERROR] Error sending message: can't send message to unknown server s.whatsapp.net in status

Any help would be apreciated.

Thank you.

**Comment by burstfreeze** [comment]
Log the sender ID you are sending messages to. It sounds like you are sending to bad IDs

**Comment by slackale** [comment]
Hello.

Yes we were able to resolve the issue, sorry I think I rushed here and oppened the issue.

All is good thank you for your time.
