### ISSUE TITLE
How to get list of chats?

### ISSUE THREAD

**Issue by krismandev** [tulir/whatsmeow#277]
![Screenshot_20221119-013907_Parallel Space 64Bit Support](https://user-images.githubusercontent.com/67109340/202779154-1bacdb33-6482-47b2-aa8f-cec66420e442.jpg)

How to get list of history chats like picture above ?

actually what i need is only number (user jid), push name or grup name

**Comment by tulir** [comment]
You get them in the history sync events soon after login. Other than that, there's no list of DMs, but you can get the list of groups with `GetJoinedGroups`.
