### ISSUE TITLE
undefined: store.CompanionProps

### ISSUE THREAD

**Issue by joeengressia** [tulir/whatsmeow#278]
error after update to go.mau.fi/whatsmeow v0.0.0-20221113135643-05e0c80bc669

store.CompanionProps.Os = goProto.String("foo")

**Comment by aldinokemal** [comment]
you can change to

```
store.DeviceProps.PlatformType = &config.AppPlatform
store.DeviceProps.Os = &osName
```


[here is the example](https://github.com/aldinokemal/go-whatsapp-web-multidevice/blob/main/src/utils/whatsapp.go#L108-L109)

**Comment by joeengressia** [comment]
thx @aldinokemal , it works
