### ISSUE TITLE
Logout after scan QRcode

### ISSUE THREAD

**Issue by fcerd95** [tulir/whatsmeow#28]
When I read the QR Code, it appears in the logs that authentication was performed successfully, so I get some acks and logout. On the cell phone the text "logging in.." appears and after a few seconds a message appears from whatsapp saying to try again.

Any ideia? 

```
15:51:20.893 [Database INFO] Successfully authenticated
....
15:52:04.888 [Database DEBUG] Received devices update
15:52:10.613 [Database/Send DEBUG] <iq id="240.105-6" to="s.whatsapp.net" type="get" xmlns="w:p"><ping/></iq>
15:52:10.742 [Database/Recv DEBUG] <iq from="s.whatsapp.net" id="240.105-6" t="1639065130" type="result"/>
15:52:21.949 [Database/Recv DEBUG] <stream:error code="401"><conflict type="device_removed"/></stream:error>
15:52:21.949 [Database/Recv DEBUG] <xmlstreamend/>
15:52:21.949 [Database WARN] Received stream end frame
15:52:21.949 [Database INFO] Got device removed stream error, sending LoggedOut event and deleting session
15:52:22.055 [Database/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF
15:52:22.055 [Database/Socket DEBUG] Frame websocket read pump exiting 0xc001047ce0
15:52:22.055 [Database DEBUG] OnDisconnect() called, but it was expected, so not emitting event

```

**Comment by batara666** [comment]
Have you try again with latest whatsmeow version?

**Comment by Paguiar735** [comment]
Gelpiu-developers' advice [1] applies for whatsmeow as well:

> Hi guys! Here's what works for me. Instead of scanning [th]e QR code right away, I have to open the WhatsApp App in a real or virtual device and wait until all messages are synced in that device. Once it has received all messages, then I scan the QR code again, and it works. Hope it helps.

WhatsApp itself says why that's so:

> We logged you out of your linked devices due to an unexpected issue with syncing data from your phone. Protecting the privacy of your messages is important to us. When we can’t verify your data is syncing properly between devices, we automatically log you out as an extra precaution.

[1] https://github.com/adiwajshing/Baileys/issues/1206#issuecomment-1224069759
[2] https://faq.whatsapp.com/819116645902042
