### ISSUE TITLE
How to reply message?

### ISSUE THREAD

**Issue by krismandev** [tulir/whatsmeow#280]
i read the issue created by [alexandrepossebom](https://github.com/alexandrepossebom) in closed issue #29  

https://github.com/tulir/whatsmeow/issues/29#issue-1083963911 

```
msg := &waProto.Message{
		ExtendedTextMessage: &waProto.ExtendedTextMessage{
			Text: &reply,
			ContextInfo: &waProto.ContextInfo{
				StanzaId:      &evt.Info.ID,
				QuotedMessage: message.Message,
			},
		},
	}
	cli.SendMessage(message.Info.Chat, "", msg)
```

but i still confused about message.Message object (QuotedMessage parameter). is it can be obtained only from *events.Message ?

i still confused how to handle that.

**Comment by tulir** [comment]
You can get or make it any way you want. GitHub issues are only for whatsmeow issues, not for whatsapp protocol questions
