### ISSUE TITLE
right way to get conversation ?

### ISSUE THREAD

**Issue by krismandev** [tulir/whatsmeow#281]
what is the right way to get conversation text?

currently i am using evt.Message.GetConversation() but sometimes it returns empty string. (usually occurs in messages received in a group)

```
func handleReceivedMessage(session_name string, msg *events.Message, eventName string) {
	sendData := make(map[string]interface{})

	log.Infof("Received message : %+v", msg)

	sendData["HasMedia"] = false
	sendData["Body"] = msg.Message.GetConversation()
	sendData["Timestamp"] = msg.Info.Timestamp.Unix()
	
	sendData["FromMe"] = msg.Info.MessageSource.IsFromMe
	sendData["Author"] = msg.Info.PushName

	log.Infof("Send Data", sendData)
}
```

**Comment by tulir** [comment]
Protocol questions should be asked in GitHub discussions or in the Matrix room. Also, it should show all the fields that are present in the message when you print it. The answer is that text messages sometimes use `ExtendedTextMessage`
