### ISSUE TITLE
what does events.ReceiptType   "sender" means?

### ISSUE THREAD

**Issue by qingcelei** [tulir/whatsmeow#284]
I handle *events.Receipt ,  one field is ReceiptType  , the value is "sender", what does "sender" means? I did not find any message about "sender"? can you write a detail demo or document for user?
![image](https://user-images.githubusercontent.com/119028382/203903931-c44a4500-d159-4e26-98a5-450f2360033b.png)

**Comment by tulir** [comment]
A constant for `sender` receipts was already added a month ago
