### ISSUE TITLE
reply failed

### ISSUE THREAD

**Issue by TAMILVIP007** [tulir/whatsmeow#285]
hey there 

```
func SendResponse(event *events.Message) {
	if event.Info.IsFromMe {
		return
	}
	resp := *event.Message.ExtendedTextMessage.ContextInfo.QuotedMessage.Conversation
	if resp == "" {
		return
	}
	_, _ = client.SendMessage(ctx.Background(), event.Info.Chat, whatsmeow.GenerateMessageID(), &wap.Message{
		ExtendedTextMessage: &wap.ExtendedTextMessage{
			Text: proto.String("resp"),
			ContextInfo: &wap.ContextInfo{
				StanzaId:      &event.Info.ID,
			
![photo_2022-11-24_03-00-32](https://user-images.githubusercontent.com/79161058/204133681-ad432996-d970-4b0c-9a4d-0c85ae4fe77e.jpg)
	Participant:   proto.String(event.Info.Sender.String()),
				QuotedMessage: &wap.Message{Conversation: proto.String(resp)},
			},

		},
	})
}
```
this is my code i am trying to reply an exiting messsage not a new message. but when i try to reply to old message by passing that text in quoted parameter it doesnt actually bein a reply to that older message anyone knows how to fix this?

![photo_2022-11-24_03-00-32](https://user-images.githubusercontent.com/79161058/204133727-2740c501-06b7-45f0-9247-ad16347ec3b0.jpg)

**Comment by Paguiar735** [comment]
I'm pretty sure the attribute `QuotedMessage` expects you the message id, which might not be what you're passing to it.

**Comment by TAMILVIP007** [comment]
> I'm pretty sure the attribute `QuotedMessage` expects you the message id, which might not be what you're passing to it.

yeh thanks found the reason

**Comment by Paguiar735** [comment]
> > I'm pretty sure the attribute `QuotedMessage` expects you the message id, which might not be what you're passing to it.
> 
> yeh thanks found the reason

Do you mind sharing the reason with us?

**Comment by TAMILVIP007** [comment]
> > > I'm pretty sure the attribute `QuotedMessage` expects you the message id, which might not be what you're passing to it.
> > 
> > 
> > yeh thanks found the reason
> 
> Do you mind sharing the reason with us?

stanzaid and participant id should be not from current event. I fixed it by storing new messages in db with their stanza id and participant id and refetched from db to reply to older messages
