### ISSUE TITLE
Decrypt poll hashes

### ISSUE THREAD

**Issue by Ased2235** [tulir/whatsmeow#286]
Is there anyway to Decrypt poll hashes? 
```
pollVote, err := cli.DecryptPollVote(evt)
		if err != nil {
			log.Println(":(", err)
			return
		}
		log.Println("Selected hashes:")
		for _, hash := range pollVote.GetSelectedOptions() {
			Log.Warnf("- %X\n", hash) // <-- this part
		}
```

**Comment by tulir** [comment]
No, you'll just have to store the options when you receive the poll create message. The votes contain SHA-256 hashes of the options (also see the `HashPollOptions` function)
