### ISSUE TITLE
panic when the client logout and store historical message secrets

### ISSUE THREAD

**Issue by kaefpiton** [tulir/whatsmeow#287]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xabea38]

goroutine 166760168 [running]:
[go.mau.fi/whatsmeow.(*Client](http://go.mau.fi/whatsmeow.(*Client)).storeHistoricalMessageSecrets(0xc05725d7d0?, {0xc072b26600?, 0xc04ee7e000?, 0xc0d2a25440?})
[go.mau.fi/whatsmeow@v0.0.0-20221117205735-357841c4ff30/message.go:409](http://go.mau.fi/whatsmeow@v0.0.0-20221117205735-357841c4ff30/message.go:409) +0x38
created by [go.mau.fi/whatsmeow.(*Client](http://go.mau.fi/whatsmeow.(*Client)).handleHistorySyncNotification
[go.mau.fi/whatsmeow@v0.0.0-20221117205735-357841c4ff30/message.go:316](http://go.mau.fi/whatsmeow@v0.0.0-20221117205735-357841c4ff30/message.go:316) +0x598

**Comment by Paguiar735** [comment]
We'll need a minimal working example to look into this.

**Comment by Paguiar735** [comment]
We need a minimal working example to be able to look into this.

**Comment by tulir** [comment]
Moving to #295
