### ISSUE TITLE
how to change device icon and name show in whatsapp  mobile

### ISSUE THREAD

**Issue by qingcelei** [tulir/whatsmeow#289]
I use this project and success login in whatsapp,  but in mobile app, the device name is whatsmeow  ,how to change the device name and icon
![lALPF7skLXHCgHnNBCrNAsI_706_1066](https://user-images.githubusercontent.com/119028382/204786551-be0a0710-e3ec-47eb-9551-68ebe25fe396.png)

**Comment by tulir** [comment]
You can change the values in `store.DeviceProps` (e.g. `store.DeviceProps.Os = proto.String("text")`, or use `store.SetOSInfo()`)

**Comment by tasovayasin** [comment]
> You can change the values in `store.DeviceProps` (e.g. `store.DeviceProps.Os = proto.String("text")`, or use `store.SetOSInfo()`)

how can change icon ?
