### ISSUE TITLE
How to get Conversations when I login in

### ISSUE THREAD

**Issue by qingcelei** [tulir/whatsmeow#291]
When I login in whatsapp ，Now I use events.HistorySync to get the Conversations , Is this right?  I see six  HistorySyncType , what does every one means?
![image](https://user-images.githubusercontent.com/119028382/205441895-6b8fc579-71cd-45f1-8527-facfa50ab6ed.png)
![image](https://user-images.githubusercontent.com/119028382/205441983-996aaae5-70a8-4213-a372-a3410593e4d1.png)

**Comment by Paguiar735** [comment]
I'm afraid that without having you explain what you mean by "conversations" exactly, and tell us what files you got those pictures from, it's a dead end.

**Comment by Paguiar735** [comment]
Unfortunately I'm not sure about the peculiarities of those arguments either.

However, [whatsmeow/binary/proto/doc.go](https://github.com/tulir/whatsmeow/blob/main/binary/proto/doc.go) claims:

> // Package proto contains the compiled protobuf structs from WhatsApp's protobuf schema.

Which can be corroborated at [whatsmeow/binary/proto/extract](https://github.com/tulir/whatsmeow/tree/main/binary/proto/extract).

In other words, that section of the project seems to be building upon the work of another repository: [sigalor/whatsapp-web-reveng](https://github.com/sigalor/whatsapp-web-reveng), which is where I believe you're more likely to find the answers you seek.

**Comment by qingcelei** [comment]
I just want to fetch the dialog list ,  but I do not know how to do
![image](https://user-images.githubusercontent.com/119028382/205589994-9b0e55b6-7bd0-4f71-a9a0-031632aa2b6b.png)

**Comment by tulir** [comment]
You can just look at what each of the types contain yourself, or even just handle any items in `Conversations` regardless of the type
