### ISSUE TITLE
What's the way to get group name from the chat?

### ISSUE THREAD

**Issue by iamatulsingh** [tulir/whatsmeow#294]
I couldn't find a way to find the group name. I'm able to get the unique group id but wants to know the name as well. Can anyone tell me?

**Comment by Paguiar735** [comment]
Try [func (*Client) GetGroupInfo](https://godocs.io/go.mau.fi/whatsmeow#Client.GetGroupInfo). It returns `(*types.GroupInfo, error)`, which [struct](https://github.com/tulir/whatsmeow/blob/main/types/group.go) contains `GroupName`.

**Comment by iamatulsingh** [comment]
Thanks @Paguiar735. It was a dumb question.
