### ISSUE TITLE
failed to send usync query: websocket not connected 

### ISSUE THREAD

**Issue by qingcelei** [tulir/whatsmeow#297]
When I use IsOnWhatsApp to validate a phone number is register on whatsapp , always raise panic failed to send usync query: websocket not connected .
I have login in whatsapp.
this method is in user.go
![image](https://user-images.githubusercontent.com/119028382/205862085-7023763c-4d9d-4a1e-bb55-1bd1de97e637.png)

**Comment by Paguiar735** [comment]
Show us a minimal working example of your code
