### ISSUE TITLE
Failed to save business name of ~@s.whatsapp.net in device store: database is locked

### ISSUE THREAD

**Issue by sakku116** [tulir/whatsmeow#298]
sometime i got client error that says "Failed to save business name of ?@s.whatsapp.net in device store: database is locked"

**Comment by Manjit2003** [comment]
Yes, I also get the same error while using the SQLite DB. Maybe SQLite is unable to keep up with the speed of key updation. I solved this by switching over to Postgres DB.

**Comment by Stein-Hakase** [comment]
Try this params _journal_mode=WAL.
Your  open will look like this `sql.Open("sqlite3", "file:storage/db.sqlite3?_foreign_keys=on&_journal_mode=WAL")`.

**Comment by sakku116** [comment]
thanks, i will try it later

**Comment by Paguiar735** [comment]
As @Manjit2003 suspected, this is a limitation of SQLite 3, unrelated to WhatsMeow.

> **SQLite supports an unlimited number of simultaneous readers, but it will only allow one writer at any instant in time**. For many situations, this is not a problem. Writers queue up. Each application does its database work quickly and moves on, and no lock lasts for more than a few dozen milliseconds. But there are some applications that require more concurrency, and those applications may need to seek a different solution. [[Source](https://www.sqlite.org/whentouse.html)]
