### ISSUE TITLE
Implement writing app state

### ISSUE THREAD

**Issue by 1337-sys** [tulir/whatsmeow#31]
If we write one of these functions, we write the rest. App state write so important.

**Comment by 1337-sys** [comment]
I'm offering you $500.  I really need appstates.

**Comment by iileandro** [comment]
I made it based on [github/dimaskiddo](https://github.com/dimaskiddo/go-whatsapp-rest/). It's not published yet. But if someone interested on it. Please tell me.

**Comment by 1337-sys** [comment]
Ping, ping...

**Comment by 1337-sys** [comment]
I beg you, can we at least do chat pinning? Only Pin, only..

**Comment by 1337-sys** [comment]
https://github.com/tulir/whatsmeow/commit/a168fde5a9dee4d950ca1dd26b5093a80eea2399

Really? 👯‍♀️ I'm so excited..

**Comment by Ased2235** [comment]
@tulir [Baileys](https://github.com/adiwajshing/Baileys/blob/d5b857ad61a68fbc6b03383a908e7c67e4d526db/src/Utils/chat-utils.ts#L118) already implement app state, Do you have any plan to add it?

**Comment by Ased2235** [comment]
I already started working on it myself but there's few things i don't understand. For example how do i get App State Sync Key?

**Comment by ffauzan** [comment]
Any update on this?

**Comment by 1337-sys** [comment]
@tulir Any update? Only pin..

**Comment by salman0ansari** [comment]
> @tulir Any update? Only pin..

what will you do with chat pin?

**Comment by 1337-sys** [comment]
Let's do chat pin in honor of the 1st year @tulir 

At least show me the way. Let's do it ourselves. We need it more than ever. Not just for me. Thousands of developer are waiting for this writing to app state.

Please...

To do what it takes? Time? Money? Let's raise funds your between us.

We love you and we are so grateful @tulir. If you won't tell us, let's not wait or develop programs in this library any more.

Thanks

- One of the dozens of developer who love you

**Comment by Paguiar735** [comment]
> I'm offering you $500. I really need appstates.

@1337-sys If it's a real bounty, I suggest you join the repo's official [Matrix room](https://matrix.to/#/#whatsmeow:maunium.net) and offer it up there.

@Ased2235 I suggest you do the same. The WhatsMeow community's more vocal on the Matrix than on Github.

**Comment by 1337-sys** [comment]
@Paguiar735 Those in this group already know the criticality of the situation. I tried to github sponsor a lot, but Github does not accept any card. I want a swift code from him. This is not a bribe. I give this not in exchange for a feature, but of all sincerity.

![SS](https://i.ibb.co/sFryPTZ/Screenshot-2023-01-29-at-16-33-30.png)

**Comment by 1337-sys** [comment]
I wish I could see such a commit when I wake up morning.


https://github.com/Auties00/WhatsappWeb4j/commit/5a4a8ae389cff88921fd00c3f901eba16c121a1b (App state writes now work!)

**Comment by ahmedRSA** [comment]
dude stop spamming if you really need state that bad why not just use other libs ??

**Comment by burstfreeze** [comment]
You even have the other libs to look at. If Tulir won't do it, you can work on it on your own and do a pull request 😅

**Comment by ahmedRSA** [comment]
petition to ban this guy 
### **[1/n]**
