### ISSUE TITLE
Message does not always arrive on whatsapp web

### ISSUE THREAD

**Issue by elpulga** [tulir/whatsmeow#32]
the message "Waiting for this message. Check your phone. Learn more" sometimes is seen on WhatsApp web cliente, instead of the actual message. Message arrives correctly on phone.
Why does this happen?

**Comment by clmnin** [comment]
I've never experienced this myself. Does this happen for newer messages or during initial sync?

**Comment by osiloke** [comment]
This is an issue with WhatsApp multi device api, I've experienced this using the official WhatsApp app and web.

**Comment by elpulga** [comment]
> This is an issue with WhatsApp multi device api, I've experienced this using the official WhatsApp app and web.

Yes, I think this could have something to do with this "unsupported feature" from whatsapp faq

"Unsupported features:
Messaging or calling someone who is using a very old version of WhatsApp on their phone."

https://faq.whatsapp.com/general/download-and-installation/about-multi-device-beta/?lang=en
