### ISSUE TITLE
Is possible to get or Update labels?

### ISSUE THREAD

**Issue by eodicarvallho** [tulir/whatsmeow#320]
i was trying to set labels for my contacts and saw that we have a method to get labels update event, is possible to set and get too?

**Comment by Paguiar735** [comment]
Can you link something that corroborates the existence of the "get labels update event"? I don't seem to find anything in the official repository or in its respective documentation that mentions "labels".

**Comment by 1337-sys** [comment]
@Paguiar735  Required app state writing https://github.com/tulir/whatsmeow/issues/31
