### ISSUE TITLE
How do I get the sender's number and recipient's number when I get a message from the client?

### ISSUE THREAD

**Issue by oiakhmad** [tulir/whatsmeow#323]
so i want to utilize target sender to save conversation

*events.Message:
........
 if !evt.Info.IsFromMe {
	       // here I want to get sender number, and receiver number
			sender_number, _ := types.ParseJID(evt.Info.SourceString())
			fmt.Println("message", evt.Message.GetConversation())
			fmt.Println("sender", sender_number)
			fmt.Printf("Sender ID: %s\nSent in Chat: %s\n", evt.Info.Sender, evt.Info.Chat)
		}

**Comment by tulir** [comment]
Looks like you already printed all the details?

GitHub issues should only be used for bug reports and feature requests. For help with using the library, the Matrix room is recommended.
