### ISSUE TITLE
how to change avatar in session?

### ISSUE THREAD

**Issue by artem-webdev** [tulir/whatsmeow#325]
how to change avatar in session?

**Comment by Paguiar735** [comment]
I don't know what you mean by "avatar" and "session" in this context, but if you're trying to change the profile picture of the WhatsApp account logged into WhatsMeow, the you can use the [SetGroupPhoto](https://github.com/tulir/whatsmeow/blob/d138a41ca8b86c1dc819db1f19f55ea4dd5f47a4/group.go) method with an empty string for the _jid_. [[Source](https://github.com/tulir/whatsmeow/discussions/248)]

**Comment by artem-webdev** [comment]
thanks you very much !
