### ISSUE TITLE
Support retrieving chat history?

### ISSUE THREAD

**Issue by d99kris** [tulir/whatsmeow#33]
Hi @tulir - your library looks very promising, thanks for building this!

I develop a minimalistic terminal-based chat client ([nchat](https://github.com/d99kris/nchat)) and I'm currently looking to support whatsapp multi-device (I'm using `go-whatsapp` today for "legacy" whatsapp). 

I see that your [feature list](https://github.com/tulir/whatsmeow#features) contains most relevant functionalities already. One thing I did not find in the list, nor in the code, is support for retrieving chat history. Do you have any plans to add that eventually?

**Comment by tulir** [comment]
It's supported, history comes in `HistorySync` events soon after login

**Comment by d99kris** [comment]
Oh I missed this, thanks for pointing out! 👍

**Comment by softnrajkumar1994** [comment]
@tulir Full history is not coming in HistorySync for a chat. Can i get full history

**Comment by hoehermann** [comment]
@softnrajkumar1994 No, this is not possible. I assume it is a WhatsApp restriction. Scrolling back in WhatsApp Web past the history that is supplied by default, it will tell you to "use WhatsApp on your phone".

**Comment by whimdo** [comment]
> Oh I missed this, thanks for pointing out! 👍

How did you accomplish this? When I use BuildHistorySyncRequest and then send the E2E.message by SendMessage, But I still cannot receive *events.HistorySync
