### ISSUE TITLE
Android app keeps crashing after sending a message to 'status@broadcast'

### ISSUE THREAD

**Issue by HoshenKadosh** [tulir/whatsmeow#335]
Hi.
when i try to upload a status by sending a message to  `status@broadcast` the status gets uploaded but the android app keeps crashing when i try to open it.
Until i disconnect the WA web session i cant open the whatsapp app on my phone.

"Whatsapp keeps stopping''.

**Comment by hasanbasri1993** [comment]
disabled by Whatsapp since Multidevice

**Comment by tulir** [comment]
Most likely an issue with what you're sending rather than whatsmeow. The app might require using ExtendedTextMessage and setting the textArgb/backgroundArgb fields. You should inspect a status message sent by the phone to make sure you're sending all the required fields.
