### ISSUE TITLE
panic: failed to upgrade database: unable to open database file: The data present in the reparse point buffer is invalid.

### ISSUE THREAD

**Issue by Backencero** [tulir/whatsmeow#337]
Please help me with this error.

panic: failed to upgrade database: unable to open database file: The data present in the reparse point buffer is invalid.
goroutine 1 [running]:
main.main()

exit status 2

**Comment by tulir** [comment]
That sounds like the database is corrupted, possibly something like the disk or other hardware failing or crashing while it was writing data.
