### ISSUE TITLE
Connect postgresql database

### ISSUE THREAD

**Issue by LucasJosivan** [tulir/whatsmeow#338]
Hello. I am currently storing data according to the application example in the documentation, sqlite3 file. However I would really like to store this data in the database on the server using postgres. How can I do this?

**Comment by tulir** [comment]
Import lib/pq or pgx and pass the appropriate params when creating the sqlstore container (the first two parameters, dialect and address, are passed to `sql.Open()` as-is).

When using lib/pq, you can additionally set `sqlstore.PostgresArrayWrapper = pq.Array` to make some batch queries a bit more efficient.
