### ISSUE TITLE
How to RevokeMessage just for Me, not Everyone ?

### ISSUE THREAD

**Issue by amrilazhar** [tulir/whatsmeow#34]
Hi Guys,  i want to know is there a way to delete/revoke message just for me not everyone ?

`func (cli *Client) RevokeMessage(chat types.JID, id types.MessageID) (time.Time, error)`

i have read the docs, and there is no option to revoke just for me, I want to know is there any workaround for this case.

Thanks,

**Comment by tulir** [comment]
Looks like that requires writing app state, which is not currently supported as per the readme (also #31)

**Comment by anonyindian** [comment]
@tulir is it possible to delete "For Me" now? If yes, then please tell how to
