### ISSUE TITLE
Use whatsmeow Sending a document message is successful, and the other party can receive it on the mobile phone, but cannot download the document file

### ISSUE THREAD

**Issue by gpyun** [tulir/whatsmeow#344]
`Data,ERR :=ioutil.ReadFile("t.txt")
                       if ERR != nil {
				return ERR.Error(), nil
			}
                       Upload, ERR:= WA.WAClient.Upload(context.Background(), Data, whatsmeow.MediaImage)
			if ERR != nil {
				return ERR.Error(), nil
			}
			t := time.Now().Unix()
			Initiator:= waProto.DisappearingMode_CHANGED_IN_CHAT
			msg := &waProto.Message{
				DocumentMessage: &waProto.DocumentMessage{
					Caption:           proto.String(""),
					Url:               proto.String(Upload.URL),
					DirectPath:        proto.String(Upload.DirectPath),
					MediaKey:          Upload.MediaKey,
					Mimetype:          proto.String("text/plain"),
					FileEncSha256:     Upload.FileEncSHA256,
					FileSha256:        Upload.FileSHA256,
					FileLength:        proto.Uint64(Upload.FileLength),
					FileName:          proto.String("t.txt"),
					Title:             proto.String("t.txt"),
					PageCount:         proto.Uint32(0),
					MediaKeyTimestamp: &t,
					ContactVcard:      proto.Bool(false),
					ContextInfo: &waProto.ContextInfo{
						DisappearingMode: &waProto.DisappearingMode{
							Initiator: &Initiator,
						},
					},
				},
				MessageContextInfo: &waProto.MessageContextInfo{
					DeviceListMetadataVersion: proto.Int32(2),
				},
			}
			resp, ERR := WA.WAClient.SendMessage(context.Background(), recipient, msg)
			if ERR != nil {
				return ERR.Error(), nil
			} else {
				return "OK", resp
			}`

Use whatsmeow Sending a document message is successful, and the other party can receive it on the mobile phone, but cannot download the document file

If login to the official website with a browser and send the same document message, the other party can download the file

![photo_2023-02-22_1](https://user-images.githubusercontent.com/18182081/220535563-27d8876d-8f66-44c3-88c5-988be054ae2f.jpg)

**Comment by floodwm** [comment]
You write what, send a document, and upload a image.
Use:
‘uploaded, err := mycli.WAClient.Upload(context.Background(), data, whatsmeow.MediaDocument)’

**Comment by gpyun** [comment]
The other party scans the QR code to log in on the official website, but also cannot download

![photo_a](https://user-images.githubusercontent.com/18182081/220548339-c36b6b3f-cdfd-4acc-8491-929534c44c7e.jpg)

**Comment by gpyun** [comment]
solved

**Comment by gpyun** [comment]
solved
