### ISSUE TITLE
Error send message: server returned error 405

### ISSUE THREAD

**Issue by adarosci** [tulir/whatsmeow#347]
hello, I have a client that when I try to send a message to some specific numbers it is returning this error

the number in question is my own test number, but it doesn't happen to everyone

this test number in another instance (whatsapp) works normally, only in that instance until then it is not working

I already updated the system to the latest version generated

the qrcode link has already been redone too

any idea of the problem?

thank you very much

![image](https://user-images.githubusercontent.com/39490460/221023285-89e4410a-3221-471e-b538-3e40aa2462e3.png)

**Comment by ramacatur** [comment]
i also experienced the same error

**Comment by adarosci** [comment]
@tulir can you help us?

I did rollback to version v0.0.0-20230126153218-e778453e6538 now the message send ok, but does not reach the phone

**Comment by nnarayanmuchhal** [comment]
No update on this?? @tulir
