### ISSUE TITLE
button and list menu not work on whatsapp version 2.23.4.79

### ISSUE THREAD

**Issue by hrizal** [tulir/whatsmeow#350]
I got reports from users who this morning updated WhatsApp to version 2.23.4.79, that the "button" and "menu list" doesn't work

also discussed [here](https://github.com/adiwajshing/Baileys/issues/2631)

**Comment by rafaellfmachado** [comment]
I took 2 cases, an iPhone and another Android, on Whats web the buttons appear, but on the device they do not appear

**Comment by rafaellfmachado** [comment]
Cases are increasing, curiously, most are customers using Xiaomi, and the app is in version 2.23.4.79

**Comment by Valdenirmezadri** [comment]
difference we found when sending the buttons

Official API
`
...
"Message": {
        "messageContextInfo": {
            "deviceListMetadata": {
                "recipientKeyHash": "nopVs9S5HXw9mg==",
                "recipientTimestamp": 1677787721
            },
            "deviceListMetadataVersion": 2
        },
        ...
        "IsViewOnce": false,
        ...
        `

using this lib with:
`
ts := (uint64(time.Now().Unix()))
		msg := &waProto.FutureProofMessage{
			Message: &waProto.Message{
				ButtonsMessage: buttonsMessage,
				MessageContextInfo: &waProto.MessageContextInfo{
					DeviceListMetadataVersion: proto.Int32(2),
					DeviceListMetadata: &waProto.DeviceListMetadata{
						RecipientKeyHash:   []byte("nopVs9S5HXw9mg=="),
						RecipientTimestamp: &ts,
					},
				},
			},
		}

		m = &waProto.Message{ViewOnceMessage: msg}
		`


`"Message": {
        "messageContextInfo": {
            "deviceListMetadataVersion": 2
        },
          ....
        "IsViewOnce": false,`

**Comment by marcelo386** [comment]
Not working Android

**Comment by awangga** [comment]
yup. works only on WhatsApp web. did not appear in android

**Comment by hrizal** [comment]
there is a new message type
`MarketingMessageMsgType`
maybe related to this?

**Comment by Duckduckgot** [comment]
https://github.com/adiwajshing/Baileys/issues/2631

**Comment by makanSukros** [comment]
> recipientKeyHash

The mystery seems to be in the contents of the recipientKeyHash value

**Comment by Romerito007** [comment]
[Fixed most buttons](https://github.com/Auties00/Whatsapp4j/commit/bc07c03adeb4a8683d3d68b9dae3eff8aa5daf77)
