### ISSUE TITLE
Empty Type in Message Info

### ISSUE THREAD

**Issue by dralh** [tulir/whatsmeow#352]
Hi, @tulir 

When I print the raw message the type appears (text, media, etc.), but the type in the message info is empty.

Nice project  by the way!

**Comment by dralh** [comment]
#353

**Comment by tulir** [comment]
Keep in mind that you shouldn't trust the type field for anything (e.g. whatsmeow itself sets it to `text` for all message types). You should always just check the which field is set in the protobuf message.

**Comment by dralh** [comment]
Thanks for the advice!
