### ISSUE TITLE
How to send a disappearing message

### ISSUE THREAD

**Issue by pelya** [tulir/whatsmeow#354]
When sending a message to a group using mdtest, I am getting a warning label inside the chat:

This message will not disappear from the chat. The sender may be on an old version of WhatsApp.

The group is set to delete old messages after some time, but this does not happen to messages sent using mdtest.
Is there some special tag that I need to add to the message so it will be marked as disappearing?

**Comment by tulir** [comment]
Yes, you have to set the `Expiration` field inside `ContextInfo` to the number of seconds the message expires in (which also means you have to use `ExtendedTextMessage` for text messages, can't use `Conversation`).

For groups the expiration timer can be found in the group info. For DMs it's not saved anywhere on the server, so you have to save it when it comes through history sync or in a new timer change message (ProtocolMessage with type EPHEMERAL_SETTING).
