### ISSUE TITLE
Missing submodules documentation

### ISSUE THREAD

**Issue by tamboto2000** [tulir/whatsmeow#357]
There's some missing documentations for some of the submodules. Documentation submodule `types` and `events` is missing.

![image](https://user-images.githubusercontent.com/23492779/225208861-75ae4310-fa59-4134-a167-9341ea73e316.png)
![image](https://user-images.githubusercontent.com/23492779/225208965-265f4be5-347b-4ae2-9777-b7673789346d.png)

I haven't check other submodules, but this is the ones that I notice is missing from documentation

**Comment by tulir** [comment]
Works fine for me

https://pkg.go.dev/go.mau.fi/whatsmeow/types
https://pkg.go.dev/go.mau.fi/whatsmeow/types/events
