### ISSUE TITLE
 Full history is not coming in HistorySync for a chat. Can i get full history ?

### ISSUE THREAD

**Issue by softnrajkumar1994** [tulir/whatsmeow#358]

**Comment by tulir** [comment]
You can set `store.DeviceProps.RequireFullSync = true` to request a year of history, or set high values in `store.DeviceProps.HistorySyncConfig` to ask for more than a year (limit seems to be around 3 years), but ultimately how much history you get is completely up to the whatsapp app on your phone and whatsmeow can't affect it.
