### ISSUE TITLE
List of applications/projects using whatsmeow?

### ISSUE THREAD

**Issue by ssgosh** [tulir/whatsmeow#359]
I stumbled upon this library while looking for a terminal-based client for whatsapp, especially one  using ncurses or similar library.. I have not found one which is recent. Does such an application which uses whatsmeow exist? 

It may be useful for end-users if projects using whatsmeow are listed somewhere in the README.

Thanks,
Sabyasachi Ghosh

**Comment by igun997** [comment]
maukirim.com use this library

**Comment by 1337-sys** [comment]
Please check this discussion https://github.com/tulir/whatsmeow/discussions/145
