### ISSUE TITLE
How to Reply to Message

### ISSUE THREAD

**Issue by Valdenirmezadri** [tulir/whatsmeow#36]
I'm trying to reply to the messages, but I can't create the context correctly, how can I do it?

![image](https://user-images.githubusercontent.com/4634624/148234309-12606d83-d472-4ea7-affa-589ac8fae537.png)

**Comment by Romerito007** [comment]
`msg := waProto.ExtendedTextMessage{`
			`Text: proto.String(caption),`
			`PreviewType: &previewType,`
			`ContextInfo: &waProto.ContextInfo{`
				`StanzaId:      proto.String("3EB0F845C2699D2E18F6"),`
				`Participant:   proto.String(jid.User),`
				`QuotedMessage: &waProto.Message{Conversation: proto.String("Test")},`
			`},`
		`}`

		m := &waProto.Message{ExtendedTextMessage: &msg}`

**Comment by Valdenirmezadri** [comment]
Text work, how send when is an image response

**Comment by Romerito007** [comment]
> Text work, how send when is an image response

Not implemented, I believe it should be simple.

**Comment by tulir** [comment]
There's nothing to implement, all replies work the same way

**Comment by Valdenirmezadri** [comment]
Example sending image with context to reply

 &waProto.Message{ImageMessage: &waProto.ImageMessage{
			Caption:       proto.String(mensagem),
			Url:           proto.String(uploaded.URL),
			DirectPath:    proto.String(uploaded.DirectPath),
			MediaKey:      uploaded.MediaKey,
			Mimetype:      proto.String(http.DetectContentType(file.File)),
			FileEncSha256: uploaded.FileEncSHA256,
			FileSha256:    uploaded.FileSHA256,
			FileLength:    proto.Uint64(uint64(len(file.File))),
			JpegThumbnail: thumb,
			ContextInfo:   context,
		}}

**Comment by azickri** [comment]
> Example sending image with context to reply
> 
> &waProto.Message{ImageMessage: &waProto.ImageMessage{ Caption: proto.String(mensagem), Url: proto.String(uploaded.URL), DirectPath: proto.String(uploaded.DirectPath), MediaKey: uploaded.MediaKey, Mimetype: proto.String(http.DetectContentType(file.File)), FileEncSha256: uploaded.FileEncSHA256, FileSha256: uploaded.FileSHA256, FileLength: proto.Uint64(uint64(len(file.File))), JpegThumbnail: thumb, ContextInfo: context, }}

What inside context?
Just StanzaId or anything else?
