### ISSUE TITLE
Couldn't link device  try again later getting this error with business account

### ISSUE THREAD

**Issue by Sandeep-Narahari** [tulir/whatsmeow#361]
When I am trying to scan the QR code with the business account i am getting this error 
Thank you @tulir 
![WhatsApp Image 2023-03-21 at 11 22 33 AM](https://user-images.githubusercontent.com/46187761/226533105-f0e90fcf-025c-4469-8b2f-e7cecdd2a9dc.jpeg)

**Comment by tulir** [comment]
It happens sometimes, trying again later usually works
