### ISSUE TITLE
Bad URL hash

### ISSUE THREAD

**Issue by williank** [tulir/whatsmeow#365]
Someone having the Bad URL hash error
when trying to download the .enc files?

**Comment by Binzaga** [comment]
I also encountered this kind of .enc type video file, how to decrypt it?

**Comment by williank** [comment]
There is the download method, on whatsmeow. You need to use it and it will return the binary and you do what you need to do...

**Comment by Binzaga** [comment]
Okay, thank you for your reply. I'll look for it.

**Comment by Binzaga** [comment]
I am currently using the following method, but when I encounter a video file that cannot be played after it has been parsed, it is very strange.

func (cli *Client) Download(msg DownloadableMessage) ([]byte, error) {

**Comment by mamur-rezeki** [comment]
Examining each process in detail might help to solve the problem.

For example, checking mimetype and file size before upload and after Cli.Download.
