### ISSUE TITLE
Baileys found fix for button

### ISSUE THREAD

**Issue by ahmedRSA** [tulir/whatsmeow#366]
When this repository add button fix?
Is developer even considering working on this lib
Because since 4 week i dont see any commit
He only update whatsapp web version

Any collaborator wants to work on button,llist fix?

**Comment by ahmedRSA** [comment]
Please say something @tulir we have projects hosted on this package all code will be useless without button, list.

**Comment by Ased2235** [comment]
I tried using [Baileys#2674](https://github.com/adiwajshing/Baileys/pull/2674/files#diff-60bede9b89bfe9062baf0a0fa058126420659c3bbb34351fa6298c1d0c67faa1R507) but it's not working, i don't know what i'm missing 
```go 

func (cli *Client) prepareMessageNode(ctx context.Context, to types.JID, id types.MessageID, message *waProto.Message, participants []types.JID, plaintext, dsmPlaintext []byte, timings *MessageDebugTimings) (*waBinary.Node, []types.JID, error) {
	start := time.Now()
	allDevices, err := cli.GetUserDevicesContext(ctx, participants)
	timings.GetDevices = time.Since(start)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to get device list: %w", err)
	}

	attrs := waBinary.Attrs{
		"id":   id,
		"type": getTypeFromMessage(message),
		"to":   to,
	}
	if editAttr := getEditAttribute(message); editAttr != "" {
		attrs["edit"] = editAttr
	}

	start = time.Now()
	participantNodes, includeIdentity := cli.encryptMessageForDevices(ctx, allDevices, id, plaintext, dsmPlaintext)
	timings.PeerEncrypt = time.Since(start)
	content := []waBinary.Node{{
		Tag:     "participants",
		Content: participantNodes,
	}}
	if includeIdentity {
		content = append(content, cli.makeDeviceIdentityNode())
	}
	var buttonType = getButtonType(message)
	if len(buttonType) > 1 {
		content = append(content, waBinary.Node{
			Tag: "biz",
			Content: []waBinary.Attrs{{
				"tag":   buttonType,
				"attrs": getButtonArgs(message),
			}},
		})
	}

	if attrs["type"] == "poll" {
		pollType := "creation"
		if message.PollUpdateMessage != nil {
			pollType = "vote"
		}
		content = append(content, waBinary.Node{
			Tag: "meta",
			Attrs: waBinary.Attrs{
				"polltype": pollType,
			},
		})
	}
	return &waBinary.Node{
		Tag:     "message",
		Attrs:   attrs,
		Content: content,
	}, allDevices, nil
}
``` 

```go
func getButtonArgs(message *waProto.Message) *waBinary.Attrs {

	if message.GetViewOnceMessage() != nil && message.GetViewOnceMessage().Message != nil {
		return getButtonArgs(message.GetViewOnceMessage().Message)
	}
	if message.GetListMessage() != nil {
		var Type = message.GetListMessage().GetListType()
		return &waBinary.Attrs{
			"v":    "2",
			"type": strings.ToLower(Type.String()),
		}
	}
	return &waBinary.Attrs{}

}

func getButtonType(message *waProto.Message) (btype string) {

	if message.GetViewOnceMessage() != nil && message.GetViewOnceMessage().Message != nil {
		return getButtonType(message.GetViewOnceMessage().Message)
	}
	if message.GetButtonsMessage() != nil {
		return "buttons"
	} else if message.GetButtonsResponseMessage() != nil {
		return "buttons_response"
	} else if message.GetInteractiveResponseMessage() != nil {
		return "interactive_response"
	} else if message.GetListMessage() != nil {
		return "list"
	} else if message.GetListResponseMessage() != nil {
		return "list_response"
	}
	return
}
``` 
I didn't edit ```cli.encryptMessageForDevices``` like he did in [Baileys#2674](https://github.com/adiwajshing/Baileys/pull/2674/files#diff-60bede9b89bfe9062baf0a0fa058126420659c3bbb34351fa6298c1d0c67faa1R454)

**Comment by ahmedRSA** [comment]
maybe tulir can help can you join matrix channel?

**Comment by Ased2235** [comment]
> maybe tulir can help can you join matrix channel?

![image](https://user-images.githubusercontent.com/13244139/229355650-4a46624f-7aea-4895-996c-b7fdf9fb3f94.png)
He said next week

**Comment by ahmedRSA** [comment]
code you pasted what problem in this?
button not sending or some other error?

**Comment by Ased2235** [comment]
> code you pasted what problem in this? button not sending or some other error? @Ased2235

Message not sent without any error

**Comment by ahmedRSA** [comment]
tried new commit still same problem 
message goes from my side but not received to receiver
LIST, BUTTON, TEMPLATE

**Comment by ahmedRSA** [comment]
@Ased2235 you tried mediatypes branch ?

**Comment by ahmedRSA** [comment]
whatsapp version of the receiver `2.23.6.76` (normal)

**Comment by Romerito007** [comment]
> whatsapp version of the receiver `2.23.6.76` (normal)

WhatsApp Business does not send, it only receives.
WhatsApp sends and receives.

**Comment by ahmedRSA** [comment]
> > whatsapp version of the receiver `2.23.6.76` (normal)
> 
> WhatsApp Business does not send, it only receives. WhatsApp sends and receives.

both my whatsapp are noraml whatsapp still not working

**Comment by ahmedRSA** [comment]
i am not using business whatsapp. 
still not working

**Comment by Ased2235** [comment]
> @Ased2235 you tried mediatypes branch ?

No, like i mentioned [here](https://github.com/tulir/whatsmeow/issues/366#issuecomment-1493320475) i didn't try ```encryptMessageForDevices```

**Comment by Ased2235** [comment]
I tried both business & normal, it's not working

**Comment by Romerito007** [comment]
> I tried both business & normal, it's not working

Making these changes worked for me.

![image](https://user-images.githubusercontent.com/13719169/229807546-b9eb3c11-f5b0-4e5d-a202-49ae71b0dcf2.png)

![image](https://user-images.githubusercontent.com/13719169/229807944-05dd5e1a-62a1-49f3-bffa-9274088b542f.png)

**Comment by pasyalab** [comment]
@Romerito007 Could you give us an example of a button message. My old code still doesn't work.
`
var msg = &waProto.Message{
		ViewOnceMessage: &waProto.FutureProofMessage{
			Message: &waProto.Message{
				ButtonsMessage: &waProto.ButtonsMessage{
					HeaderType: waProto.ButtonsMessage_TEXT.Enum(),
					Header: &waProto.ButtonsMessage_Text{
						Text: "Message header", 
					},
					ContentText: proto.String("Message content"),
					FooterText:  proto.String("Footer"),
					Buttons: []*waProto.ButtonsMessage_Button{
						{
							ButtonId: proto.String("id1"),
							ButtonText: &waProto.ButtonsMessage_Button_ButtonText{
								DisplayText: proto.String("Yes"),
							},
							Type:           waProto.ButtonsMessage_Button_RESPONSE.Enum(),
							NativeFlowInfo: &waProto.ButtonsMessage_Button_NativeFlowInfo{},
						},
						{
							ButtonId: proto.String("id2"),
							ButtonText: &waProto.ButtonsMessage_Button_ButtonText{
								DisplayText: proto.String("No"),
							},
							Type:           waProto.ButtonsMessage_Button_RESPONSE.Enum(),
							NativeFlowInfo: &waProto.ButtonsMessage_Button_NativeFlowInfo{},
						}
					},
				},
			},
		},
	}

cli.SendMessage(context.Background(), recipient, msg)
`

**Comment by Romerito007** [comment]
> @Romerito007 Could you give us an example of a button message. My old code still doesn't work.
> 
> ```
> var msg = &waProto.Message{
> 		ViewOnceMessage: &waProto.FutureProofMessage{
> 			Message: &waProto.Message{
> 				ButtonsMessage: &waProto.ButtonsMessage{
> 					HeaderType: waProto.ButtonsMessage_TEXT.Enum(),
> 					Header: &waProto.ButtonsMessage_Text{
> 						Text: "Message header", 
> 					},
> 					ContentText: proto.String("Message content"),
> 					FooterText:  proto.String("Footer"),
> 					Buttons: []*waProto.ButtonsMessage_Button{
> 						{
> 							ButtonId: proto.String("id1"),
> 							ButtonText: &waProto.ButtonsMessage_Button_ButtonText{
> 								DisplayText: proto.String("Yes"),
> 							},
> 							Type:           waProto.ButtonsMessage_Button_RESPONSE.Enum(),
> 							NativeFlowInfo: &waProto.ButtonsMessage_Button_NativeFlowInfo{},
> 						},
> 						{
> 							ButtonId: proto.String("id2"),
> 							ButtonText: &waProto.ButtonsMessage_Button_ButtonText{
> 								DisplayText: proto.String("No"),
> 							},
> 							Type:           waProto.ButtonsMessage_Button_RESPONSE.Enum(),
> 							NativeFlowInfo: &waProto.ButtonsMessage_Button_NativeFlowInfo{},
> 						}
> 					},
> 				},
> 			},
> 		},
> 	}
> 
> cli.SendMessage(context.Background(), recipient, msg)
> ```

Your code looks good to me!
WhatsApp Business does not send button.

![WhatsApp Image 2023-04-04 at 11 35 25](https://user-images.githubusercontent.com/13719169/229827245-268d0e2b-4b81-44e4-a104-fe374f43db72.jpeg)

**Comment by Ased2235** [comment]
Only button works, list & templates aren't working

**Comment by ahmedRSA** [comment]
> Only button works, list & templates aren't working

same

**Comment by Romerito007** [comment]
[Type needs to be in lower case.](https://github.com/tulir/whatsmeow/commit/65649ccb64e561876b733a4e95374b19d085eb0d#diff-be1a26a0a39d1b142416f8bd3bfca3a179a00bed2ac5f85448a4780477ff18fcR554)

![WhatsApp Image 2023-04-06 at 06 24 39](https://user-images.githubusercontent.com/13719169/230334458-a821b925-f82a-47e0-bcd1-c003a97e9946.jpeg)

**Comment by ahmedRSA** [comment]
### Big thanks to tulir

**Comment by ramacatur** [comment]
I try with whatsapp business not work but normal whatsapp it wors. 

anyone experiencing the same thing?

**Comment by Ased2235** [comment]
> [Type needs to be in lower case.](https://github.com/tulir/whatsmeow/commit/65649ccb64e561876b733a4e95374b19d085eb0d#diff-be1a26a0a39d1b142416f8bd3bfca3a179a00bed2ac5f85448a4780477ff18fcR554)
> 
> ![WhatsApp Image 2023-04-06 at 06 24 39](https://user-images.githubusercontent.com/13719169/230334458-a821b925-f82a-47e0-bcd1-c003a97e9946.jpeg)

Still not working

**Comment by ramacatur** [comment]
> > [Type needs to be in lower case.](https://github.com/tulir/whatsmeow/commit/65649ccb64e561876b733a4e95374b19d085eb0d#diff-be1a26a0a39d1b142416f8bd3bfca3a179a00bed2ac5f85448a4780477ff18fcR554)
> > ![WhatsApp Image 2023-04-06 at 06 24 39](https://user-images.githubusercontent.com/13719169/230334458-a821b925-f82a-47e0-bcd1-c003a97e9946.jpeg)
> 
> Still not working
> 
> ```go
> var msg = &waProto.Message{
> 		ViewOnceMessage: &waProto.FutureProofMessage{
> 			Message: &waProto.Message{
> 				ListMessage: &waProto.ListMessage{
> 					Title:       proto.String("title"),
> 					Description: proto.String("Description"),
> 					ButtonText:  proto.String("ButtonText"),
> 					ListType:    waProto.ListMessage_SINGLE_SELECT.Enum(),
> 					Sections: []*waProto.ListMessage_Section{
> 						{
> 							Title: proto.String("title 2"),
> 							Rows: []*waProto.ListMessage_Row{
> 								{
> 									Title:       proto.String("title"),
> 									Description: proto.String("Yes"),
> 									RowId:       proto.String("id1"),
> 								},
> 							},
> 						},
> 					},
> 				},
> 			},
> 		},
> 	}
> 
> 
> 
> 	resp, err := cli.SendMessage(nil, jid, msg)
> 	if err != nil {
> 		Log.Errorf("Error sending message: %v", err)
> 	} else {
> 		Log.Infof("Message sent (server timestamp: %s)", resp.Timestamp)
> 	}
> ```

Whatsapp Business ?

**Comment by Romerito007** [comment]
> > > [Type needs to be in lower case.](https://github.com/tulir/whatsmeow/commit/65649ccb64e561876b733a4e95374b19d085eb0d#diff-be1a26a0a39d1b142416f8bd3bfca3a179a00bed2ac5f85448a4780477ff18fcR554)
> > > ![WhatsApp Image 2023-04-06 at 06 24 39](https://user-images.githubusercontent.com/13719169/230334458-a821b925-f82a-47e0-bcd1-c003a97e9946.jpeg)
> > 
> > 
> > Still not working
> > ```go
> > var msg = &waProto.Message{
> > 		ViewOnceMessage: &waProto.FutureProofMessage{
> > 			Message: &waProto.Message{
> > 				ListMessage: &waProto.ListMessage{
> > 					Title:       proto.String("title"),
> > 					Description: proto.String("Description"),
> > 					ButtonText:  proto.String("ButtonText"),
> > 					ListType:    waProto.ListMessage_SINGLE_SELECT.Enum(),
> > 					Sections: []*waProto.ListMessage_Section{
> > 						{
> > 							Title: proto.String("title 2"),
> > 							Rows: []*waProto.ListMessage_Row{
> > 								{
> > 									Title:       proto.String("title"),
> > 									Description: proto.String("Yes"),
> > 									RowId:       proto.String("id1"),
> > 								},
> > 							},
> > 						},
> > 					},
> > 				},
> > 			},
> > 		},
> > 	}
> > 
> > 
> > 
> > 	resp, err := cli.SendMessage(nil, jid, msg)
> > 	if err != nil {
> > 		Log.Errorf("Error sending message: %v", err)
> > 	} else {
> > 		Log.Infof("Message sent (server timestamp: %s)", resp.Timestamp)
> > 	}
> > ```
> 
> Whatsapp Business ?

No!

**Comment by Ased2235** [comment]
> > > [Type needs to be in lower case.](https://github.com/tulir/whatsmeow/commit/65649ccb64e561876b733a4e95374b19d085eb0d#diff-be1a26a0a39d1b142416f8bd3bfca3a179a00bed2ac5f85448a4780477ff18fcR554)
> > > ![WhatsApp Image 2023-04-06 at 06 24 39](https://user-images.githubusercontent.com/13719169/230334458-a821b925-f82a-47e0-bcd1-c003a97e9946.jpeg)
> > 
> > 
> > Still not working
> > ```go
> > var msg = &waProto.Message{
> > 		ViewOnceMessage: &waProto.FutureProofMessage{
> > 			Message: &waProto.Message{
> > 				ListMessage: &waProto.ListMessage{
> > 					Title:       proto.String("title"),
> > 					Description: proto.String("Description"),
> > 					ButtonText:  proto.String("ButtonText"),
> > 					ListType:    waProto.ListMessage_SINGLE_SELECT.Enum(),
> > 					Sections: []*waProto.ListMessage_Section{
> > 						{
> > 							Title: proto.String("title 2"),
> > 							Rows: []*waProto.ListMessage_Row{
> > 								{
> > 									Title:       proto.String("title"),
> > 									Description: proto.String("Yes"),
> > 									RowId:       proto.String("id1"),
> > 								},
> > 							},
> > 						},
> > 					},
> > 				},
> > 			},
> > 		},
> > 	}
> > 
> > 
> > 
> > 	resp, err := cli.SendMessage(nil, jid, msg)
> > 	if err != nil {
> > 		Log.Errorf("Error sending message: %v", err)
> > 	} else {
> > 		Log.Infof("Message sent (server timestamp: %s)", resp.Timestamp)
> > 	}
> > ```
> 
> Whatsapp Business ?

No, original one.
