### ISSUE TITLE
Os: proto.String("whatsmeow") isn't potential ban flag?

### ISSUE THREAD

**Issue by brunoaduarte** [tulir/whatsmeow#37]
![image](https://user-images.githubusercontent.com/5354345/148304618-ac445684-59a8-4f75-9a00-8436a37f10f8.png)

Isn't that a potential mass ban facilitator for WhatsApp?

https://github.com/tulir/whatsmeow/blob/666a92779bf58d5fe6446135aac4ba9f9829217d/store/clientpayload.go#L64

![image](https://user-images.githubusercontent.com/5354345/148304793-caeac2bb-cad3-429c-8018-40436bb071e6.png)

How can I emulate an official Chrome browser? I tried changing the string, but the Chrome icon won't appear

**Comment by tulir** [comment]
The browser type is stored in `PlatformType`, so you can set it with something like `store.CompanionProps.PlatformType = waProto.CompanionProps_CHROME.Enum()`. The OS field is just the operating system part.
