### ISSUE TITLE
Mdtest - Can't link new devices at this time

### ISSUE THREAD

**Issue by 1337-sys** [tulir/whatsmeow#371]
Hi @tulir,

I can't read it on my personal device but works at business.

![Photo](https://i.ibb.co/yF4BWPF/2023-04-09-12-57-28.jpg)

**Comment by 1337-sys** [comment]
This issue is critical. It doesn't read qr right now, including business accounts.

**Comment by 1337-sys** [comment]
Fixed

**Comment by itzngga** [comment]
hello @1337-sys, how do you fix this issue?

**Comment by miguel-arrf** [comment]
Having the same issue. Any clue about what's happening?
