### ISSUE TITLE
Baileys  Down

### ISSUE THREAD

**Issue by andresayac** [tulir/whatsmeow#375]
Taking into account that https://github.com/adiwajshing/Baileys is no longer accessible, I believe that much can be contributed to this library. Many of us depended on it for our integrations, so if I can be of any help, I'll be here.

**Comment by amiruldev20** [comment]
https://github.com/amiruldev20/Baileys

**Comment by guiireal** [comment]
This is an important issue.

Given the situation and what happened with Baileys, is it still worth investing time to create automations with this Go lib?

I say this because switching technologies takes time.

What is the WhatsMeow maintainers' stance on using unofficial libraries regarding what happened with Baileys?

I say this because if it happened with one, it will probably happen with others...

**Comment by Duckduckgot** [comment]
[GitHub - WhiskeysSockets/Baileys: Lightweight full-featured typescr...](https://github.com/WhiskeysSockets/Baileys)

**Comment by burstfreeze-alt** [comment]
> I say this because if it happened with one, it will probably happen with others...

No. It has been happening every now and then for almost 10 years at this point. Always at random. Don't worry

**Comment by richard892** [comment]
Hello there,

We noticed that the popular "Baileys" GitHub repository has been taken down by its creator. We know that this can be frustrating for those who were using it in their projects.

If you're one of those developers looking for an alternative to Baileys, we'd like to introduce you to our paid service. Our service provides a REST API that can easily be integrated into your project, giving you the functionality you need without having to worry about maintaining the code yourself.

With our service, you can focus on building your application, while we take care of the underlying infrastructure. Our team of experts is available 24/7 to ensure that your projects run smoothly.

We believe that our service can provide you with a reliable and scalable solution for your messaging needs. If you're interested, we'd love to discuss how we can help you get started.
Connect on telegram for Free trial of our Whatsapp Rest API - https://telegram.me/richard_892
Thank you for your time, and we look forward to hearing from you soon.

Best regards,
Richard
