### ISSUE TITLE
download failed with status code 403

### ISSUE THREAD

**Issue by qingcelei** [tulir/whatsmeow#385]
when I use whatsmeow.Client DownloadAny method to download media , it return error , the error  message is download failed with status code 403 . some media can download , some media 403 error , why ?

**Comment by mamur-rezeki** [comment]
Is the main message is still available or has deleted ?

**Comment by qingcelei** [comment]
it is avaliable , i can see the message in my phone

**Comment by tulir** [comment]
Not sure why it happens, but re-requesting probably works like 404 and 410 (`SendMediaRetryReceipt`)
