### ISSUE TITLE
No documentation for getting chat history

### ISSUE THREAD

**Issue by iamatulsingh** [tulir/whatsmeow#386]
can someone please provide a code snippet that can help to read old chat history after login. I know it send event for that but don't know how to use it.

**Comment by hoehermann** [comment]
I do it here: https://github.com/hoehermann/purple-gowhatsapp/commit/2048d46

**Comment by MeinDeutschkurs** [comment]
Is this similar?
https://github.com/tulir/whatsmeow/discussions/391 

As a beginnen I'm a bit lost. Thx.

**Comment by mamur-rezeki** [comment]
Sounds like #33 .

**Comment by MeinDeutschkurs** [comment]
> Sounds like #33 .

Unexpected. Thanks for the link. I try to understand it. Have to fight through manual. As a beginner it‘s challenging. Hope, I get it.
