### ISSUE TITLE
SubscribePresence

### ISSUE THREAD

**Issue by deletexl** [tulir/whatsmeow#39]
Hello, I am using the SubscribePresence function as in the documentation. Before this I create normal jid with phone number 

```
// Already logged in, just connect
err = client.Connect()
if err != nil {
	panic(err)
}
tmpJid := types.NewJID("number", types.DefaultUserServer)
fmt.Println(tmpJid.String()) // look right
err = client.SubscribePresence(tmpJid)
if err != nil {
	fmt.Println(err)
}
```

Event Listener

```
func eventHandler(evt interface{}) {
	switch v := evt.(type) {
	case *events.Presence:
		fmt.Println("[+] Presenceee", v)
	}
}
```

Debug output

`11:26:53.534 [Client/Send DEBUG] <presence to="number@s.whatsapp.net" type="subscribe"/>←[0m`

As a result, I can't get any information, is this function working? Or am I doing something wrong.

**Comment by hoehermann** [comment]
In my project https://github.com/hoehermann/purple-gowhatsapp, I just used your example. Presence updates work for me. That does not help you much, but thanks for the code! :)

**Comment by deletexl** [comment]
Sorry, I don't understand exactly what you want to say. I think you solved this case in a different way. Is it possible to do this with Go?

**Comment by hoehermann** [comment]
Indeed, I am using whatsmeow in the context of a bigger messenger. This is what I do (in that order):

1. I establish a connection and [add the event handler](https://github.com/hoehermann/purple-gowhatsapp/blob/2e2b74f/src/go/login.go#L80).
2. The event handler [reacts](https://github.com/hoehermann/purple-gowhatsapp/blob/2e2b74f/src/go/handler.go#L70) to the Presence event.
3. The presence information is [interpreted](https://github.com/hoehermann/purple-gowhatsapp/blob/2e2b74f/src/go/presence.go#L22).
4. I [subscribe](https://github.com/hoehermann/purple-gowhatsapp/blob/2e2b74f/src/go/presence.go#L36) to be informed about presence updates for each user in list of contacts.
