### ISSUE TITLE
ListMessage & ButtonsMessage is not working on android but working on IOS and web 

### ISSUE THREAD

**Issue by rhmdnrhuda** [tulir/whatsmeow#398]
code: 
`msg := &waProto.Message{
		ViewOnceMessage: &waProto.FutureProofMessage{
			Message: &waProto.Message{
				ListMessage: &waProto.ListMessage{
					Title:       proto.String("ListMessage title"),
					Description: proto.String("ListMessage Description"),
					FooterText:  proto.String("ListMessage footer"),
					ButtonText:  proto.String("ListMessage ButtonText"),
					ListType:    waProto.ListMessage_SINGLE_SELECT.Enum(),
					Sections: []*waProto.Section{
						{
							Title: proto.String("Section1 title"),
							Rows: []*waProto.Row{
								{
									RowId:       proto.String("id1"),
									Title:       proto.String("ListMessage section row title"),
									Description: proto.String("ListMessage section row desc"),
								},
								{
									RowId:       proto.String("id2"),
									Title:       proto.String("title 2"),
									Description: proto.String("desc 2"),
								},
							},
						},
						{
							Title: proto.String("Section2 title"),
							Rows: []*waProto.Row{
								{
									RowId:       proto.String("id1"),
									Title:       proto.String("ListMessage section row title"),
									Description: proto.String("ListMessage section row desc"),
								},
								{
									RowId:       proto.String("id2"),
									Title:       proto.String("title 2"),
									Description: proto.String("desc 2"),
								},
							},
						},
					},
				},
			},
		},
	}`
	
	
on website:
![image](https://github.com/tulir/whatsmeow/assets/33447750/8c8e7292-9441-4648-b745-8544d10d22e0)

on my server web also working fine:
![image](https://github.com/tulir/whatsmeow/assets/33447750/49600c09-ccea-4690-b991-8990c035a807)

i was checked on message `*events.Message` data and there is no values for `RawMessage.MessageContextInfo.DeviceListMetadata,SenderKeyHash` and `RawMessage.MessageContextInfo.DeviceListMetadata.SenderTimestamp` .

**Comment by tulir** [comment]
WhatsApp doesn't allow sending those anymore (https://github.com/WhiskeySockets/Baileys/issues/56)
