### ISSUE TITLE
I am getting this error, project is not working anymore

### ISSUE THREAD

**Issue by mohitmanuja** [tulir/whatsmeow#399]
0|ca       | 11:18:36.058 [Client ERROR] Client outdated (405) connect failure
0|ca       | 11:18:36.155 [Client/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by tulir** [comment]
Works fine for me, you're probably using an outdated version

**Comment by mohitmanuja** [comment]
@tulir What's the latest version?

**Comment by tulir** [comment]
The main branch is the latest version, currently commit 5dd0baf43eda3a4d68d6f30b3f0c773cfc93c46d. I adjusted the client outdated log message to include the current version so it's easier to tell if you updated properly or not.

**Comment by mohitmanuja** [comment]
@tulir Cool, I'm using this project as a library. Have you also released the latest version?

**Comment by tulir** [comment]
There haven't been any releases yet of any version

**Comment by mohitmanuja** [comment]
Okay, so instead of library I should clone this project?

**Comment by tulir** [comment]
No, you can just update the library version, `go get -u go.mau.fi/whatsmeow@latest` in your project will update go.mod

**Comment by mohitmanuja** [comment]
@tulir Thanks for the quick help, I have updated to latest version and it's working fine. Closing this issue.
