### ISSUE TITLE
keepalive timeouts handling

### ISSUE THREAD

**Issue by a5r0n** [tulir/whatsmeow#40]
maybe we should count errors, disconnect the socket, or maybe dispatch them as an event?
At least, to store them to use in `client.IsConnected()`

**Comment by a5r0n** [comment]
@tulir Any thoughts?

**Comment by SchulteMK** [comment]
Any new ideas on this topic?

https://github.com/tulir/whatsmeow/blob/dafd80811aec3f58f9621fa100d3557991e382c6/keepalive.go#L55-L57

Disconnecting the socket could be an option, but it feels a bit drastic. Maybe dispatch the failed keepalive as an event as @a5r0n already suggested? This way the user can decide what to do for himself.
