### ISSUE TITLE
Nil pointer reference (commit 5dd0baf commit 7aedaa1)

### ISSUE THREAD

**Issue by SouzaGustavoGG** [tulir/whatsmeow#400]
I was facing the same issue reported here:
https://github.com/tulir/whatsmeow/issues/399

I upgraded my project to @latest version.

Now I'm getting a Nil pointer reference inside whatsmeow.Client when adding a EventHandler...
Then a tried to downgrade to commit 7aedaa1, but the error continues.

Logs:
```
23:40:34.753 [Database INFO] Upgrading database to v2
23:40:34.754 [Database INFO] Upgrading database to v2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8bfb96]

goroutine 10 [running]:
go.mau.fi/whatsmeow.(*Client).AddEventHandler(0x0, 0xc00034e290)
        /go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230608204524-7aedaa1de108/client.go:475 +0x36
```

**Comment by tulir** [comment]
That error seems to happen if you call `AddEventHandler` on a `Client` that is nil (i.e. the problem is in your code)

**Comment by SouzaGustavoGG** [comment]
Thank you, Tulir. 

Just for context. I was creating my clients concurrently and the database was trying to migrate more than once from version v2 to v4 concurrently too (as you can see in the logs):
`23:40:34.753 [Database INFO] Upgrading database to v2
23:40:34.754 [Database INFO] Upgrading database to v2`
With the migration failing, sqlstore.New returned an error and the client returned Nil:
`failed to upgrade database: database is locked (5) (SQLITE BUSY)`

**Comment by tulir** [comment]
You should use the same sqlstore container for all clients, or use different databases entirely
