### ISSUE TITLE
Decrypt received poll options

### ISSUE THREAD

**Issue by bhavesh53** [tulir/whatsmeow#416]
currently receiving selected poll option to HEX format how to convert it to plain text ??  
```
	if evt.Message.GetPollUpdateMessage() != nil {
			decrypted, err := cli.DecryptPollVote(evt)
			if err != nil {
				log.Errorf("Failed to decrypt vote: %v", err)
			} else {
				log.Infof("Selected options in decrypted vote:")
				for _, option := range decrypted.SelectedOptions {
					log.Infof("- %X", option)
					
				}
			}
		}
```

receiving like this 

```
16:38:37.814 [Main INFO] Selected options in decrypted vote:
16:38:37.814 [Main INFO] - F1320FD7A6E37C6256635E929939FA12C8C598E17EE4CDBA9ACB1220B29396E3

```

**Comment by tulir** [comment]
They're sha256 hashes of the option names and can't be decrypted. You need to remember the original option names.

https://pkg.go.dev/go.mau.fi/whatsmeow#HashPollOptions can be used to get the hashes from names, but you can also just do it yourself
