### ISSUE TITLE
How To A Kick And Invite?

### ISSUE THREAD

**Issue by refaldyrk** [tulir/whatsmeow#418]
How To Listen Invite Kick And Invite, Add Admin Or Delete Admin? And I Request Kick, Invite Etc?

**Comment by tulir** [comment]
[GroupInfo](https://pkg.go.dev/go.mau.fi/whatsmeow/types/events#GroupInfo) events are dispatched for all kinds of group changes, including added/removed members and admin status. Methods for making group info changes can also be found by searching [the docs](https://pkg.go.dev/go.mau.fi/whatsmeow)
