### ISSUE TITLE
Link with phone number

### ISSUE THREAD

**Issue by mrma95** [tulir/whatsmeow#419]
Hey there,
WhatsApp Web has recently added a new option for logging in to the account using the phone number.
I was wondering when will this feature be added to whatsmeow?

**Comment by paulcarroty** [comment]
Yeah, super useful for devices with broken/nonexistent camera.

**Comment by Manjit2003** [comment]
tulir is working on it in the [pair-code branch](https://github.com/tulir/whatsmeow/tree/pair-code)

**Comment by diezeldev** [comment]
I am also interested

this would make things so much easier

**Comment by burstfreeze** [comment]
The https://github.com/tulir/whatsmeow/tree/pair-code branch works perfectly with the latest commit

**Comment by hrizal** [comment]
i am not received any event when phone is connected with pair code.
how is your experience ?

**Comment by masewo** [comment]
Here a notification arrives at the primary device (Android) as soon as the pair code is requested.
