### ISSUE TITLE
pair timeout panic: out of range [:32] with capacity 0

### ISSUE THREAD

**Issue by itzngga** [tulir/whatsmeow#426]
panic: runtime error: slice bounds out of range [:32] with capacity 0

goroutine 107 [running]:
go.mau.fi/whatsmeow.(*Client).handleCodePairNotification(0x14000aa4800, 0x140000fd3e0?)
	/Users/itzngga/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230709134728-5fa63e35d8a4/pair-code.go:147 +0xffc
created by go.mau.fi/whatsmeow.(*Client).handleNotification
	/Users/itzngga/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230709134728-5fa63e35d8a4/notification.go:263 +0x734
exit status 2

code examples:
```go
client.Disconnect()
client.Connect()

// -> example hostnumer you can change it
linkedCode, err := client.PairPhone("6281234567890", false, whatsmeow.PairClientChrome, "Test")
if err != nil {
return "", err
}
```

**Comment by tulir** [comment]
That's expected if you try to use unfinished code
