### ISSUE TITLE
Doesn't catch banned event

### ISSUE THREAD

**Issue by galihsatriawan** [tulir/whatsmeow#434]
Dear Team, 
I has added banned event handler like this
![image](https://github.com/tulir/whatsmeow/assets/25653488/2929e7e2-c98e-409a-98e9-a24a879d6784)

But when device has banned
![image](https://github.com/tulir/whatsmeow/assets/25653488/7d338d09-f96d-4b02-a336-da57d514ca2b)

only catch logout event 🙏 
![image](https://github.com/tulir/whatsmeow/assets/25653488/a50dc85d-edc5-48a0-8c21-e617d03d2c41)

**Comment by mamur-rezeki** [comment]
The most likely reason is that it's not a temporary ban.

**Comment by galihsatriawan** [comment]
But there is a button that we can still request a review to whatsapp for recovering our device @mamur-rezeki. And I assume that it will give temporary banned without expiry time
<img width="756" alt="image" src="https://github.com/tulir/whatsmeow/assets/25653488/8e9a014e-3bdf-4a7f-be74-36b8421ef648">

**Comment by tulir** [comment]
It's not a temporary ban. If it triggers a logout event, it probably means a ban event doesn't exist.
