### ISSUE TITLE
failed to decode app state regular_high patches

### ISSUE THREAD

**Issue by alipbudiman** [tulir/whatsmeow#445]
[Client ERROR] Failed to sync app state after notification: failed to decode app state regular_high patches: failed to verify patch v107: mismatching LTHash

**Comment by alipbudiman** [comment]
> [Client ERROR] Failed to sync app state after notification: failed to decode app state regular_high patches: failed to verify patch v107: mismatching LTHash

Solve by remove

waBinary.IndentXML = true

**Comment by alipbudiman** [comment]
> [Client ERROR] Failed to sync app state after notification: failed to decode app state regular_high patches: failed to verify patch v107: mismatching LTHash

Solve by removing

waBinary.IndentXML = true

**Comment by Ased2235** [comment]
> waBinary.IndentXML = true

Can you tell me which file to edit? i'm also getting this error
