### ISSUE TITLE
How to edit a message using whatsmeow?

### ISSUE THREAD

**Issue by celestix** [tulir/whatsmeow#447]
Hello! I was looking for method to edit an already posted message using this library, but I don't seem to find one. Is there any workaround for it?

**Comment by tulir** [comment]
Did you try searching for "edit" in the docs? https://pkg.go.dev/go.mau.fi/whatsmeow#Client.BuildEdit

**Comment by hbinduni** [comment]
hi, does edit message working? or did i do wrong?. i do this, but it seem not working:
```
msg := cli.BuildEdit(jid, messageID, &waProto.Message{
    Conversation: proto.String("lorem ipsum dolor edited message"),
})

resp, err := cli.SendMessage(context.Background(), jid, msg)
```
