### ISSUE TITLE
Sending Image Message

### ISSUE THREAD

**Issue by shadowbane** [tulir/whatsmeow#45]
Hi, I'm having an issue when sending image message. Can anybody help me?

Here's what i've tried:

```go
	newMessage := &waProto.Message{
		ImageMessage: &waProto.ImageMessage{
			Url:     proto.String("https://someurl.com/image.jpg"),
			Caption: proto.String("Test Kirim image"),
		},
	}

	_, err = client.SendMessage(newJid, newMessageId, newMessage)
	if err != nil {
		panic(err)
	}
```

**Comment by alexandrepossebom** [comment]
You need to Upload the image first.

Take a look in example:

[Mdtest example](https://github.com/tulir/whatsmeow/blob/e64fb976bf152581a4a3219419660500ef5d5747/mdtest/main.go#L352)

**Comment by hoehermann** [comment]
Also, the other fields (Caption, Url, DirectPath, MediaKey, Mimetype, FileEncSha256, FileSha256, FileLength) are not optional.

**Comment by aldinokemal** [comment]
How to show image thumbnails?

**Comment by erzqy** [comment]
> How to show image thumbnails?

add `JpegThumbnail` field on `ImageMessage` which `imageByte` is `[]byte` of our image.

```go

messageImage := &waProto.Message{
	ImageMessage: &waProto.ImageMessage{
...
		JpegThumbnail: imageByte,
...
	},
}

```
