### ISSUE TITLE
I have extracted the storage device local public and private keys. Is it possible to login without a qrcode?

### ISSUE THREAD

**Issue by chenyangbo3** [tulir/whatsmeow#452]
The public key and secret key of the mobile device, and the message public key and secret key are extracted directly. This facilitates the management of multiple devices. Is it possible to login the device without scanning the QR code?
The public key and secret key of the mobile device, and the message public key and secret key are extracted directly. This facilitates the management of multiple devices. Is it possible to login the device without scanning the QR code?

**Comment by tulir** [comment]
You can't log in without having whatsapp on a mobile device

(you can log in without QR code nowadays, by entering a 8 character code on the phone https://faq.whatsapp.com/1324084875126592 - `Client.PairPhone` in whatsmeow)
