### ISSUE TITLE
panic: failed to upgrade database: foreign keys are not enabled

### ISSUE THREAD

**Issue by ahmedRSA** [tulir/whatsmeow#454]
after new commit this error come 
using this db driver modernc.org/sqlite

db url look lie this

_ "modernc.org/sqlite"
sqlURL = "sessions.db?_foreign_keys=on"
dB, err = sqlstore.New("sqlite", sqlURL, nil)

**Comment by tulir** [comment]
The syntax for enabling foreign keys may be different on different sql drivers, looks like it's `?_pragma=foreign_keys(1)` for modernc/sqlite https://pkg.go.dev/modernc.org/sqlite#Driver.Open

**Comment by ahmedRSA** [comment]
> 

same code was working before i updated the whatsmeow package to the latest commit

**Comment by tulir** [comment]
Previous versions didn't check if foreign keys are enabled, but the latest db migration checks it because it makes a change that will break the db if foreign keys are disabled.

**Comment by mwk24** [comment]
should this not also enable foreign keys if they are not enabled?

the url flag does not seem to work for me
