### ISSUE TITLE
Getting blocked when creating group

### ISSUE THREAD

**Issue by elpulga** [tulir/whatsmeow#46]
The moment I create a group, I get blocked  instantly on WhatsApp

This is the code I'm using

```
        participants := []types.JID{}
        for _, p := range strings_participants {
            jid, _ := parseJID(p)
            participants = append(participants, jid)
        }

        info, err := client.CreateGroup("group name", participants)
```
Any Ideas why I could be getting blocked when doing this?

**Comment by gqlxj1987** [comment]
have you get a solution? @elpulga

**Comment by elpulga** [comment]
@gqlxj1987 
It was a code issue on my side. If I recall correctly, there was a problem with the participants of the group. But it was a few months ago, so I don't remember exactly

**Comment by gqlxj1987** [comment]
thanks, I will try to  solove this problem, by fix the participants  of the group
