### ISSUE TITLE
Getting banned after sending five messages

### ISSUE THREAD

**Issue by lorenzopic** [tulir/whatsmeow#465]
Hello there, I am using the library with multiple landline numbers on Whatsapp Business, sending and receiving work as they should until I try to send multiple messages. When I try to send a list of more than five messages the number gets banned after the fifth one and I see a message similar to `this number is being used on another phone`, afterwards it asks me to login again and shows me that I have breached the ToS.
I have a delay of five seconds between each message sent and they are all different from each other, the only thing I modified is the name showed when the program connects to the Whatsapp (the default "Whatsmeow"). 
Any clues on what might be causing those bans?
Thanks in advance

Edit: the numbers I am sending the messages to have never contacted me before and are not in my contacts.

**Comment by ahmedRSA** [comment]
no one is facing ban you must be doing something wrong

**Comment by lorenzopic** [comment]
I am just sending normal text messages with 5 seconds delay between each:
`_, err = client.SendMessage(
		context.Background(),
		types.NewJID(sendMessageReqJson.Target, "s.whatsapp.net"),
		&waProto.Message{
			Conversation: proto.String(sendMessageReqJson.Content),
		},
	)`
