### ISSUE TITLE
Server returned error 400 while sending message to channel

### ISSUE THREAD

**Issue by Ased2235** [tulir/whatsmeow#477]
Anyone know how to send message to newsletter (channel) ? Here's how i'm sending 

```golang
jid, _ := parseJID("xxxxxxx@newsletter")

	msg1 :=
		waProto.Message{

			Conversation: proto.String("data.Text"),
		}

	t, err := cli.SendMessage(nil, jid, &msg1)

	if err != nil {
		Log.Errorf("Error sending message: %v", err)
		return
	}

	Log.Debugf("%v", t)
```

But i'm getting error ```[Main ERROR] Error sending message: server returned error 400```

**Comment by Jigarvarma2005** [comment]
https://github.com/tulir/whatsmeow/blob/306bf6fef4d22464b11b43f4bf3a5f9ffbb3cf33/send.go#L120

Try like this
