### ISSUE TITLE
GetGroupInfo error timeout

### ISSUE THREAD

**Issue by ashuvax** [tulir/whatsmeow#489]
```
group, err := client.GetGroupInfo(v.Info.Sender)

if err != nil {
panic(err)
}
```

[Client ERROR] Event handler panicked while handling a *events.Message: info query timed out
![image](https://github.com/tulir/whatsmeow/assets/78299418/b126cff5-65d8-4896-9a43-511d1e6b828f)

**Comment by tulir** [comment]
Calling GetGroupInfo with a user jid doesn't make any sense

**Comment by ashuvax** [comment]
How can I get the correct user jid when receiving a message from a group?
