### ISSUE TITLE
Large image thumbnail in Channel messages

### ISSUE THREAD

**Issue by rudyzeinoun** [tulir/whatsmeow#494]
I'm trying to send an ExtendedTextMessage to a channel, containing a hyperlink (Text, CanonicalUrl, Title, MatchedText, Description) and a JpegThumbnail. With the latest commit, this now works. However, the message gets sent with a small square thumbnail. If you use WhatsApp on a phone to send a link to a channel, then after sending, the link preview appears in a large format similar to a photo message.

Is it possible to support this or provide documentation for it if already supported?

Thank you.

**Comment by tulir** [comment]
WhatsApp protocol questions belong in GitHub discussions. In general, you should just print an incoming message to find out which fields to use, then send messages with those fields. You can also read the protobuf schema to find potentially relevant fields https://github.com/tulir/whatsmeow/blob/main/binary/proto/def.proto#L300-L305
