### ISSUE TITLE
 [Client DEBUG] Didn't handle WhatsApp node

### ISSUE THREAD

**Issue by victormedranop** [tulir/whatsmeow#5]
Hi, i just update de whatsapp cliente on the phone.
try the mdtest, but can read the qr code.

its said 

10:22:24.036 [Client/Recv DEBUG] <ib from="s.whatsapp.net"><downgrade_webclient/></ib>
10:22:24.036 [Client DEBUG] Didn't handle WhatsApp node
10:22:40.865 [Client/Send DEBUG] <iq id="98.37-1" to="s.whatsapp.net" type="get" xmlns="w:p"><ping/></iq>
10:22:40.918 [Client/Recv DEBUG] <iq from="s.whatsapp.net" id="98.37-1" t="1634826160" type="result"/>

and create a new qrcode, and so on.

Victor

**Comment by tulir** [comment]
That sounds like you don't have multidevice enabled on your phone. This library will only support the multidevice API (since whatsapp seems to already be working on phasing out the legacy API)
