### ISSUE TITLE
IOS dont support foward

### ISSUE THREAD

**Issue by fcerd95** [tulir/whatsmeow#50]
I try to send image and pdf by foward, but IOS users can't open

My protoImage Message structure in addition to the required fields, I send the contextInfo field as follows

```
ContextInfo:   &proto.ContextInfo{
            IsForwarded: protobuf.Bool(forward),   
            ForwardingScore: protobuf.Uint32(score)           
}
```

where forward is true and score equal 1.

This is a message in IOS
![image](https://user-images.githubusercontent.com/86968404/152600250-f7be0e95-a62b-4069-8e74-65ef78c6e480.png)

**Comment by fcerd95** [comment]
In android and whatsapp web work's normally

**Comment by jraylan** [comment]
Same problem but with audio message sent directly. Some audio message doesn't work on iOS. "This audio isn't available enymore". May it be related?

![Uploading Captura de Tela 2022-04-05 às 15.42.53.png…]()

**Comment by tulir** [comment]
whatsmeow doesn't really care what you put in the protobuf, so figuring out that part is mostly up to you. Might be useful to look at an incoming protobuf for a forwarded message from a native app and make sure you have the same fields.

Also make sure sending images without the forward flag is working (the Upload method doc has an example that should work: https://pkg.go.dev/go.mau.fi/whatsmeow#Client.Upload)
