### ISSUE TITLE
client and db errors

### ISSUE THREAD

**Issue by Solutionkw** [tulir/whatsmeow#505]
[Client ERROR] Failed to do initial fetch of app state regular_high: failed to get app state regular_high version: database is locked (5) (SQLITE_BUSY)
[Client ERROR] Failed to do initial fetch of app state regular: failed to get app state regular version: database is locked (5) (SQLITE_BUSY)
[Client ERROR] Failed to sync app state after notification: failed to get app state regular version: database is locked (5) (SQLITE_BUSY)
[Client ERROR] Failed to do initial fetch of app state regular_low: failed to get app state regular_low version: database is locked (5) (SQLITE_BUSY)
[Database ERROR] Failed to save identity of xxxxxxxxxx8:0: database is locked (5) (SQLITE_BUSY)
[Database ERROR] Failed to store session with xxxxxxxxxx8:0: database is locked (5) (SQLITE_BUSY)
[Database ERROR] Failed to remove prekey 46: database is locked (5) (SQLITE_BUSY)
[Database ERROR] Failed to load sender key from xxxxxxxxxx8:0 for xxxxxxxxxxxxxxxx83@g.us: database is locked (5) (SQLITE_BUSY)
[Database ERROR] Failed to store sender key from xxxxxxxxxx8:0: database is locked (5) (SQLITE_BUSY)
 plz anyone help to resolve these errors

**Comment by tulir** [comment]
Did you do something silly like pointing multiple programs at the same database file? Anyway, not a problem in whatsmeow itself. If you want to have lots of sessions, you need to either use postgres or separate sqlite files.
