### ISSUE TITLE
Getting bans

### ISSUE THREAD

**Issue by RafaelKuhn1212** [tulir/whatsmeow#506]
For some reason  i am getting so many bans, i send like 50 messages and get banned

**Comment by tulir** [comment]
Getting banned is expected if you spam

**Comment by adebisi-fa** [comment]
> More than 5 messages per minute are very risky.
Do you mean 5 msgs per **per second**?

**Comment by masewo** [comment]
No, per minute and per sending phone number. Especially if the message body is the same. It depends on a lot of factors (scoring). You have to find them out yourself. According to my experience it's just a rule of thumb.
