### ISSUE TITLE
Messages sent to a community Announcements group can not be reacted to

### ISSUE THREAD

**Issue by Jonny1987** [tulir/whatsmeow#509]
This issue only occurs when using whatsmeow, but not when sending a message in the Whatsapp app directly. This functionality was added to Whatsapp this year and users before this were not able to react to messages in the Announcements group of a community. It seems that whatsmeow is still sending messages the old way instead of the new way (whatever this is) which allows reactions.

**Comment by tulir** [comment]
You probably need to set `MessageSecret` inside `MessageContextInfo` (just generate 32 random bytes for it)
