### ISSUE TITLE
Export all group personal chats

### ISSUE THREAD

**Issue by TouchstoneTheDev** [tulir/whatsmeow#513]
Hey I want to delete all my data from whatsapp.
but i also i want save my data.
My app size have become 12 GB.
it will soon stop working.
The manual process will take too much time as i have multiple chats and grps.
If this feature worked or implemented. I pledge to sponsor or like to give a bounty reward !

**Comment by tulir** [comment]
whatsmeow is a library, you can use it to build stuff, but it won't do anything on its own.

WhatsApp will send some history when you link a device, plus more can be requested 50 messages at a time (see https://pkg.go.dev/go.mau.fi/whatsmeow#Client.BuildHistorySyncRequest). The amount of initial history is either 3 months, 1 year, or a few years, depending on settings set before login (see https://github.com/tulir/whatsmeow/blob/main/mdtest/main.go#L60-L65 for example)

You can use `mdtest -request-full-sync` to request a few years of history, which it'll save to json files automatically on login. The exact amount depends on your phone (mdtest sets the request to 10 years, but in practice, the whatsapp apps won't give that much in the initial sync). mdtest doesn't have the on-demand history sync stuff, so you'll have to build that part yourself.
