### ISSUE TITLE
How do i get all the chats and your last message?

### ISSUE THREAD

**Issue by 3046285135** [tulir/whatsmeow#522]
![78885801-94683700-7a33-11ea-82ad-d10085e9086f](https://github.com/tulir/whatsmeow/assets/147360308/ecb5f122-9180-4bae-9b84-ec8b667a6cc0)

**Comment by tulir** [comment]
You receive history immediately after login as `*events.HistorySync`

**Comment by 3046285135** [comment]
> You receive history immediately after login as `*events.HistorySync`

thank you for replying.  i have 20 accounts to login in with whatsmeow,  how can i  tell which account the HistorySync event belong to ?

**Comment by tulir** [comment]
You can add a struct method as the event handler so you have access to the struct

```go
type MyClient struct {
  WA *whatsmeow.Client
  // ...other struct fields...
}

func (mc *MyClient) HandleEvent(evt any) {
  ...
}

func main() {
  client := &MyClient{WA: whatsmeow.NewClient(...)}
  client.WA.AddEventHandler(client.HandleEvent)
}
```

**Comment by 3046285135** [comment]
i'll try it. thank you very much , god bless you, happy new year
