### ISSUE TITLE
Using Whatsmeow to send message with image thumbnail 

### ISSUE THREAD

**Issue by llai-utexas** [tulir/whatsmeow#533]
I wonder if it's possible to use Whatsmeow to send message that looks like the Click-to-Whatsapp message template, with embedded thumbnail with hyperlink that looks like the following

<img width="987" alt="Screenshot 2024-01-17 at 9 37 12 PM" src="https://github.com/tulir/whatsmeow/assets/149282248/3507736f-55ab-4ed9-a8e5-eeede6f6300b">

**Comment by tulir** [comment]
You can send whatever you want that fits in the `Message` protobuf object. Finding out what to put there is up to you. A good way is receiving a message and printing the content to see which fields should be filled.
