### ISSUE TITLE
panic: failed to open database: sql: unknown driver "sqlite3" (forgotten import?)

### ISSUE THREAD

**Issue by rbadillo** [tulir/whatsmeow#54]
Hi,

When running the example I get the following error:

```
panic: failed to open database: sql: unknown driver "sqlite3" (forgotten import?)
```

Any idea how to fix it?

I'm on a Mac Intel Based
Go 1.17

Thanks in advance.

**Comment by rbadillo** [comment]
That worked, thanks a lot.

**Comment by refaldyrk** [comment]
> _ "github.com/mattn/go-sqlite3"

I try to like this but i got same error
