### ISSUE TITLE
Make "downloadAndDecrypt" method exportable.

### ISSUE THREAD

**Issue by ASmoilr** [tulir/whatsmeow#549]
There is case, when you want to download a media without having the message. For instance, you received the message and you saved the necessary fields, like mediakey, mediatype, etc.  In this case, you need to call "downloadAndDecrypt" function. Unfortunately, this function has been defined as private function and the only function which called it and it's exportable is "Download", which requires "DownloadableMessage". 
Is it possible to make this function public?

**Comment by tulir** [comment]
`DownloadMediaWithPath` is already exported. WhatsApp is deprecating the `url` field, so you should always save and use `directPath`, not full urls.
