### ISSUE TITLE
PSA Error 405 - Please don't spam the issue section, Tulir is aware of the problem.

### ISSUE THREAD

**Issue by burstfreeze** [tulir/whatsmeow#56]
Seems to happen to all repos right now.

Connecting will throw `[Client WARN] Unknown connect failure: <failure location="vll" reason="405"/>`

Let's see where this is going. Please comment if you found something that may help.

**Comment by tulir** [comment]
Everything is working fine

**Comment by hugodeco** [comment]
same problem again

**Comment by vocuzi** [comment]
`06:32:09.519 [Client WARN] Unknown connect failure: <failure location="cln" reason="405"/>`

Getting this in the logs while attempting to make a connection.

**Comment by Ased2235** [comment]
Same issue here 
```
12:52:28.854 [Client WARN] Unknown connect failure: <failure location="atn" reason="405"/>
events :- *events.ConnectFailure -> {
  "Reason": "405",
  "Raw": {
    "Tag": "failure",
    "Attrs": {
      "location": "atn",
      "reason": "405"
    },
    "Content": null
  }
}
12:52:28.955 [Client/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF
```

**Comment by tulir** [comment]
To clarify, that only happens on outdated versions. The latest version works fine

**Comment by Ased2235** [comment]
> > > To clarify, that only happens on outdated versions. The latest version works fine
> > 
> > 
> > Which commit should i marge? i tried ([014990e](https://github.com/tulir/whatsmeow/commit/014990ede5fda2d6c38bf139663961a7e7706821)) but it's not working.
> 
> Please try creating a new session and check if that works.

I did but the error is showing before QR code.

**Comment by Ased2235** [comment]
> Then something else is going on. Post the complete log.

Ye i found out that appstats.go was outdated from my side, thank you & @tulir
