### ISSUE TITLE
Client.Disconnect() does not stop the QR Code creation process

### ISSUE THREAD

**Issue by azickri** [tulir/whatsmeow#563]
I have tried to stop the Generate QR Code Function in various ways

1. Client.Disconnect()
2. Client.Store.Delete() // return error `Error Delete Device device JID must be known before accessing database`
3. Client.RemoveEventHandlers()

How to stop the correct QR code generation process? Is there no way at the moment? @tulir 

Thank You.

**Comment by fanesz** [comment]
Hello @azickri, would you provide how you solve it?, because I experience the same issue

**Comment by azickri** [comment]
Hello @fanesz .
The solution I did was to ignore it. Because I store the whatsmeow Client in a local variable Array.

Like this is the Data
```
type Session struct {
  ID string
  SessionID string
  Client *whatsmeow.Client
}
```

And this is the function to delete our whatsmeow Client.

```
index, session := findSession(id)
  if session != nil && session.ID != "" {
    sessions = append(sessions[:index], sessions[index+1:]...)
    session.Client.Disconnect()

    jid, err := types.ParseJID(sessionId)
    if err == nil {
       deviceStore, err := container.GetDevice(jid)
       if err == nil && deviceStore != nil {
           container.DeleteDevice(deviceStore)
       }
     }
  }
```

More precisely, we also cannot stop the qrcode generation, the qrcode will stop being generated until the last one. We also use cron on our vps to restart every 6 hours where the whatsmeow Client will continue to be updated and the one that was deleted will be lost

**Comment by ecsavigne** [comment]
If you capture the context passed to Client.GetQRChannel, you can wrap it in a goroutine, which will receive the context. Whenever you want to stop the generation of the QR code, you just need to exit the goroutine and cancel the context, and this will stop the QR code generation
