### ISSUE TITLE
invalid prekey in prekey response

### ISSUE THREAD

**Issue by fengshunli** [tulir/whatsmeow#571]
Is there no request to manually upload the prekey?
![image](https://github.com/tulir/whatsmeow/assets/18587688/999959fc-49b2-4dd3-85cf-d04e247af806)

example
xmlns="encrypt" type="set" to="s.whatsapp.net">

**Comment by NoamHarel1** [comment]
Same here ✌️

**Comment by Valdenirmezadri** [comment]
Same here ✌️
