### ISSUE TITLE
show Typing while doing backend stuff

### ISSUE THREAD

**Issue by GonzalezAtWork** [tulir/whatsmeow#572]
Hello guys,

I did not found any way to send/show a "typing" for the client while doing backend work.

Is there a way?

thanks!

**Comment by JustSoursop** [comment]
You could call `client.SendChatPrecence(chat, state, media)` :

https://github.com/tulir/whatsmeow/blob/350073db195c6b6fae832a5b420b5b67fd39f6be/presence.go#L115-L138

**Comment by GonzalezAtWork** [comment]
Awesome, worked like a charm:

to start typing:
`mycli.WAClient.SendChatPresence(userJid, types.ChatPresenceComposing, "")`

to stop it:
`mycli.WAClient.SendChatPresence(userJid, types.ChatPresencePaused, "")`
