### ISSUE TITLE
WhatsApp Name from Local Contact

### ISSUE THREAD

**Issue by azickri** [tulir/whatsmeow#573]
Is there an option or function to get the WhatsApp contact name instead of the name displayed by the WhatsApp user?

**Comment by JustSoursop** [comment]
The contacts are probably also synced into the database. You can see this in the `whatsmeow_contacts` table.

`ContactInfo.FullName`

ref :
https://github.com/tulir/whatsmeow/blob/350073db195c6b6fae832a5b420b5b67fd39f6be/types/user.go#L37-L47

Here is how to get the contact info :
```go
ci, err := client.Store.Contacts.GetContact(jid)
if err != nil {
    panic(err)
}

fmt.Println(ci.FullName)

```

**Comment by azickri** [comment]
Thanks, i will try it.

**Comment by azickri** [comment]
I experienced another problem, when the contact name was changed on the cellphone it didn't change in the local database. What must be done to get it in sync?

**Comment by azickri** [comment]
@JustSoursop any advice on this?

**Comment by azickri** [comment]
@JustSoursop When I delete the .db file and try to reconnect, there are some contact names that go back to the beginning (before they were changed) is there a proper handling for this?

**Comment by JustSoursop** [comment]
The contacts are auto-synced by default, including the update.
