### ISSUE TITLE
Possible search user by number?

### ISSUE THREAD

**Issue by refaldyrk** [tulir/whatsmeow#574]
Umm i mean, i want get detail user whatsapp from number, like photo, name, bio, etc?

**Comment by JustSoursop** [comment]
There is a `GetUserInfo()` func to get basic info about the user 

ref :
https://github.com/tulir/whatsmeow/blob/350073db195c6b6fae832a5b420b5b67fd39f6be/user.go#L195-L229

and `GetProfilePictureInfo()` separately 

ref : 
https://github.com/tulir/whatsmeow/blob/350073db195c6b6fae832a5b420b5b67fd39f6be/user.go#L381-L649

You probably need to check whether the phone  `IsOnWhatsApp()`.

https://github.com/tulir/whatsmeow/blob/350073db195c6b6fae832a5b420b5b67fd39f6be/user.go#L162

**Comment by refaldyrk** [comment]
is there anything i do using jid? or phone number?
