### ISSUE TITLE
Get Pushname

### ISSUE THREAD

**Issue by refaldyrk** [tulir/whatsmeow#576]
how can i get push name without send message or receive message?

**Comment by JustSoursop** [comment]
PushName automatically updated via `*events.<...>` that received in `whatsmeow` client. You can get it in contacts info. `Client.Store.Contacts.GetContact(jid)`.

> 

https://github.com/tulir/whatsmeow/issues/202#issuecomment-1183411947

**Comment by refaldyrk** [comment]
So I want to input a number or JID, without having to communicate with him, so it's like a random person, and then I want to see his push name., how?

**Comment by JustSoursop** [comment]
Currently there is no way to get a pushname directly without ever communicating.

The PushName is sent within the first message is sent, and the next name update will be received in the form of a PushName change event (`*events.<...>`) broadcast by the user account.

**Comment by refaldyrk** [comment]
Thanks
