### ISSUE TITLE
How to detect message sent from another device but same account as whatsmeow

### ISSUE THREAD

**Issue by SyngletOxygen** [tulir/whatsmeow#580]
The idea i have is to make the Whatsmeow read previous messages(to fill a form) only if from another device(same account as whatsmeow) sent a message.
But i dont know if detecting when another device has sent messages is possible.

**Comment by JustSoursop** [comment]
You can check the `Device` ID in incoming message event,  `events.Message.Info.Sender.Device`. The JID would be seen like this `1234567890:<ID>@whatsapp.net`.

"The `Device` ID always increases whenever we pair a new device. If the `Device` is `0`, it means it is sent from the mobile app where our phone number was originally registered."

Ref : 
https://github.com/tulir/whatsmeow/blob/01b0547014dc47a63ddce5c1287f64c7d1dc26a4/types/jid.go#L54-L62
