### ISSUE TITLE
How to reply a group message

### ISSUE THREAD

**Issue by GonzalezAtWork** [tulir/whatsmeow#585]
Hello guys!

I am a bit lost and did not found a reply on google or here on how can I reply a Group Message?

I can still use SendMessage, creating a JID from the group, instead of a specifc user? 

some directions, please?

thanks!

**Comment by JustSoursop** [comment]
You can send a message ([SendMessage](https://github.com/tulir/whatsmeow/blob/01b0547014dc47a63ddce5c1287f64c7d1dc26a4/send.go#L166)) into where the chat (jid) coming from. 
Chat `evt.Info.Chat`, the Sender `evt.Info.Sender`.

https://github.com/tulir/whatsmeow/blob/01b0547014dc47a63ddce5c1287f64c7d1dc26a4/types/message.go#L14-L20

**Comment by GonzalezAtWork** [comment]
None of those did not worked:

`chatJid = types.NewJID(v.Info.Chat, types.DefaultUserServer)`

`chatJid = types.NewJID(v.Info.Chat.User, types.DefaultUserServer)`

`chatJid = types.NewJID(v.Info.Chat.Server, types.DefaultUserServer)`


This do not give an error, but also did not send any response to the chat:

`chatJid = types.NewJID(v.Info.Chat.User +"@" + v.Info.Chat.Server, types.DefaultUserServer)`

(ends up with ID@g.us@s.whatsapp.net)

`mycli.WAClient.SendMessage(context.Background(), chatJid, response)`

**Comment by tulir** [comment]
You're way overthinking things

`chatJid = v.Info.Chat`

**Comment by JustSoursop** [comment]
Maybe need new IDE for editing the code that support LSP.

**Comment by GonzalezAtWork** [comment]
ops, my bad:

`chatJid = types.NewJID(v.Info.Chat.User, v.Info.Chat.Server)`
 this works

but nice to know that there is a simplier solution like you said! Thanks!

**Comment by JustSoursop** [comment]
> ops, my bad:
> 
> `chatJid = types.NewJID(v.Info.Chat.User, v.Info.Chat.Server)` this works
> 
> but nice to know that there is a simplier solution like you said! Thanks!

Actually, `v.Info.Chat` is already `types.JID` and doesn't need to be re-created it.
