### ISSUE TITLE
Text message sometimes empty string

### ISSUE THREAD

**Issue by ekasetiawans** [tulir/whatsmeow#588]
I’m facing issue that sometimes received message receiving a empty string. It’s only occured on some whatsapp account. Is there any explanation why this happen?

**Comment by JustSoursop** [comment]
It's kinda hard to figure it out since you didn't provide more information about your case.

**Comment by ekasetiawans** [comment]
I just using simpel example whatsmeow in godoc, the conversation message has empty string

**Comment by JustSoursop** [comment]
IINW, there's 2 type of text message in WhatsApp proto,
`Conversation` & `ExtendedTextMessage`

`Conversation` commonly used in regular chat message that doesn't use Disappearing timer and 
then `ExtendedTextMessage` is a rich text message that can contain`Text`, Link preview, Ads, and other properties like quoting, forwarding, `Expiration` (for disappearing timer) .

reff :
https://pkg.go.dev/go.mau.fi/whatsmeow@v0.0.0-20240507080416-01b0547014dc/binary/proto#Message

**Comment by ekasetiawans** [comment]
So we need to check which the correct message type right?

**Comment by lucasvmx** [comment]
> So we need to check which the correct message type right?

Right.

**Comment by h4775346** [comment]
> > So we need to check which the correct message type right?
> 
> Right.
> 
> You can use this function to check:
> 
> ```go
> func hasTextMessage(msg *proto.Message) bool {
> 	extendedMsg := msg.GetExtendedTextMessage()
> 
> 	return len(msg.GetConversation()) > 0 ||
> 		len(extendedMsg.GetContextInfo().GetQuotedMessage().GetConversation()) > 0 ||
> 		len(extendedMsg.GetText()) > 0
> }
> ```

Your Answer Worked For me after changing some code could be perfect

```
func GetMessageFromEvt(msg *waProto.Message) string {
	extendedMsg := msg.GetExtendedTextMessage()

	if len(msg.GetConversation()) > 0 {
		return msg.GetConversation()
	}
	if len(extendedMsg.GetContextInfo().GetQuotedMessage().GetConversation()) > 0 {
		return extendedMsg.GetContextInfo().GetQuotedMessage().GetConversation()
	}

	if len(extendedMsg.GetText()) > 0 {
		return extendedMsg.GetText()
	}
	return ""
}
```

**Comment by stevegore** [comment]
> > > So we need to check which the correct message type right?
> > 
> > 
> > Right.
> > You can use this function to check:
> > ```go
> > func hasTextMessage(msg *proto.Message) bool {
> > 	extendedMsg := msg.GetExtendedTextMessage()
> > 
> > 	return len(msg.GetConversation()) > 0 ||
> > 		len(extendedMsg.GetContextInfo().GetQuotedMessage().GetConversation()) > 0 ||
> > 		len(extendedMsg.GetText()) > 0
> > }
> > ```
> 
> Your Answer Worked For me after changing some code could be perfect
> 
> ```
> func GetMessageFromEvt(msg *waProto.Message) string {
> 	extendedMsg := msg.GetExtendedTextMessage()
> 
> 	if len(msg.GetConversation()) > 0 {
> 		return msg.GetConversation()
> 	}
> 	if len(extendedMsg.GetContextInfo().GetQuotedMessage().GetConversation()) > 0 {
> 		return extendedMsg.GetContextInfo().GetQuotedMessage().GetConversation()
> 	}
> 
> 	if len(extendedMsg.GetText()) > 0 {
> 		return extendedMsg.GetText()
> 	}
> 	return ""
> }
> ```

Chances are you want the reply instead of the quoted message. Proposed alternative:

```golang
func messageContent(msg *waE2E.Message) string {
	if msg == nil {
		return ""
	}

	if conversation := msg.GetConversation(); len(conversation) > 0 {
		return conversation
	}

	if extendedMsg := msg.GetExtendedTextMessage().GetText(); len(extendedMsg) > 0 {
		return extendedMsg
	}

	if editedContent := messageContent(msg.GetProtocolMessage().GetEditedMessage()); len(editedContent) > 0 {
		return editedContent
	}

	return ""
}
```
