### ISSUE TITLE
Connected, but registering device +... ⏳ Waiting for code...XXXX-XXXX

### ISSUE THREAD

**Issue by alanmugiwara** [tulir/whatsmeow#589]
I've been getting this message, API never send the code. I remove 2FA but nothing changes.

Initializing...
Cleaning cache...
Cache cleaned!
"⏳ Connected, but registering device +5571993277032...
⏳ Waiting for code...0000-0000
❌ Disconnected from WhatsApp Servers!
"⏳ Connected, but registering device +0000...
⏳ Waiting for code...0000-0000

**Comment by tulir** [comment]
whatsmeow doesn't print any messages like that

**Comment by alanmugiwara** [comment]
This is part of a code the uses whatsmeow to link a bot write in Go to whatsapp. Seems like an API connection problem. I changed token method for a Qr-code method and works fine.

**Comment by JustSoursop** [comment]
Are change the User agent for pairing ?


https://github.com/tulir/whatsmeow/blob/main/mdtest%2Fmain.go#L191
