### ISSUE TITLE
timeout running - Getting Issue While QR Scan Call Open

### ISSUE THREAD

**Issue by keyura2** [tulir/whatsmeow#590]
We are facing issue while calling QR - Getting Timeout for the QR. Please let as know the solution as soon as possible

**Comment by JustSoursop** [comment]
Seems it's related to the #584 .

**Comment by JustSoursop** [comment]
Seems it's related to the #584 .

**Comment by keyura2** [comment]
Thank YOu !! i Got the Solution -- 
thank you @JustSoursop

**Comment by alsak0de** [comment]
Just to be clear.. was the solution using a proxy?

**Comment by alsak0de** [comment]
This is what worked for me: add this version to go.mod

go.mau.fi/whatsmeow v0.0.0-20240520180327-81f8f07f1dfb

**Comment by hamidcu** [comment]
lol
1. Login to your local.
2. if login is success on local setup. copy local db file  ( example : examplestore.db )  file to cloud folder.
3. run
