### ISSUE TITLE
Not working when setting DeviceProps_HistorySyncConfig

### ISSUE THREAD

**Issue by zhiru** [tulir/whatsmeow#594]
Hey!

when we pass:
store.DeviceProps.RequireFullSync = proto.Bool(true)

store.DeviceProps.HistorySyncConfig = &waProto.DeviceProps_HistorySyncConfig{
				FullSyncDaysLimit:   proto.Uint32(3650),
				FullSyncSizeMbLimit: proto.Uint32(102400),
			}

or

store.DeviceProps.RequireFullSync = proto.Bool(false)
store.DeviceProps.HistorySyncConfig = &waProto.DeviceProps_HistorySyncConfig{
				FullSyncDaysLimit: proto.Uint32(HistorySyncValue * 10),
				RecentSyncDaysLimit: proto.Uint32(HistorySyncValue * 10),
				FullSyncSizeMbLimit: proto.Uint32(102400),
			}

it continues to bring full fullsync and not just messages from the last 5 days.

Any help @tulir ?

Mention:
@hugodeco

**Comment by tulir** [comment]
The parameters are just passed to the mobile client, it's up to whatsapp what they want to return. I'd guess the full sync params are not applied at all when request full sync is false, and non-full syncs are 3 months worth of history.

In any case, whatsmeow has no control over how it's implemented by whatsapp

**Comment by zhiru** [comment]
hmmm So the ideal, for example, would be to create a filter so that if we pass a date it validates the timestamp of the message and ignores it?

**Comment by hugodeco** [comment]
we saw that exists a method to do a request for history sync, and it works since the messages ids that are requested, doesnt exists in whatsmeow database. Can you create a method to cleanup this internal history based on a timestamp ?
So, we can use that cleanup method with the history sync method and all will be flowers ...
