### ISSUE TITLE
Client outdated (405) connect failure (client version: 2.2329.9)

### ISSUE THREAD

**Issue by gleandroj** [tulir/whatsmeow#598]
May 27 19:12:22 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/net/http/server.go:2109 +0x2f
May 27 19:12:22 whatsapp leantrack_whatsapp[5460]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc000104780, {0xe2b1a8, 0xc000120000}, 0xc0000a9200)
May 27 19:12:22 whatsapp leantrack_whatsapp[5460]:         /builds/fabersoftbr/leantrack_whatsapp/vendor/github.com/gorilla/mux/mux.go:210 +0x1cf
May 27 19:12:22 whatsapp leantrack_whatsapp[5460]: net/http.serverHandler.ServeHTTP({0xe28760?}, {0xe2b1a8, 0xc000120000}, 0xc0000a9200)
May 27 19:12:22 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/net/http/server.go:2947 +0x30c
May 27 19:12:22 whatsapp leantrack_whatsapp[5460]: net/http.(*conn).serve(0xc0002ca500, {0xe2bd70, 0xc000354ed0})
May 27 19:12:22 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/net/http/server.go:1991 +0x607
May 27 19:12:22 whatsapp leantrack_whatsapp[5460]: created by net/http.(*Server).Serve
May 27 19:12:22 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/net/http/server.go:3102 +0x4db
May 27 19:12:22 whatsapp leantrack_whatsapp[5460]: 19:12:22.133 [Database/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF
May 27 19:16:30 whatsapp leantrack_whatsapp[5460]: 7:16PM INF Instance [159] - Generating a new QR Code
May 27 19:16:30 whatsapp leantrack_whatsapp[5460]: 7:16PM INF Instance [159] - Getting QR Code.
May 27 19:16:30 whatsapp leantrack_whatsapp[5460]: 7:16PM INF Instance [159] - Waiting for QR Code Scan.
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: 19:16:32.735 [Database ERROR] Client outdated (405) connect failure (client version: 2.2329.9)
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: 7:16PM INF Instance [159] - Event [err-client-outdated], Error [<nil>].
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: 2024/05/27 19:16:32 http: panic serving 127.0.0.1:47830: runtime error: invalid memory address or nil pointer dereference
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: goroutine 173 [running]:
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: net/http.(*conn).serve.func1()
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/net/http/server.go:1850 +0xbf
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: panic({0xbfd4e0, 0x131ca00})
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/runtime/panic.go:890 +0x262
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: gitlab.com/fabersoft/leantrack_whatsapp/src/app/http/controllers.getQrCode(0xc000120620)
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /builds/fabersoftbr/leantrack_whatsapp/src/app/http/controllers/instancecontroller.go:166 +0x131
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: gitlab.com/fabersoft/leantrack_whatsapp/src/app/http/controllers.CreateInstance({0xe2b1a8, 0xc000120460}, 0xc0000bb500)
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /builds/fabersoftbr/leantrack_whatsapp/src/app/http/controllers/instancecontroller.go:82 +0x1bb
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: net/http.HandlerFunc.ServeHTTP(0xe2bd70?, {0xe2b1a8?, 0xc000120460?}, 0xe20db0?)
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/net/http/server.go:2109 +0x2f
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: gitlab.com/fabersoft/leantrack_whatsapp/src/app/http/middlewares.glob..func1.1({0xe2b1a8, 0xc000120460}, 0xc0000ba600)
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /builds/fabersoftbr/leantrack_whatsapp/src/app/http/middlewares/auth.go:75 +0x45c
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: net/http.HandlerFunc.ServeHTTP(0xc0000ba500?, {0xe2b1a8?, 0xc000120460?}, 0xc0000679e0?)
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/net/http/server.go:2109 +0x2f
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc000104780, {0xe2b1a8, 0xc000120460}, 0xc0000ba400)
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /builds/fabersoftbr/leantrack_whatsapp/vendor/github.com/gorilla/mux/mux.go:210 +0x1cf
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: net/http.serverHandler.ServeHTTP({0xe28760?}, {0xe2b1a8, 0xc000120460}, 0xc0000ba400)
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/net/http/server.go:2947 +0x30c
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: net/http.(*conn).serve(0xc0001cc960, {0xe2bd70, 0xc000354ed0})
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/net/http/server.go:1991 +0x607
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: created by net/http.(*Server).Serve
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]:         /usr/local/go/src/net/http/server.go:3102 +0x4db
May 27 19:16:32 whatsapp leantrack_whatsapp[5460]: 19:16:32.741 [Database/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by ALiwoto** [comment]
@gleandroj you are getting "Event [err-client-outdated]" error. what is the whatsmeow version you are using? Make sure it's upgraded to the latest version:
`go get -u go.mau.fi/whatsmeow`
