### ISSUE TITLE
Audio VN (PTT) cant play in iOS

### ISSUE THREAD

**Issue by azickri** [tulir/whatsmeow#599]
Hello, Whatsmeow Team.

I have used whatsmeow for our application, it is lighter to run than other packages.
We experienced problems when we wanted to send an Audio Message when ptt was true, our audio file was .ogg.
But, when the receiver is Android as well as Web it works fine.

Code example

```
seconds := helper.GetAudioDuration(filepath)
ptt := false
audiotype := "audio/mpeg"

if mimetype == "audio/ogg" {
	audiotype = "audio/ogg; codecs=opus"
	ptt = true
}

AudioMessage: &waProto.AudioMessage{
	Url:              proto.String(uploaded.URL),
	DirectPath:       proto.String(uploaded.DirectPath),
	MediaKey:         uploaded.MediaKey,
	Mimetype:         proto.String(audiotype), // audio/ogg for ptt is true
	FileEncSha256:    uploaded.FileEncSHA256,
	FileSha256:       uploaded.FileSHA256,
	FileLength:       proto.Uint64(uint64(len(data))),
	Seconds:          &seconds,
	Ptt:              &ptt,
	ContextInfo:      messageContextInfo,
	StreamingSidecar: []byte(*proto.String("QpmXDsU7YLagdg==")),
	Waveform:         []byte(*proto.String("OjAnExISDgsKCAkJBwgkHAQEBBEFAwMNAxAcKCgkFzM0QUE4Jh4eKAoKChcLCwkeFgkJCQo3JiQmIiIRPz8/Ow==")),
},
```

**Comment by ahmedRSA** [comment]
invalid encoded audio

**Comment by mikhikhi** [comment]
hi
thanks for awesome work,
anyone can find solution for "no longer available media" in IOS?

**Comment by azickri** [comment]
I forgot to close this issue, for those looking for a solution the audio must be converted to 16000kHz frequency so it can be played on iOS

https://github.com/tulir/whatsmeow/issues/517
