### ISSUE TITLE
Invalid information 

### ISSUE THREAD

**Issue by victormedranop** [tulir/whatsmeow#6]
Hi everyone I test this example 4 times and give me the same result.
some times data come with the information right but some times does not.

**from a samsung phone with WhatsApp updated **

16:42:01.830 [Client/Recv DEBUG] <message from="18294403683@s.whatsapp.net" id="DC89E3C9A9BCA3EE99B99DF5F8FACBB2" notify="Victor Medrano" t="1634848921" type="text"><enc type="pkmsg" v="2"></enc></message>
16:42:01.830 [Client DEBUG] Decrypting 1 messages from 18294403683@s.whatsapp.net
[WARNING] 2021-10-21T16:42:01-04:00 Session.go:118 ▶  We've already setup a session for this V3 message, letting bundled message fall through...

from phone number -> 18X9X4X3X8X -------> here
Timestamp -> 1634848921
Message -> Yeah 

16:42:01.834 [Main INFO] Received message: &{Info:{MessageSource:{Chat:18294403683@s.whatsapp.net Sender:18294403683@s.whatsapp.net IsFromMe:false IsGroup:false} ID:DC89E3C9A9BCA3EE99B99DF5F8FACBB2 Type: Notify:Victor Medrano Timestamp:1634848921 Category: DeviceSentMeta:<nil>} Message:conversation:"Yeah"  messageContextInfo:{deviceListMetadata:{recipientKeyHash:"9\xac\xcaI:\xad\xca\xcc\xc1\x93"  recipientTimestamp:1634832216}  deviceListMetadataVersion:2} IsEphemeral:false IsViewOnce:false RawMessage:conversation:"Yeah"  messageContextInfo:{deviceListMetadata:{recipientKeyHash:"9\xac\xcaI:\xad\xca\xcc\xc1\x93"  recipientTimestamp:1634832216}  deviceListMetadataVersion:2}}
16:42:01.834 [Client/Send DEBUG] <receipt id="DC89E3C9A9BCA3EE99B99DF5F8FACBB2" to="18294403683@s.whatsapp.net" type="inactive"/>
16:42:01.834 [Client/Send DEBUG] <ack class="message" id="DC89E3C9A9BCA3EE99B99DF5F8FACBB2" to="18294403683@s.whatsapp.net"/>
16:42:02.117 [Client/Recv DEBUG] <receipt from="18092155887@s.whatsapp.net" id="DC89E3C9A9BCA3EE99B99DF5F8FACBB2" recipient="18294403683@s.whatsapp.net" t="1634848922"/>
16:42:02.117 [Client/Send DEBUG] <ack class="receipt" id="DC89E3C9A9BCA3EE99B99DF5F8FACBB2" recipient="18294403683@s.whatsapp.net" to="18092155887@s.whatsapp.net"/>
16:42:02.117 [Main INFO] Received receipt: &{MessageSource:{Chat:18294403683@s.whatsapp.net Sender:18092155887@s.whatsapp.net IsFromMe:true IsGroup:false} MessageID:DC89E3C9A9BCA3EE99B99DF5F8FACBB2 Timestamp:2021-10-21 16:42:02 -0400 AST Type: PreviousIDs:[]}

**but with another phone Chinese with no update whatsapp came this** 
16:39:21.082 [Client DEBUG] Decrypting 1 messages from 18095810178@s.whatsapp.net in status@broadcast
[WARNING] 2021-10-21T16:39:21-04:00 Session.go:118 ▶  We've already setup a session for this V3 message, letting bundled message fall through...

from phone number -> status -------> here suppose to come the phone number
Timestamp -> 1634848760
Message ->

16:39:21.086 [Main INFO] Received message: &{Info:{MessageSource:{Chat:status@broadcast Sender:18095810178@s.whatsapp.net IsFromMe:false IsGroup:true} ID:3A98213C0043E943F06A Type: Notify:Elianny♥️ Timestamp:1634848760 Category: DeviceSentMeta:<nil>} Message:protocolMessage:{key:{remoteJid:"status@broadcast"  fromMe:true  id:"3AAD9A96B2E5EB2FF96E"}  type:REVOKE}  messageContextInfo:{deviceListMetadata:{recipientKeyHash:"9\xac\xcaI:\xad\xca\xcc\xc1\x93"}  deviceListMetadataVersion:2} IsEphemeral:false IsViewOnce:false RawMessage:protocolMessage:{key:{remoteJid:"status@broadcast"  fromMe:true  id:"3AAD9A96B2E5EB2FF96E"}  type:REVOKE}  messageContextInfo:{deviceListMetadata:{recipientKeyHash:"9\xac\xcaI:\xad\xca\xcc\xc1\x93"}  deviceListMetadataVersion:2}}

the name it's not the name of the Chinese phone, and in the phone number came the message. I haven't change anything in the example just run the main.go I will think that this is for beta test from whatsapp. but the contact that is displaying is not he original sender is different , but the message text message is real.

***and in the whatsapp application the message is not display, I saw the notification but no display the message.***

I will upload basic logs file

[example.log](https://github.com/tulir/whatsmeow/files/7392788/example.log)

Victor

**Comment by tulir** [comment]
So what's the issue? That first log looks like a normal message, the second one is someone removing a status broadcast message?

**Comment by victormedranop** [comment]
if you like you can access to my server and check this out.
