### ISSUE TITLE
List Message not working

### ISSUE THREAD

**Issue by askareija** [tulir/whatsmeow#600]
So i tried to send list message like this:

```go
message := &waE2E.Message{
		ListMessage: &waE2E.ListMessage{
			Title:       proto.String("Daftar Menu"),
			Description: proto.String("Silakan lihat daftar menu dengan klik tombol dibawah"),
			ButtonText:  proto.String("ButtonText"),
			FooterText:  proto.String("Footer Section"),
			ListType:    waE2E.ListMessage_PRODUCT_LIST.Enum(),
			ProductListInfo: &waE2E.ListMessage_ProductListInfo{
				ProductSections: []*waE2E.ListMessage_ProductSection{
					{
						Title: proto.String("Row 1"),
						Products: []*waE2E.ListMessage_Product{
							{
								ProductID: proto.String("row1"),
							},
						},
					},
					{
						Title: proto.String("row 2"),
						Products: []*waE2E.ListMessage_Product{
							{
								ProductID: proto.String("row2"),
							},
						},
					},
				},
			},
		},
	}
```

I send it and received both on Android and web. But the button doesn't work.
![gambar](https://github.com/tulir/whatsmeow/assets/21377617/f0ac31e8-4cba-4de8-9457-3ae9f4f91e44)

when i clicked on web it doesn't show anything, and when i click on Android the WhatsApp force closed. Is there anything wrong with my code or is it doesnt supported yet?

**Comment by ahmedRSA** [comment]
baileys got rekt because they constantly pushed button fixes 
we don't need anything button related on whatsmeow.

if you need buttons, use official API. 
close the issue pls.

**Comment by askareija** [comment]
@ahmedRSA i'm not using buttons, i'm using list message. i'm asking why the menu list is not working, is it deprecated or there is something wrong with my code

**Comment by hrizal** [comment]
No you cannot use this for
list message and buttons
since last year

Pada Kam, 30 Mei 2024 15.51, Aden Aziz H ***@***.***> menulis:

**Comment by tulir** [comment]
The protobufs are defined by whatsapp, the fields and what is deprecated or not deprecated is not related to whatsmeow.

**Comment by askareija** [comment]
List message is working on Evolution API (https://github.com/EvolutionAPI/evolution-api)
![gambar](https://github.com/tulir/whatsmeow/assets/21377617/d752e78b-0914-41ba-9059-91f8cef0b7e0)

![gambar](https://github.com/tulir/whatsmeow/assets/21377617/388f73fe-1799-4d66-b96d-1844317a9ae9)

maybe we should check that out
