### ISSUE TITLE
No new message notification on phone if message received in whatsmeow

### ISSUE THREAD

**Issue by zhiru** [tulir/whatsmeow#605]
The notification of the received message does not appear on the phone if the message is also received in whatsmeow. How can I get notifications for new messages on my phone?

here is the code that i`m using to connect:

![image](https://github.com/tulir/whatsmeow/assets/4226997/32a0a275-e310-4514-ab0f-307176b21a97)

like #262 

PS: everything is working, sending, receiving, but just the notifications is not working

@hugodeco

**Comment by ahmedRSA** [comment]
when you connect precense wil set to availble

**Comment by zhiru** [comment]
> when you scan precense wil set to availble


So I have to define the presence before scanning, then there is no way to change it, that's what I understand, right?

**Comment by ahmedRSA** [comment]
why brazil people so dumb in coding ?

**Comment by ahmedRSA** [comment]
> > when you scan precense wil set to availble
> 
> So I have to define the presence before scanning, then there is no way to change it, that's what I understand, right?

you are already setting presence before scanning 
after scanning you change precense any time you want

**Comment by zhiru** [comment]
> why brazil people so dumb in coding ?

If you're not here to help, just ignore and let others respond, I don't need your insults!

Let's maintain respect so that everyone can learn and contribute in a positive way.

**Comment by zhiru** [comment]
> > > when you scan precense wil set to availble
> > 
> > 
> > So I have to define the presence before scanning, then there is no way to change it, that's what I understand, right?
> 
> you are already setting presence before scanning after scanning you change precense any time you want

Do not tell me! serious? If you read a little and read the title you will see that even though everything is working and even changing the presence to unavaible, we still do not receive the notification. When you responded, what I understood was that it was only before the scan that you could set the presence.

If you see my code you will see that right after connecting to whatsmeow I passed it as unavaible, which I use after having already scanned.

If you have something that can help without offending about receiving notifications on device, I would appreciate it, if not I do not need your comments.

**Comment by hugodeco** [comment]
Any parameter I define in "SendPresence" brings the same result. Still no "PUSH" notifications

**Comment by hugodeco** [comment]
No, its only happen when connected by whatsmeow

**Comment by PurpShell** [comment]
set the presence to unavailable. You should do this every 15 seconds

**Comment by zhiru** [comment]
Thanks @PurpShell we will try!

Do you know if is possible to verify/consult the presence?

**Comment by PurpShell** [comment]
> Thanks @PurpShell we will try!
> 
> Do you know if is possible to verify/consult the presence?

You can subscribe to your number from another number, or perhaps just still a little monitor like this one (https://gist.github.com/PurpShell/9e9200632abfd6289b89cca1f9ebd1ba) on another Web session and click on your chat to see the <presence> node coming from WA

**Comment by hugodeco** [comment]
Resolved !

**Comment by geanrt** [comment]
> set the presence to unavailable. You should do this every 15 seconds

Dude, isn't there a better method? This loop thing smells like a server crash to me...

**Comment by devlikepro** [comment]
@geanrt 
It doesn't have to be every 15 seconds, afaik. 
But whenever you do something (like send a message/set "typing"/etc) - after this it's a good practice to mark the connection as offline.

You should check the official web version and see how it works there (when it sends presence) and basically replicate this behaviour.
