### ISSUE TITLE
Re-request media from phone

### ISSUE THREAD

**Issue by idontneedgithub** [tulir/whatsmeow#607]
Hi, i've encountered an issue while trying to work with the historysync updates. Basically, media older than one month is not available on the WhatsApp's cdns directly and the request fails with either a 410 Gone or a 403 Forbidden. After some googling around i found out there should be a method to prompt the websocket to ask for a media reupload from the phone that the official clients do use when this happens, could this be implemented in whatsmeow?

**Comment by tulir** [comment]
https://pkg.go.dev/go.mau.fi/whatsmeow#Client.SendMediaRetryReceipt
