### ISSUE TITLE
 Questions about database

### ISSUE THREAD

**Issue by zhenchuanpeng** [tulir/whatsmeow#608]
Hi, I want to create WhatsApp account filtering feature. How do I obtain this example database file: examplestore.db?

**Comment by tulir** [comment]
Databases are created automatically, you don't obtain them from anywhere

**Comment by zhenchuanpeng** [comment]
So how do I use this client example?

**Comment by Manjit2003** [comment]
> So how do I use this client example?

https://github.com/tulir/whatsmeow/tree/main/mdtest
