### ISSUE TITLE
Not sending sync data

### ISSUE THREAD

**Issue by idontneedgithub** [tulir/whatsmeow#620]
Sometimes in (rare cases) when logging in WhatsApp doesnt seem to send HistorySync updates, is there any method to prompt WhatsApp into sending the sync data?

**Comment by PurpShell** [comment]
I'll need to see if whatsmeow cosplays as a desktop device such that we get all historysync options

**Comment by idontneedgithub** [comment]
yes

**Comment by PurpShell** [comment]
> yes

That is odd

**Comment by idontneedgithub** [comment]
Like i said there's no way to trigger historysync updates? Sometimes whatsmeow just connects and recieves nothing
