### ISSUE TITLE
[Client WARN] Failed to parse <meta> node in 774CB66BF4BB7D3336: [didn't find required attribute 'target_id']

### ISSUE THREAD

**Issue by ashuvax** [tulir/whatsmeow#621]

**Comment by PurpShell** [comment]
mhm

**Comment by hbinduni** [comment]
i found this issue too exist in current mdtest. bot still working but better if we can just remove this warning

**Comment by PurpShell** [comment]
yeah i kinda made this warning appear with one of my prs

**Comment by brunoaduarte** [comment]
How to fix this error ?

**Comment by PurpShell** [comment]
This is not an error. Do not worry
