### ISSUE TITLE
Bug send reply message (in receiver not work)

### ISSUE THREAD

**Issue by endasuhadi** [tulir/whatsmeow#622]
this is display in sender (server)
![on-server](https://github.com/tulir/whatsmeow/assets/47001274/2c5fddd4-d5b7-4ede-ba35-b579e1c4a2d9)

this is display in receiver
![on-client](https://github.com/tulir/whatsmeow/assets/47001274/f6803120-e958-4b5f-901e-3434a6723abc)

please help

**Comment by tulir** [comment]
Message content is set in your code, so it's not a whatsmeow issue
