### ISSUE TITLE
"CallLogMesssage" (?)

### ISSUE THREAD

**Issue by idontneedgithub** [tulir/whatsmeow#634]
I believe this is either a mistype in the protobuf or an error in the library
It seems to be never set even when "call" messages (missed call and such) are encountered

**Comment by idontneedgithub** [comment]
https://pkg.go.dev/go.mau.fi/whatsmeow/proto/waE2E#Message

**Comment by tulir** [comment]
The protobuf schema is decided by whatsapp, the library doesn't have errors or mistypes

**Comment by idontneedgithub** [comment]
am i using the wrong type then? im expecting some call log messages (the one it sends when the other party misses the call for example) but it doesnt seem to be present in this parameter at least not on the historysync updates

**Comment by tulir** [comment]
I'd guess that's not a real message type that gets sent, but rather something that's generated by clients (and maybe included in history syncs when logging into a new device)

**Comment by idontneedgithub** [comment]
Im positive its coming from this
https://pkg.go.dev/go.mau.fi/whatsmeow/proto/waSyncAction#CallLogRecord

Thanks for the clarification, i'll stop it here

**Comment by tulir** [comment]
Sync actions are not messages, they're an entirely different thing called app state. Some app state types have proper events in whatsmeow (https://github.com/tulir/whatsmeow/blob/main/types/events/appstate.go), but not all of them do. For ones that don't, you can either listen to the raw `*events.AppState` or make a PR to add a proper event for it

**Comment by idontneedgithub** [comment]
I've tried catching *waSyncAction.CallLogAction since the historysync parameter came empty and it seems it wasn't sent, is there any default setting preventing call logs from being requested or its just whatsapp being fussy?
