### ISSUE TITLE
Audio Message decrypt problem

### ISSUE THREAD

**Issue by tasovayasin** [tulir/whatsmeow#636]
How can decrypt .enc audio message? I can get audio received message. url :(audioMessage:(URL:"sample") and key:(mediaKey:"sample").
But i cant decrypt .enc file.

**Comment by tulir** [comment]
https://pkg.go.dev/go.mau.fi/whatsmeow#Client.Download

**Comment by tasovayasin** [comment]
thats work. thanks.
val, er := cli.Download(evt.Message.AudioMessage)

**Comment by tasovayasin** [comment]
thats work, thanks.
val, err := cli.Download(evt.Message.GetAudioMessage())
