### ISSUE TITLE
How can I install and run this project?

### ISSUE THREAD

**Issue by enskpl** [tulir/whatsmeow#64]
Hello,
I don't know Go at all, I've never worked in either of them before.
But I want to use this package.
Even though I struggled for hours, I could not understand how to install and run it, I am constantly encountering errors.
Could someone please send me a detailed document on how to install and run this project?
Thanks.

**Comment by tulir** [comment]
This is a library, not a program for end users. Knowing Go is a prerequisite.

Some of the projects using the library may be targeted at end users, but those projects will have their own documentation for setting up.
