### ISSUE TITLE
group create ban issue

### ISSUE THREAD

**Issue by ahmedRSA** [tulir/whatsmeow#645]
what is the proper way to create a group 

i have tried both new and aged (2+yrs old number) numbers they both get banned when creating group 

- users are messaging me first so its not spam [the one i am adding]
- users are saved in my contact list 

i want to know from if tulir can help or any experienced guy 
what is the proper way to create a group without getting banned

**Comment by weskerty** [comment]
Adding people to a group with a bot, even if it has contacts, will send the number to support. This also happens with baileys
