### ISSUE TITLE
When I send a docx file it turns into a zip file

### ISSUE THREAD

**Issue by tasovayasin** [tulir/whatsmeow#648]
I can send pdf or txt but i can't send docx file.
  
  
    msgV = &waE2E.Message{DocumentMessage: &waE2E.DocumentMessage{
	    Caption:       proto.String(caption),
	    URL:           proto.String(uploaded.URL),
	    DirectPath:    proto.String(uploaded.DirectPath),
	    MediaKey:      uploaded.MediaKey,
	    Mimetype:      proto.String(http.DetectContentType([]byte(data))),
	    FileEncSHA256: uploaded.FileEncSHA256,
	    FileSHA256:    uploaded.FileSHA256,
	    FileLength:    proto.Uint64(uint64(len(data))),
    }}
    
    }
    
    resp, err := cli.SendMessage(context.Background(), recipient, msgV, whatsmeow.SendRequestExtra{
    MediaHandle: uploaded.Handle,
    })

**Comment by tulir** [comment]
This is just user error, whatsmeow does not touch files
