### ISSUE TITLE
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:38:2: too many errors

### ISSUE THREAD

**Issue by slackale** [tulir/whatsmeow#649]
Greetings

I have this error when trying to "go run ."

# go.mau.fi/whatsmeow/binary/proto
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:28:2: ADVEncryptionType redeclared in this block
        vendor/go.mau.fi/whatsmeow/binary/proto/def.pb.go:25:6: other declaration of ADVEncryptionType
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:29:2: KeepType redeclared in this block
        vendor/go.mau.fi/whatsmeow/binary/proto/def.pb.go:81:6: other declaration of KeepType
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:30:2: PeerDataOperationRequestType redeclared in this block
        vendor/go.mau.fi/whatsmeow/binary/proto/def.pb.go:140:6: other declaration of PeerDataOperationRequestType
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:31:2: MediaVisibility redeclared in this block
        vendor/go.mau.fi/whatsmeow/binary/proto/def.pb.go:205:6: other declaration of MediaVisibility
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:32:2: DeviceProps_PlatformType redeclared in this block
        vendor/go.mau.fi/whatsmeow/binary/proto/def.pb.go:264:6: other declaration of DeviceProps_PlatformType
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:34:2: HistorySyncNotification_HistorySyncType redeclared in this block
        vendor/go.mau.fi/whatsmeow/binary/proto/def.pb.go:837:6: other declaration of HistorySyncNotification_HistorySyncType
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:35:2: HighlyStructuredMessage_HSMLocalizableParameter_HSMDateTime_HSMDateTimeComponent_DayOfWeekType redeclared in this block
        vendor/go.mau.fi/whatsmeow/binary/proto/def.pb.go:908:6: other declaration of HighlyStructuredMessage_HSMLocalizableParameter_HSMDateTime_HSMDateTimeComponent_DayOfWeekType
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:36:2: HighlyStructuredMessage_HSMLocalizableParameter_HSMDateTime_HSMDateTimeComponent_CalendarType redeclared in this block
        vendor/go.mau.fi/whatsmeow/binary/proto/def.pb.go:979:6: other declaration of HighlyStructuredMessage_HSMLocalizableParameter_HSMDateTime_HSMDateTimeComponent_CalendarType
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:37:2: GroupInviteMessage_GroupType redeclared in this block
        vendor/go.mau.fi/whatsmeow/binary/proto/def.pb.go:1035:6: other declaration of GroupInviteMessage_GroupType
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:38:2: ExtendedTextMessage_PreviewType redeclared in this block
        vendor/go.mau.fi/whatsmeow/binary/proto/def.pb.go:1091:6: other declaration of ExtendedTextMessage_PreviewType
vendor/go.mau.fi/whatsmeow/binary/proto/legacy.go:38:2: too many errors

Tried with golang version 1.21.6 and 1.23.0

Thank you.

**Comment by tulir** [comment]
Vendoring Go modules is generally not recommended. If you do vendor packages, you at least need to do it correctly, which means removing old files when they're deleted.

**Comment by slackale** [comment]
Ok, so I changed my Dockerfile and the error is somewhat still the same:

 => ERROR [6/6] RUN CGO_ENABLED=0 GOOS=linux go build -o /whatsmeow                                                                            53.4s
------                                                                                                                                               
 > [6/6] RUN CGO_ENABLED=0 GOOS=linux go build -o /whatsmeow:                                                                                        
#0 51.81 # go.mau.fi/whatsmeow/binary/proto                                                                                                          
#0 51.81 binary/proto/legacy.go:28:2: ADVEncryptionType redeclared in this block                                                                     
#0 51.81        binary/proto/def.pb.go:26:6: other declaration of ADVEncryptionType                                                                  
#0 51.81 binary/proto/legacy.go:29:2: KeepType redeclared in this block                                                                              
#0 51.81        binary/proto/def.pb.go:82:6: other declaration of KeepType
#0 51.81 binary/proto/legacy.go:30:2: PeerDataOperationRequestType redeclared in this block
#0 51.81        binary/proto/def.pb.go:141:6: other declaration of PeerDataOperationRequestType
#0 51.81 binary/proto/legacy.go:31:2: MediaVisibility redeclared in this block
#0 51.81        binary/proto/def.pb.go:206:6: other declaration of MediaVisibility
#0 51.81 binary/proto/legacy.go:32:2: DeviceProps_PlatformType redeclared in this block
#0 51.81        binary/proto/def.pb.go:265:6: other declaration of DeviceProps_PlatformType
#0 51.81 binary/proto/legacy.go:33:2: ImageMessage_ImageSourceType redeclared in this block
#0 51.81        binary/proto/def.pb.go:384:6: other declaration of ImageMessage_ImageSourceType
#0 51.81 binary/proto/legacy.go:34:2: HistorySyncNotification_HistorySyncType redeclared in this block
#0 51.81        binary/proto/def.pb.go:443:6: other declaration of HistorySyncNotification_HistorySyncType
#0 51.81 binary/proto/legacy.go:35:2: HighlyStructuredMessage_HSMLocalizableParameter_HSMDateTime_HSMDateTimeComponent_DayOfWeekType redeclared in this block
#0 51.81        binary/proto/def.pb.go:514:6: other declaration of HighlyStructuredMessage_HSMLocalizableParameter_HSMDateTime_HSMDateTimeComponent_DayOfWeekType
#0 51.81 binary/proto/legacy.go:36:2: HighlyStructuredMessage_HSMLocalizableParameter_HSMDateTime_HSMDateTimeComponent_CalendarType redeclared in this block
#0 51.81        binary/proto/def.pb.go:585:6: other declaration of HighlyStructuredMessage_HSMLocalizableParameter_HSMDateTime_HSMDateTimeComponent_CalendarType
#0 51.81 binary/proto/legacy.go:37:2: GroupInviteMessage_GroupType redeclared in this block
#0 51.81        binary/proto/def.pb.go:641:6: other declaration of GroupInviteMessage_GroupType
#0 51.81 binary/proto/legacy.go:37:2: too many errors

Dockerfile:

# syntax=docker/dockerfile:1

FROM golang:1.21.6

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/reference/dockerfile/#copy
ADD . ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /whatsmeow

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/reference/dockerfile/#expose
EXPOSE 54007

# Run
CMD ["/whatsmeow"]

**Comment by JustSoursop** [comment]
Is it the same issue https://github.com/jmoiron/sqlx/issues/203 ?
