### ISSUE TITLE
Get client jid from evt.message

### ISSUE THREAD

**Issue by tasovayasin** [tulir/whatsmeow#657]
how can i get client jid from received message?

**Comment by tulir** [comment]
The JID is stored in the client (`cli.Store.ID`). To access the client instance, [read the docs](https://pkg.go.dev/go.mau.fi/whatsmeow#Client.AddEventHandler).

Note that GitHub issues are for bugs and feature requests, not questions

**Comment by tulir** [comment]
I linked the docs above
