### ISSUE TITLE
Presencesubscribe won't work for non contact

### ISSUE THREAD

**Issue by enskpl** [tulir/whatsmeow#66]
After WhatsApp's recent update, if you don't have a history of messaging with a number, you cannot track that number.
Is there any way to get fix this?

**Comment by tulir** [comment]
No, clients can't bypass server-side restrictions

**Comment by enskpl** [comment]
@tulir
But I've seen apps that do this.
What do you think about it?
They run the presence feature without sending any message or information to the number.
