### ISSUE TITLE
send extend text message to status@broadcast failed

### ISSUE THREAD

**Issue by bodhi-code** [tulir/whatsmeow#668]
extend text message struct value is below：
{text:"hello" ,textArgb:4294967295,  backgroundArgb:4283943423,  font:SYSTEM,  previewType:NONE , inviteLinkGroupTypeV2:DEFAULT}

client log is below:
time="2024-10-08 19:42:57" level="warn" msg="[Client]Server returned different participant list hash when sending to status@broadcast. Some devices may not have received the message." file="E:/GoProject/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240726213518-bb5852f056ca/send.go:345" 
time="2024-10-08 19:42:57" level="debug" msg="[Client]Sent retry #1 for status@broadcast/3EB08032C8ECCB9ACADE0A to **132******10@s.whatsapp.net" file="E:/GoProject/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20240726213518-bb5852f056ca/retry.go:298" 

from this log result，send message retried it once， but eventually the send failed.

How to send extend text message to status@broadcast in right way? Can anyone give an example of the correct code?

**Comment by JustSoursop** [comment]
`Server returned different participant list hash when sending to status@broadcast. Some devices may not have received the message.`

Do you try to send status to specific jids ?

**Comment by bodhi-code** [comment]
how to send status to specific jids ?

**Comment by tulir** [comment]
Those logs look like it was sent to the server successfully

**Comment by bodhi-code** [comment]
i don't see the status on my cell phone

**Comment by bodhi-code** [comment]
> Those logs look like it was sent to the server successfully

 i don't see the status on my cell phone
