### ISSUE TITLE
How to obtain the specific reason for websocket disconnection?

### ISSUE THREAD

**Issue by xiaohuwei** [tulir/whatsmeow#674]
```
	case *events.Disconnected:
		fmt.Println("close")
```

How to obtain the specific reason for disconnection?

**Comment by tulir** [comment]
GitHub issues are for bugs and feature requests, not questions.

Some disconnections will be preceded by another event like StreamError, StreamReplaced or LoggedOut, but some are just plain disconnections with no reason
