### ISSUE TITLE
Mention chat not show in group

### ISSUE THREAD

**Issue by anggatinggalklik** [tulir/whatsmeow#675]
i have implement mention chat group like this 
`pattern := `@62\d{9,12}`
		re := regexp.MustCompile(pattern)
		matches := re.FindAllString(msg.Body, -1)
		if matches != nil {
			var mentionedJID []string
			for _, match := range matches {
				mentionedJID = append(mentionedJID, types.NewJID(strings.Replace(match, "@", "", 1), types.DefaultUserServer).ToNonAD().String())
			}

			if mentionedJID != nil {
				payload.ExtendedTextMessage = &waE2E.ExtendedTextMessage{
					Text: proto.String(msg.Body),
					ContextInfo: &waE2E.ContextInfo{
						MentionedJID: mentionedJID,
					},
				}
			}
		}`

no error in log but chat isnt show in group conversation

**Comment by JustSoursop** [comment]
Use discussion tab for protocol question.
