### ISSUE TITLE
[BUG] Edit Message Text with Image (Text is Gone after edited)

### ISSUE THREAD

**Issue by azickri** [tulir/whatsmeow#684]
Hi, tulir.

I have tried to change the Text Message that is present along with the Image, but when edited successfully, the text is gone from WhatsApp. Should I implement the Image Proto in the waProto.Message parameter?

My Code Example

```
_, err := session.Client.SendMessage(
  context.Background(),
  chatJID,
  session.Client.BuildEdit(chatJID, messageId, &waProto.Message{Conversation: proto.String(text)}),
)
```

![Screenshot from 2024-11-01 14-52-01](https://github.com/user-attachments/assets/5cb286ff-271b-453e-9133-2e10469f3c06)

**Comment by JustSoursop** [comment]
Image Message using caption 
```go
edited = &waE2E.Message{
    ImageMessage: &waE2E.ImageMessage{
        Caption: &caption,
    },
}
```
