### ISSUE TITLE
Use GetProfilePictureInfo to retrieve the profile picture, resulting in a bad request.

### ISSUE THREAD

**Issue by hicjcn** [tulir/whatsmeow#693]
`func (cli *Client) GetProfilePictureInfo(jid types.JID, params *GetProfilePictureParams) (*types.ProfilePictureInfo, error)`

When using this method, I consistently receive a bad request, and I'm unsure why. This is a code snippet.

```
	glog.Info(ctx, "getUserAvatar", c.jid.String(), existingId)
	avatar, err := c.client.GetProfilePictureInfo(*c.jid, &whatsmeow.GetProfilePictureParams{
		Preview:     false,
		ExistingID:  existingId,
		IsCommunity: false,
	})
	if err != nil {
		glog.Error(ctx, "GetProfilePicture error", err)
		return "", existingId
	}
```
The logs are as follows.
![image](https://github.com/user-attachments/assets/bae120ee-63ac-4442-b6d9-429247336a8f)

I hope to receive your assistance, thank you.

**Comment by azickri** [comment]
I try with this one, running normally.

`		pictureInfo, errorPicture := client.GetProfilePictureInfo(chatId, &whatsmeow.GetProfilePictureParams{Preview: true})
		if errorPicture == nil {
			picture = pictureInfo.URL
		}`

**Comment by tulir** [comment]
If you pass a JID that can't have an avatar (like an AD-JID instead of a plain user JID), the request will fail

**Comment by hicjcn** [comment]
Indeed, using `jid.ToNonAD()` to convert the JID allows one to access the avatar.
