### ISSUE TITLE
go-sqlite3 requires cgo to work

### ISSUE THREAD

**Issue by RaulJofre** [tulir/whatsmeow#70]
Failed to connect to database: failed to upgrade database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

I can't use CGO_ENABLED=1 in mac computer.

**Comment by tulir** [comment]
You can use cgo anywhere, it just requires a C compiler. Don't use cross-compiling as that complicates things.

**Comment by 42wim** [comment]
@RaulJofre YMMV, but you can use a pure go sqlite if you want

```golang
import _ "modernc.org/sqlite"

...

storeContainer, err := sqlstore.New("sqlite", "file:whatsapp.db?_foreign_keys=on&_pragma=busy_timeout=10000", nil)
```
