### ISSUE TITLE
Unavailable message on sending view_once messages

### ISSUE THREAD

**Issue by RianFC** [tulir/whatsmeow#705]
When receiving/sending a message as 'view once', it's giving a cryptography error. This is happening due to a WhatsApp update. Using an older version, it still works.

**Comment by Onichaa** [comment]
> What the error log ?

Connecting to whatsmeow...
Connected to whatsmeow!!
01:30:02.196 [Client INFO] Successfully authenticated
01:30:02.782 [Client WARN] Unavailable message 0A86B053B903CDB8483ECC9B5CFC470E from 62838xxxxxxx@s.whatsapp.net

**Comment by RianFC** [comment]
same error that occurred with me

**Comment by tulir** [comment]
If WhatsApp decided to stop sending view once messages, whatsmeow can't do anything about it
