### ISSUE TITLE
Read messages from database (sqlstore)

### ISSUE THREAD

**Issue by ibyter** [tulir/whatsmeow#714]
I want to read all messages directly from the database.

When I browser the SQL tables, I found the following, none of which contains the messages!:
```text
sqlite_master
whatsmeow_app_state_mutation_macs
whatsmeow_app_state_sync_keys
whatsmeow_app_state_version
whatsmeow_chat_settings
whatsmeow_contacts
whatsmeow_device
whatsmeow_identity_keys
whatsmeow_message_secrets
whatsmeow_pre_keys
whatsmeow_privacy_tokens
whatsmeow_sender_keys
whatsmeow_sessions
whatsmeow_version
```

Please let know if I'm missing something

**Comment by tulir** [comment]
whatsmeow doesn't store messages, you have to do it yourself if you want them later

**Comment by ibyter** [comment]
> whatsmeow doesn't store messages, you have to do it yourself if you want them later

How to implement it? Which methods can help me achieve that
