### ISSUE TITLE
some question about HistorySync

### ISSUE THREAD

**Issue by sodaling** [tulir/whatsmeow#74]
Hello, I would like to know what the enumeration values ​​of HistorySyncNotificationHistorySyncType defined in the proto file mean?

In other words, after I log in, there are 4 more .json files in the directory, two are syncType = 3, and one is syncType = 0. I would like to know, what does it mean for the different types to represent the history of this file? At the same time, what are the two files with syncType= 3 classified?

I really hope you can clear up your confusion, thanks

**Comment by tulir** [comment]
They pretty much mean what the names say.

`INITIAL_BOOTSTRAP` = first blob with chat list and some messages
`INITIAL_STATUS_V3` = status messages
`RECENT` = recent messages (can be multiple blobs)
`FULL` = more messages (might mean the 1 year sync, can be multiple blobs)
`PUSH_NAME` = user displaynames, no messages

**Comment by pfthink** [comment]
Hi ，how to get more displaynames？thanks
