### ISSUE TITLE
Panic error that restarts the service

### ISSUE THREAD

**Issue by gabrielphilipes** [tulir/whatsmeow#75]
It's been returning this error for a few days that restarts the service. Apparently it's when generating the key to decrypt. Does anyone know what can it be?

`
Mar 21 17:03:24 server6 relay[1722807]: 17:03:24.381 [Client WARN] Error decrypting message from xxxxx6927755@s.whatsapp.net in status@broadcast: failed to decrypt prekey message: p>
Mar 21 17:03:25 server6 relay[1722807]: 17:03:25.655 [Database ERROR] Failed to store session withxxxxxxx002:0: database is locked
Mar 21 17:03:26 server6 sshd[1732182]: Failed password for invalid user ly from 157.245.139.92 port 45926 ssh2
Mar 21 17:03:26 server6 relay[1722807]: 17:03:26.622 [Database ERROR] Failed to store session with xxxxxxx002:0: database is locked
Mar 21 17:03:26 server6 relay[1722807]: 17:03:26.782 [Database ERROR] Failed to save identity of xxxxxxx002:0: database is locked
Mar 21 17:03:27 server6 relay[1722807]: 17:03:27.741 [Database ERROR] Failed to load session with xxxxxxx1413:0: database is locked
**Mar 21 17:03:27 server6 relay[1722807]: panic: runtime error: invalid memory address or nil pointer dereference**
Mar 21 17:03:27 server6 relay[1722807]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc134ba]
Mar 21 17:03:27 server6 relay[1722807]: goroutine 1107582 [running]:
Mar 21 17:03:27 server6 relay[1722807]: go.mau.fi/libsignal/state/record.(*State).SenderChainKey(...)
Mar 21 17:03:27 server6 relay[1722807]:         /home/junior/go/pkg/mod/go.mau.fi/libsignal@v0.0.0-20220308120827-0d87a03fd7c7/state/record/SessionState.go:297
Mar 21 17:03:27 server6 relay[1722807]: go.mau.fi/libsignal/session.(*Cipher).Encrypt(0xc003f09330, {0xc001dfe700, 0x198, 0x380})
Mar 21 17:03:27 server6 relay[1722807]:         /home/junior/go/pkg/mod/go.mau.fi/libsignal@v0.0.0-20220308120827-0d87a03fd7c7/session/SessionCipher.go:71 +0x7a
Mar 21 17:03:27 server6 relay[1722807]: go.mau.fi/whatsmeow.(*Client).encryptMessageForDevice(0xc00151c000, {0xc0088bed00, 0x18d, 0x18d}, {{0xc002dbfdf0, 0xc}, 0x0, 0x0, {0x1061786, >
Mar 21 17:03:27 server6 relay[1722807]:         /home/junior/dev/go/meow/whatsmeow/send.go:356 +0x4dd
Mar 21 17:03:27 server6 relay[1722807]: go.mau.fi/whatsmeow.(*Client).encryptMessageForDeviceAndWrap(0x2, {0xc0088bed00, 0x0, 0x9ec48b}, {{0xc002dbfdf0, 0xc}, 0x0, 0x0, {0x1061786, 0>
Mar 21 17:03:27 server6 relay[1722807]:         /home/junior/dev/go/meow/whatsmeow/send.go:333 +0x59
Mar 21 17:03:27 server6 relay[1722807]: go.mau.fi/whatsmeow.(*Client).encryptMessageForDevices(0xc00151c000, {0xc0062f4000, 0x4, 0xc0050c2d80}, {0xc0063600d8, 0x14}, {0xc008c87e00, 0>
Mar 21 17:03:27 server6 relay[1722807]:         /home/junior/dev/go/meow/whatsmeow/send.go:289 +0xa0b
Mar 21 17:03:27 server6 relay[1722807]: go.mau.fi/whatsmeow.(*Client).prepareMessageNode(0x7f6184220638, {{0xc000367cd0, 0xc}, 0x0, 0x0, {0x1061786, 0xe}, 0x0}, {0xc0063600d8, 0x14},>
Mar 21 17:03:27 server6 relay[1722807]:         /home/junior/dev/go/meow/whatsmeow/send.go:216 +0x16b
Mar 21 17:03:27 server6 relay[1722807]: go.mau.fi/whatsmeow.(*Client).sendDM(0xc00151c000, {{0xc000367cd0, 0xc}, 0x0, 0x0, {0x1061786, 0xe}, 0x0}, {0xc0063600d8, 0x14}, ...)
Mar 21 17:03:27 server6 relay[1722807]:         /home/junior/dev/go/meow/whatsmeow/send.go:200 +0x21b
Mar 21 17:03:27 server6 relay[1722807]: go.mau.fi/whatsmeow.(*Client).SendMessage(0xc00151c000, {{0xc000367cd0, 0xc}, 0x0, 0x0, {0x1061786, 0xe}, 0x0}, {0xc0063600d8, 0x14}, ...)
Mar 21 17:03:27 server6 relay[1722807]:         /home/junior/dev/go/meow/whatsmeow/send.go:83 +0x270
Mar 21 17:03:27 server6 relay[1722807]: go.mau.fi/whatsmeow.(*Client).handleRetryReceipt(0xc00151c000, 0xc008a297a0, 0xc006eaddd0)
Mar 21 17:03:27 server6 relay[1722807]:         /home/junior/dev/go/meow/whatsmeow/retry.go:191 +0x16ce
Mar 21 17:03:27 server6 relay[1722807]: go.mau.fi/whatsmeow.(*Client).handleReceipt.func1()
Mar 21 17:03:27 server6 relay[1722807]:         /home/junior/dev/go/meow/whatsmeow/receipt.go:26 +0x33
Mar 21 17:03:27 server6 relay[1722807]: created by go.mau.fi/whatsmeow.(*Client).handleReceipt
`

**Comment by Valdenirmezadri** [comment]
I have the same problem

**Comment by moxovil** [comment]
+

**Comment by rafaellfmachado** [comment]
I have the same problem

**Comment by tulir** [comment]
You can only have one process using a single SQLite database at a time, use separate databases or postgres if you have multiple processes. Probably also can't have more than one `sqlstore.Container` using the same sqlite db (but multiple sessions within one container should be fine)

**Comment by moxovil** [comment]
can we at least remove the panic from the libsignal if the session returned as nil?
