### ISSUE TITLE
Media Audio not send

### ISSUE THREAD

**Issue by danielspk** [tulir/whatsmeow#77]
Hello, does anyone else have errors to send audio type messages? I don't get any kind of error. The file seems to upload fine but is never received.

Message:

```go
msg := &waProto.Message{
    AudioMessage: &waProto.AudioMessage{
        Url:           proto.String(uploaded.URL),
        DirectPath:    proto.String(uploaded.DirectPath),
        MediaKey:      uploaded.MediaKey,
        Mimetype:      proto.String(http.DetectContentType(data)),
        FileEncSha256: uploaded.FileEncSHA256,
        FileSha256:    uploaded.FileSHA256,
        FileLength:    proto.Uint64(uint64(len(data))),
    },
}`
```

**Comment by Romerito007** [comment]
> Hello, does anyone else have errors to send audio type messages? I don't get any kind of error. The file seems to upload fine but is never received.
> 
> Message:
> 
> ```go
> msg := &waProto.Message{
>     AudioMessage: &waProto.AudioMessage{
>         Url:           proto.String(uploaded.URL),
>         DirectPath:    proto.String(uploaded.DirectPath),
>         MediaKey:      uploaded.MediaKey,
>         Mimetype:      proto.String(http.DetectContentType(data)),
>         FileEncSha256: uploaded.FileEncSHA256,
>         FileSha256:    uploaded.FileSHA256,
>         FileLength:    proto.Uint64(uint64(len(data))),
>     },
> }`
> ```

Change mimetype to "audio/ogg; codecs=opus"

**Comment by danielspk** [comment]
Thanks @Romerito007.

This works!

**Comment by refaldyrk** [comment]
I Have same error but i change mimetype to audio/ogg; codecs=opus, still can't send
