### ISSUE TITLE
I got the following error when using MySQL

### ISSUE THREAD

**Issue by ratnokustiawan** [tulir/whatsmeow#82]
panic: failed to upgrade database: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'byte
a NOT NULL CHECK ( length(noise_key) = 32 ),
                identity_key bytea NOT NULL C' at line 6

**Comment by ratnokustiawan** [comment]
MySQL Version '5.7.37'

**Comment by tulir** [comment]
MySQL isn't supported. There's a PR for it at #48, but I'm not sure if it's possible to support simultaneously with Postgres, and Postgres takes priority.
