### ISSUE TITLE
Revoke Message seems not working properly

### ISSUE THREAD

**Issue by Dhaninovic** [tulir/whatsmeow#83]
Revoke message seems not working properly, when I call the function, the response is timestamp and there is no error, but when I see the revoked message in both recipient devices and sender devices, the message is still not revoked, did I missed something , cause I already follow the example in mdtest, here is my code to revoke the message : 
`timestamp, err := listconn[jid].Socket.RevokeMessage(parsejid, msgid)`
`return timestamp, err`

**Comment by tulir** [comment]
It works fine, but keep in mind that you can't revoke old messages and you can only revoke your own messages. (WhatsApp is working on changing both of those limits, but right now the limits are still there)
