### ISSUE TITLE
v.Message.GetConversation() not working with tags

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#86]
Hi, trying my first app, I noticed that the msg that has tag, like "hi @xxx" is not read at `v.Message.GetConversation()` is there another way or option to read them, and check if I'm the one who is tagged there or no?

**Comment by tulir** [comment]
Those are in `ExtendedTextMessage` (and the mention metadata specifically is inside `ContextInfo`). In general, you should just print the whole message object if you want to find out where some data is

**Comment by hajsf** [comment]
mm, `v.Message.ExtendedTextMessage.GetText()` worked only if there is a mentioned metadata, and `v.Message.GetConversation()` works only if no mentioned in the msg, shall I use both, is not there a way to get the msg text regardless it contains a mentiontag or no? thanks

**Comment by tulir** [comment]
You have to check both (since `Message` is just the raw data from whatsapp without any extra processing)
