### ISSUE TITLE
Sending html in the message

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#87]
Is there a way I can sen in the message, some thing like `<a href="https://www.w3schools.com">Visit W3Schools</a>` or even a styled `div` with `button` elements.
Not sure if this is supported by whatsapp wed itself or no.
Thanks

**Comment by tulir** [comment]
No.

https://faq.whatsapp.com/general/chats/how-to-format-your-messages/

**Comment by tulir** [comment]
Oh right, for buttons there are some business API things: https://github.com/tulir/whatsmeow/blob/main/binary/proto/def.proto#L963 (but you'll have to figure out how to use them yourself, and they might get you banned because they're meant to only be sent by business accounts)
