### ISSUE TITLE
Customize app name at linked devices screen

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#89]
At WhatsApp linked devices screen, the app name appears as: whatsmeow

Is therea way to customize it, so my app name be spending there?

![IMG_20220409_003137](https://user-images.githubusercontent.com/98168280/162535251-cbd32389-08fe-42c1-b196-f1fc096be36c.jpg)

**Comment by tulir** [comment]
https://github.com/tulir/whatsmeow/blob/main/store/clientpayload.go#L126-L133 (you can just change those directly from your code, e.g. `store.CompanionProps.Os = proto.String("foo")`)

**Comment by hajsf** [comment]
Appreciate your prompt response and feedback, thanks a lot.

**Comment by hajsf** [comment]
Hi again, is therea way to change the logo as well? Thanks
