### ISSUE TITLE
Upload without storing whole file in memory

### ISSUE THREAD

**Issue by biji** [tulir/whatsmeow#94]
Is it possible to `Upload()` big files like videos and documents without reading whole file to variable?
Probably that will save some memory

Thanks

**Comment by Serenity-77** [comment]
Upload once and cache the upload result

**Comment by tulir** [comment]
Currently not possible, but files are also limited to 100mb so there's no problem just reading the whole file to memory.

**Comment by Duckduckgot** [comment]
> Upload once and cache the upload result

But it is limited in time, then you will need to upload again.

**Comment by mamur-rezeki** [comment]
`Client.Upload` encrypt whole []byte in code before uploaded.

https://github.com/tulir/whatsmeow/blob/be0edabb0bf3d3f6401d9e6d9922373ed58a3487/upload.go#L63-L134

Seems impossible to implement io Reader directly from path to avoid high memory usage.

**Comment by tulir** [comment]
It's of course possible to implement, just requires a bunch of refactoring

**Comment by mamur-rezeki** [comment]
Alright, we will wait for it to be implement.

**Comment by Duckduckgot** [comment]
Someone please help to realize this useful feature.

**Comment by Duckduckgot** [comment]
Something's wrong.

```
func EncryptStream(key, iv []byte, reader io.Reader, writer io.Writer) error {
	block, err := aes.NewCipher(key)
	if err != nil {
		return err
	}

	var stream cipher.Stream
	if iv != nil {
		stream = cipher.NewCFBEncrypter(block, iv)
	} else {
		iv = make([]byte, aes.BlockSize)
		if _, err := io.ReadFull(rand.Reader, iv); err != nil {
			return err
		}

		stream = cipher.NewCFBEncrypter(block, iv)
		writer.Write(iv)
	}

	writer = &cipher.StreamWriter{S: stream, W: writer}

	if _, err := io.Copy(writer, reader); err != nil {
		return err
	}

	return nil
}
```

**Comment by Duckduckgot** [comment]
func encryptStream(key, iv, macKey []byte, reader io.Reader, writer io.Writer) ([]byte, []byte, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, nil, err
	}
	h1 := sha256.New()
	if _, err := io.Copy(h1, reader); err != nil {
		return nil, nil, err
	}
	FileSHA256 := h1.Sum(nil)
	var buf bytes.Buffer
	stream := cipher.NewCFBEncrypter(block, iv)
	encWriter := &cipher.StreamWriter{S: stream, W: &buf}

	h := hmac.New(sha256.New, macKey)
	if _, err := io.Copy(h, reader); err != nil {
		return nil, nil, err
	}
	mac := h.Sum(nil)
	mac10 := mac[:10]

	h2 := sha256.New()
	if _, err := io.Copy(encWriter, reader); err != nil {
		return nil, nil, err
	}
	if _, err := writer.Write(mac10); err != nil {
		return nil, nil, err
	}
	if _, err := io.Copy(h2, &buf); err != nil {
		return nil, nil, err
	}
	FileEncSHA256 := h2.Sum(nil)

	return FileSHA256, FileEncSHA256, nil
}

**Comment by ahmedRSA** [comment]
> ```
> func encryptStream(key, iv, macKey []byte, reader io.Reader, writer io.Writer) ([]byte, []byte, error) {
> 	block, err := aes.NewCipher(key)
> 	if err != nil {
> 		return nil, nil, err
> 	}
> 	h1 := sha256.New()
> 	if _, err := io.Copy(h1, reader); err != nil {
> 		return nil, nil, err
> 	}
> 	FileSHA256 := h1.Sum(nil)
> 	var buf bytes.Buffer
> 	stream := cipher.NewCFBEncrypter(block, iv)
> 	encWriter := &cipher.StreamWriter{S: stream, W: &buf}
> 
> 	h := hmac.New(sha256.New, macKey)
> 	if _, err := io.Copy(h, reader); err != nil {
> 		return nil, nil, err
> 	}
> 	mac := h.Sum(nil)
> 	mac10 := mac[:10]
> 
> 	h2 := sha256.New()
> 	if _, err := io.Copy(encWriter, reader); err != nil {
> 		return nil, nil, err
> 	}
> 	if _, err := writer.Write(mac10); err != nil {
> 		return nil, nil, err
> 	}
> 	if _, err := io.Copy(h2, &buf); err != nil {
> 		return nil, nil, err
> 	}
> 	FileEncSHA256 := h2.Sum(nil)
> 
> 	return FileSHA256, FileEncSHA256, nil
> }
> ```

you make it work?

**Comment by arugaz** [comment]
i can make it but it requires temporary file to place the enc data, if thats not a problem i'll do pull request

**Comment by Duckduckgot** [comment]
> i can make it but it requires temporary file to place the enc data, if thats not a problem i'll do pull request
> 
> edit: ill find out to avoid that

Is there any progress?

**Comment by gamersindo1223** [comment]
@Duckduckgot any progress?

**Comment by mamur-rezeki** [comment]
According to @arugaz comment.

Temporarily storing `plaintext` and `dataToUpload` to disk for read-write may reduce RAM memory usage rather than use buffer variable like `bytes.Reader` or `[]byte` to pass to the another func.

**Comment by gamersindo1223** [comment]
yeah

**Comment by Epikcoder** [comment]
@Duckduckgot any progress?

**Comment by arugaz** [comment]
I've been busy the last few months, haven't test it yet, also the call function :crying_cat_face: 

![image](https://github.com/user-attachments/assets/ddf18a43-c3d8-490a-a2fe-679ea8bcefcc)

**Comment by arugaz** [comment]
@tulir nice work that same as mine, is it good to use pool?

```
var bytePool = sync.Pool{
    New: func() interface{} {
        return make([]byte, 32*1024)
    },
}
```
