### ISSUE TITLE
Checking Message type

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#97]
Hi, I aware there are many types of messages, and to read them we use `evt.Message.Get{MessageType}Message()`, something like `evt.Message.GetListResponseMessage()`

Is there a way to check the `MessageType` so I cane use it in `select` statement or so?

**Comment by tulir** [comment]
No, but you can still use it in a `select` statement:

```go
select {
case evt.Message.Conversation != nil:
    ...
case evt.Message.ListResponseMessage != nil:
    ...
}
```
