### ISSUE TITLE
error when message sent from whatsapp desktop  (Version 2.2212.8)

### ISSUE THREAD

**Issue by hrizal** [tulir/whatsmeow#98]
i got error like this

[client.go 511] Event handler panicked while handling a *events.Message: runtime error: slice bounds out of range [:-1]

when message come from whatsapp desktop (Version 2.2212.8) .
from other whatsapp is working fine

**Comment by tulir** [comment]
That's most likely a bug in your code, the stack trace will say for sure (posting the stack trace is required anyway when reporting panics)

**Comment by hrizal** [comment]
Opps, you right 🙏
