### ISSUE TITLE
messageId from send message 

### ISSUE THREAD

**Issue by hrizal** [tulir/whatsmeow#99]
how to get messageId of sent message? so you can delete it later

**Comment by tulir** [comment]
https://pkg.go.dev/go.mau.fi/whatsmeow#Client.SendMessage

![image](https://user-images.githubusercontent.com/4224639/164909426-04602899-0854-47db-95e9-85aced03a007.png)

(also https://pkg.go.dev/go.mau.fi/whatsmeow#GenerateMessageID)

**Comment by hrizal** [comment]
Oww, thank you 🙏
